### ISSUE TITLE
Beatport Genre Tagging not working

### ISSUE THREAD

**Issue by lornz** [Marekkon5/onetagger#1]
I try to update the genre tag for my mp3 files with the help of Beatport.
OneTagger fails to find any of my tracks, although they are either bought at beatport or itunes.
I tried setting Strictness to 0%. Still no results
![image](https://user-images.githubusercontent.com/953762/118356720-ec4a6900-b576-11eb-8c22-5b975ce60ffa.png)

Anything I can do to debug this further?

**Comment by onetagger** [comment]
That's weird.
Can you sent me a few of those files?
A zippyshare link will do.

**Comment by bascurtiz** [comment]
I tried the same tracks with default settings in One Tagger. They all get matched.
You are aware One Tagger needs atleast a proper artist & title tag filled in, right?

Example with 1 artist + title filled in = found:
![image](https://user-images.githubusercontent.com/34075088/118365107-9e942780-b59b-11eb-9d17-b9ecfc591519.png)

Example with multipe artists + title filled = found
![image](https://user-images.githubusercontent.com/34075088/118365132-c2f00400-b59b-11eb-817f-d1fee6e90cb9.png)

**Comment by Marekkon5** [comment]
Closing becayse of inactivity
