### ISSUE TITLE
Quick Tag doesn't recognise all songs in library

### ISSUE THREAD

**Issue by Wohme** [Marekkon5/onetagger#104]
When I assigned my folder in Quick Tag to try out the feature, I noticed that 5 of the 7 files were recognised. There isn't a pattern about format or anything like that. On the other hand these songs were recognised in Auto Tag.

The library I'm trying to access is on my NAS.

I'm using Windows 11 OS build 22000.613

**Comment by Marekkon5** [comment]
Hello, for tracks to show up in QT they need title and artist tag.
Could you please also send the log, so I can see the issue? Thanks

**Comment by Wohme** [comment]
For 1 of the tracks, it was the case you mentioned (no artist + title was in metadata) and for the other, I see the following:
`2022-04-24 09:55:06 [ERROR] onetagger::quicktag: Error loading file: \\?\UNC\SNUFKIN\Data\Music\07.  m to the third power - brainwaves  (mike wertheim remix).mp3 NoTag: reader does not contain an id3 tag`

**Comment by Marekkon5** [comment]
Well the file doesnt have any tags at all. You can use edit tags to manually add title and artist tag, or autotagger with shazam or parse filename options.

**Comment by Wohme** [comment]
![image](https://user-images.githubusercontent.com/101064352/164966933-d44eee79-e008-453a-ae2e-7d3ce6bde647.png)

But it has, that's why I don't understand the error log above. Sorry, I wasn't that specific.

**Comment by Marekkon5** [comment]
Could you send the file please, so I can test myself? Thanks

**Comment by Wohme** [comment]
https://we.tl/t-H9AUrnx5t5

Here you go.

**Comment by Marekkon5** [comment]
Your track has ID3v1.1, which has been deprecated for quite a long time and not used anymore. The ID3 library we're using should read that, but it probably fails somewhere. However since ID3v1.1 has been deprecated since loooong time ago, I won't fix or report an issue for it. You should use tools such as mp3tag or others that can just convert it to ID3v2.3/2.4.

**Comment by bascurtiz** [comment]
@Wohme 
You can convert (and remove) all ID3v1 in one go, using [Mp3tag](https://www.mp3tag.de/en/download.html):
_To convert tags, go to the options, Tags > Mpeg and choose your desired tag version, then select all files you want to convert and use "Save Tag" (Ctrl+S)_
Simply drop all your tracks in there and make sure your settings are like below.


![id3v1 to id3v2](https://user-images.githubusercontent.com/34075088/164976841-7d9921b5-749d-483b-a87b-55c2072aa83a.gif)

**Comment by Wohme** [comment]
Fantastic, thank you guys for the help!

Then my suggestion would be that 1T would notify you if QT cannot scan all the files in that specific folder with a message like this for example:
"215 of 243 tracks were succesfully scanned"

So we know that we have to make amendments for some to be able to work.

Would that be possible?

**Comment by Marekkon5** [comment]
Added in latest commit, you can get the binary in the Actions tab to try it out. Feel free to comment or open another issue if you have any problems with it. Thanks
