### ISSUE TITLE
Feature request: "Add new value" will focus and highlight new input field

### ISSUE THREAD

**Issue by lord-carlos** [Marekkon5/onetagger#105]
Hi

When I press "Add new value" in for example "Vibe" it will create a new field with "new" in it.
It would be neat 📸 if the input field was focused / highlighted.

Now:
![image](https://user-images.githubusercontent.com/155855/166142051-30cf4f73-72cc-4470-b5ba-3f6e368b71eb.png)

Expected:
![image](https://user-images.githubusercontent.com/155855/166142063-73f5356f-1c1a-4637-975f-a35de74207e6.png)

Thank you for your time.
With kind regards.

**Comment by Marekkon5** [comment]
Added in latest commit, you can get the binary from the Actions tab to try it out. Feel free to comment or reopen if you have any more issues. Thanks
