### ISSUE TITLE
Feature request: %filename% variable for "Auto rename" 

### ISSUE THREAD

**Issue by lord-carlos** [Marekkon5/onetagger#106]
Hi

Sometimes I want to move file into an artist folder without renaming the files itself.
mp3tag supports this with  `%_filename%`

For example renaming / moving file with this pattern: `%artist%/%_filename%`
Would move the files into the artist folder without touching the files itself.

It's not super important, but nice to have.

**Comment by Marekkon5** [comment]
Hello, I've added `%filename%` in the latest commit. You can get the binary from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues. Thanks

**Comment by pritvorshik** [comment]
Hello. Thank you very much for your hard work. Please tell me how to add the "Mix Name" field to "EDIT TAGS" for AUTO RENAME. It displays the remixer and the original mix
