### ISSUE TITLE
Personal suggestions for the Quick Tag section

### ISSUE THREAD

**Issue by nico-ottati** [Marekkon5/onetagger#107]
1. When I import my already tagged tracks in iTunes, the ratings are missing. Even if I load the iTunes playlist as an m3u file, when I modify the rating and save changes, they won't update in iTunes.

2. In settings, in the "Quick Tag Custom" tab, you can re arrange customized tags within sections, but you cannot do the same when it comes to sections. Let's say I created a Section with 30 quick tags, and then I created like four more with other quick tags inside, but after I finished, I realized that in the tagging process, I want these sections to have a different order because of how I play... Well at least for now, I have no other way to do that rather than delete and create all the sections/tags all over again.

3. It would be amazing if in the wave viewer, I mean the media player, you could see the playback position/track's total duration as in other players. Oh, and I've sometimes noticed that the wave doesn't actually matches what's going on in during playback (let's say there haven't been a "drop" yet and the waveform is still wide instead of being thin).

4. Let's say you made a mistake. You used a quick tag in a lot of tracks, and then changed your mind about that tag. It would be really nice being able to make an "advanced search", where you can add filters such as Sections and the quick tags within those sections, so that way you can visualize the tracks that contain that tag and make it right easily. Same goes with Genre, Ratings, etc. That way we could try combinations for possible smart playlists as well. As an exampleI have in mind kind of how it was made in Beatport Pro.

5. It would be great to have different list visualization options, like in macOS Finder, or in any other media players. Personally I find the items on the list to be extremely big, and I think maybe other users too.

6. It would be great to have the ability to, while a track is being previewed, select another track without stopping the previous trac preview. For example, that way I can check wich tags I used in similar tracks. I know there's an option to do so in Settings (General section), but the it doesn't seem to be working on that way.

7. On the "Custom Notes" section in the right, it would be great that we could re arrange the quick tags within the sections as we can in Settings. We can now add tags, but we can't arrange them, so we still have to open the Settings to do so.

If I come up with another details I'll update the list. Thanks.

**Comment by Marekkon5** [comment]
Inactive / Fixed.
