### ISSUE TITLE
Dragging folder into folder field

### ISSUE THREAD

**Issue by ianfoxofficial** [Marekkon5/onetagger#11]
It would be nice to be able to drag folders into the app instead of navigating to it. This would speed up the workflow tremendously. Now it opens the folder in the view, making the app's UI disappear.

**Comment by Marekkon5** [comment]
This already has been requested, however it would require native implementation for each of the platforms (Linux, Windows, Mac), so don't really expect it in near future.

**Comment by onetagger** [comment]
@ianfoxofficial 
You can however - since I believe you are a mac user (ALAC requester =) - drag 'nd drop the folder into the path.
Like shown in the update overview of v1.1.0 here: 
https://youtu.be/wYqF6jV29QQ?t=18

**Comment by IanSkylegs** [comment]
Too bad. I forgot the drag & drop API ( https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop ) probably doesn't give access to the native file path...

**Comment by Marekkon5** [comment]
@IanSkylegs Nope, that gives only file data and we use it for playlists / album art in tag editor. Can't be used for getting entire paths.

**Comment by ianfoxofficial** [comment]
> @ianfoxofficial
> You can however - since I believe you are a mac user (ALAC requester =) - drag 'nd drop the folder into the path.
> Like shown in the update overview of v1.1.0 here:
> https://youtu.be/wYqF6jV29QQ?t=19

Hehe, no. I'm a Windows user but my whole music collection is in iTunes for Windows. (I used to have a Mac but completely switched back to PC)

**Comment by Marekkon5** [comment]
As I said, it would require native implementation, which is kinda painful. Will take look at it someday in future.

**Comment by lord-carlos** [comment]
In the meantime, could you disable that the folder gets opened in the view when drag and dropping?

**Comment by Marekkon5** [comment]
Actually I've tried implementing folder drag and drop on Windows, but the CEF window never receives `WM_DROPFILES` message (even with `PeekMessageW`), which I assume is because CEF intercepts it. So because of it am stuck on dead end and maybe someone notices this and knows what to do.

> In the meantime, could you disable that the folder gets opened in the view when drag and dropping?

I don't really think I can, it's a CEF thing.

**Comment by Marekkon5** [comment]
Latest commit replaces CEF with webview2 and I (with some shitty hack) added folder drag and drop support.
