### ISSUE TITLE
capi

### ISSUE THREAD

**Issue by jauntyd** [Marekkon5/onetagger#113]
Hello:
Trying to build on FreeBSD 13-STABLE. The UI builds good, but when I run: 
"cargo-cbuild cbuild --release"
I get the follow error:
Error: CliError { error: Some(none of the selected packages contains these features: capi, did you mean: tag?), exit_code: 101 }

I have searched the Master branch and the latest release source for anything mentioning capi as a requirement, but have been unsuccessful. When you have time, could you help me out?

Thanks.

**Comment by Marekkon5** [comment]
I have 0 experience with FreeBSD, but:

1. Could you share the whole error? Is this the only output?
2. The `cargo-cbuild cbuild` is an actual thing or a `cargo build` typo?
3. It seems that  `capi` is feature of some crate (that maybe isn't available on BSD). Maybe there will be more info if you run it with `-v`


Thanks

**Comment by jauntyd** [comment]
```
user@host:~/Downloads/onetagger-1.4.0 $ cargo-cbuild cbuild -v --release
    Updating crates.io index
    Updating git repository `https://github.com/Marekkon5/SongRec.git`
Error: CliError { error: Some(none of the selected packages contains these features: capi, did you mean: tag?), exit_code: 101 }
```

`cargo-cbuild cbuild` is the command from the cargo-c-0.9.8_2 package. I also installed cargo-generate-0.12.0_4. 

Here's a bit of an update...
I tried crates.io again and this time it returned the capi crate. Verified with PKG in FreeBSD:
```

user@host:~/Downloads/onetagger-1.4.0 $ cargo search capi
capi = "0.0.0"                   # Helper methods for building a C API in Rust: 
```


Sorry to have bothered you, hopefully this will help someone else.
