### ISSUE TITLE
[Suggestion] Preference for Date

### ISSUE THREAD

**Issue by ScrewedDriver** [Marekkon5/onetagger#115]
I'd like to suggest a preference for dates.
Actually OneTagger writes the exact release date to the tags.
I would prefer to have the option only to write the year.
Additionally people like different date formats like mm/dd/yyyy or dd/mm/yyyy.

**Comment by Marekkon5** [comment]
Added in the latest commit, you can get the binary from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues. Thanks
