### ISSUE TITLE
Total number of tracks

### ISSUE THREAD

**Issue by ScrewedDriver** [Marekkon5/onetagger#117]
I'd like to have the total number of tracks within the number tag in my files.
Actually one tagger only writes the number of the track but not the total number of tracks from the release.
MIght it be possible to include an option for the total number of tracks in a future release of onetagger?
Also I like to know if a release consists of more then one disk, which culd be archived through the Disc-Number Tag.

**Comment by Marekkon5** [comment]
Added track total in latest commit, it is not supported by all platforms and untested. You can get the binary from the actions tab to try it out. Thanks

**Comment by ScrewedDriver** [comment]
When I use my iPhone and the disc number is stored within the tags the order of a multiple disc release is correct. 
Same for music app on macOS.

**Comment by Marekkon5** [comment]
I meant which platform provides the disc number data? Discogs, iTunes, Beatport, Traxsource...? I can't seem to find it there

**Comment by ScrewedDriver** [comment]
Discogs provides this Information.
About other sources I’m not sure

**Comment by Marekkon5** [comment]
Added in latest commit, you can get the binary from Actions tab. Feel free to comment or open an issue if you have any more problems. Thanks
