### ISSUE TITLE
Compilations / Various Artists

### ISSUE THREAD

**Issue by ScrewedDriver** [Marekkon5/onetagger#118]
When tagging an release which contains tracks from different artists, onetagger appears to put all of the artists names in to the "Album Artist" tag.
Might it be possible to have an option to choose "Various artists" or something similar for the output to the "Album Artist" tag field in case there are multiple artist on the release?

**Comment by Marekkon5** [comment]
OneTagger writes what the platforms provide, the platforms usually don't differentiate between normal albums and VA albums, so there is no way for 1T to know this.
