### ISSUE TITLE
Path dragging

### ISSUE THREAD

**Issue by ScrewedDriver** [Marekkon5/onetagger#119]
When i drag a folder in the folder part of the onetagger window, and it is already populated from a previous action, the new folder path is added after the existing one which causes an error.
Might it be possible to change the behavior in a way that a dragged folder removes the existing information in this particular field of the window?

**Comment by Marekkon5** [comment]
This has been requested in issue #11 and also some Reddit threads - however drag and dropping folders isn't supported, as it requires custom implementation for each platform. I have no experience with Mac APIs and I don't own a Mac, so I am unable to implement it. Therefore on Mac you only have the default drag and drop behavior which exists in every app (dragging a folder into text field pastes the path there). Sorry for the inconvenience.
