### ISSUE TITLE
also save (beatport) track id / release id in id3 tags

### ISSUE THREAD

**Issue by benjaminlewandowski** [Marekkon5/onetagger#12]

**Comment by Marekkon5** [comment]
Which specific tag this should be written to?

**Comment by benjaminlewandowski** [comment]
Afaik Yate and the beatport script for mp3tag are saving it inside a custom field called "BEATPORT TRACK ID". Beatport Pro used UNIQUEFILEID as http://www.beatport.com|track-**ID**

(i use this tag to look up if a track is a beatport available track or not and if i synced all information)

**Comment by Marekkon5** [comment]
I am currently on vacation, will add the track id tag when I get back. However if you want the beatport URL, you can enable the "Other" tag option.

**Comment by benjaminlewandowski** [comment]
i think i can build a little a regex script for mp3tag that automatically moves the id from url inside WWWAUDIOFILE to "UNIQUEFILEID" and "BEATPORT TRACK ID"

**Comment by Marekkon5** [comment]
Added track ids in latest commit, URLs are now separate tag, Other will write `UNIQUEFILEID` tag. Reopen this issue if you have any problems with it, thanks.
