### ISSUE TITLE
Onetagger deleting Serato beatgrid/cue points?

### ISSUE THREAD

**Issue by DJScalf** [Marekkon5/onetagger#121]
After adding tags through OneTagger, a good amount of my tracks (~25%) have completely lost all cue point, beatgrid, and play count information in Serato. When loading tracks, some now load as if I have never used them before and they are being analyzed for the first time. 

Songs with 30+ plays will load in at 0 plays -- completely wiped of cues and grids.

In the case of one folder filled with halloween tracks that I tagged as "seasonal" and "niche", every single one has lost its cues and grids.

Is there any rhyme or reason to this or ways I can prevent? I love the product otherwise but I am afraid I am causing more harm than good with this now.

**Comment by DJScalf** [comment]
Update: I have found a pattern in which ones are affected and which are not:

I get my music from two main sources: BPM Supreme & TheMashup

TheMashup: **ALL** tracks from here are affected (luckily I have only used OneTagger on very few of these so far)

BPM Supreme: I know their older uploads were not as good with metadata and have gotten better through the years. For tracks from this record pool, it seems that tracks uploaded 2019 or later are unaffected, **everything else** is wiped of cue points and grids upon loading in Serato


Do you know what might be causing this? I am going to have to stop using OneTagger and begin doing this manually instead. For now, this will save me time of this cue/grid nightmare

**Comment by Marekkon5** [comment]
Could you share your log? It might have some useful info about what happened. You can access it using Settings > Open data folder and there is onetagger.log. Thanks

**Comment by Marekkon5** [comment]
Should be fixed in the latest commit. You can get binary from the `Actions` tab to test it out. Let me know if it works for you, feel free to comment or reopen if you have any more issues. Thanks

**Comment by DJScalf** [comment]
Here is my log. I will see if it has resolved my issues!
[onetagger.log](https://github.com/Marekkon5/onetagger/files/9014776/onetagger.log)

**Comment by DJScalf** [comment]
Also excuse my unfamiliarity with open-source terminology: Do I have to update anything to get the latest commit?

**Comment by DJScalf** [comment]
If the case is that it auto-updates: I am still having the same exact issue

**Comment by bascurtiz** [comment]
@DJScalf 
Do like this:

> You don't have to compile it from source. You just have to be logged into Github, then click the Actions tab on top:
> 
> ![image](https://user-images.githubusercontent.com/15169286/159360551-d58a0aa9-ce1d-4032-9eec-a06d1c2bbcca.png)
> 
> Then click on the latest commit:
> 
> ![image](https://user-images.githubusercontent.com/34075088/176557204-1f3f9fac-09af-4554-8bd9-4c966bd6e844.png)
> 
> There **scroll to bottom** and you can see the `Artifacts` section:
> 
> ![image](https://user-images.githubusercontent.com/15169286/159360636-56d6cacf-95a9-48e9-b8dd-4cfdc5016385.png)
> 
> If you use Windows - click `onetagger-win-setup` and it will download the Windows Setup version.

**Comment by DJScalf** [comment]
thanks @bascurtiz ! Very helpful

Good news and bad news:

Good news - Yay! My cue points and beatgrids are still in tact now! Thank you so much!
Bads news - play count is wiped upon loading still for the files in question.

Any way to fix that as well?

btw: thank you for all that you do for the DJ community

**Comment by bascurtiz** [comment]
@DJScalf 
You're welcome and thank you!
I've played around a bit and this is the outcome, see: https://serato.com/forum/discussion/1867961
Can you confirm?

**Comment by DJScalf** [comment]
yep @bascurtiz that sounds accurate. I wonder if Serato will have anything. 

However, this issue still only affects certain files (in my case, old BPM Supreme files and TheMashup files)

**Comment by bascurtiz** [comment]
Interesting...
Could you share such old and a new file (that does not seem to be affected), so I can inspect further?
You can attach them here as a zip.

**Comment by DJScalf** [comment]
Here you go
[onetagger test songs.zip](https://github.com/Marekkon5/onetagger/files/9042259/onetagger.test.songs.zip)

**Comment by DJScalf** [comment]
^ Jimmy Cooks should be unaffected, the other one should be affected

**Comment by DJScalf** [comment]
Thanks for all your hard work! Really insightful stuff.

However, I can't find the setting in OneTagger you're referring to:

![image](https://user-images.githubusercontent.com/108306155/177654033-0fb455e8-f7f0-4272-83f8-ee5fc4b6ede1.png)

**Comment by Marekkon5** [comment]
It's in the AutoTagger advanced sections. Not settings.

**Comment by DJScalf** [comment]
Ah I see. Thanks! I have really only been using quick tag but I did run a few folders through autotag to get album art, years, etc. 

If I understand correctly, will running files through autotag (with ID3v2.4 setting turned on) then using quick tag prevent the playcount issues?

**Comment by Marekkon5** [comment]
Hello, I've assumed you used AT, not QT. My bad.

Anyway in the latest commit I've added the ID3v2.4 option for QuickTag into settings. I've also switched to my fork of rust-id3, so Serato Playcount should be fixed now. You can get the binary from the Actions tab to try it out. Feel free to comment or reopen if you have any more issues.

**Comment by DJScalf** [comment]
Hey, new issue seems to have surfaced. I tried to manually fix a song's incorrect metadata, and I get this error. It seems I am unable to do anything in the "edit tags" mode without getting this error

![image](https://user-images.githubusercontent.com/108306155/178170652-d638e570-4c07-4cf7-bfca-b5f5b397bb75.png)

**Comment by Marekkon5** [comment]
We actually already found out and fixed that. Again you can get the latest binary from the Actions tab

**Comment by bascurtiz** [comment]
Correct. Grab the latest commit from the actions, where this has been fixed.
