### ISSUE TITLE
Total Track Number & issue in Album Artist field

### ISSUE THREAD

**Issue by SunKrocket** [Marekkon5/onetagger#127]
I noticed that another user requested to have total number of tracks along with the track number in the tag but that thread is closed. Is there a way you could add this ability for Traxsource?
Also, there seems to be extra spaces inserted when the album artist field is written. It seems to happen when there is a multiple entry separated by commas and ends looking like this:
Cassio Ware ,   Big Logan ,   Dave Lalla

Finally, I wanted to commend you for the interaction you have with your users. There is another mp3 tag software I primarily use but over the years the creator has never created a forum to listen to his users to make the program better. I now think OneTagger is equal and in some ways superior...being able to tag my vinyl rips much more efficiently is one example. So thanks for this program and your hard work!

**Comment by Marekkon5** [comment]
Hello, Traxsource supports track number and track total. Are you using the latest build from Actions tab (latest release 1.4.0 doesn't have this feature yet).

As for the extra spaces in albums - I am on vacation now, so it will take some time for me to fix it. Sorry for the inconvenience.

**Comment by Marekkon5** [comment]
Sorry for the delays, should be fixed in latest commit. You can get the binary from the Actions tab to test it out.
