### ISSUE TITLE
QuickTag + Autosave | Error when switching directory before saving

### ISSUE THREAD

**Issue by lord-carlos** [Marekkon5/onetagger#128]
Hello

I run a few weeks old dev version.
When changing / adding a tag, switching directory and clicking on a new track, OneTagger can't autosave and will throw an error.

Step to reproduce:
* Open a sub folder in QuickTag
* Change a tag or rating
* Let the song play
* switch to a parent directory 
* click on a new song
* Observe:
  * Error: quickTagSaved: Invalid Track

**Comment by Marekkon5** [comment]
Hello, could you please try the latest Actions build? There actually have been some changes related to this. 

If it doesn't work - I am on vacation, it will take some time to fix it, so you should temporarily use older, working version. Thank you

**Comment by Marekkon5** [comment]
Hello, fixed in the latest commit. Actually I've just hid the error, because the track gets saved successfully anyway. As always you can get the binary from the actions tab, feel free to comment or reopen if you have any more issues. Thanks

**Comment by lord-carlos** [comment]
Yes, it's fixed. Thank you <3
