### ISSUE TITLE
Auto tag won't find any matches when source is m3u playlist

### ISSUE THREAD

**Issue by 99Probl3ms** [Marekkon5/onetagger#129]
As the title says, I'm unable to match any tracks when I try to use a playlist as a source, even tracks that have been previously matched when the source was the folder that the tracks were in. 

Here are the errors I got on a single run:
![image](https://user-images.githubusercontent.com/14315709/181094532-740d1f8d-3afb-4871-bf79-f547b6825c74.png)

![image](https://user-images.githubusercontent.com/14315709/181094568-2d69ac1d-e1b8-4d41-b5ff-fab6b07b9898.png)

![image](https://user-images.githubusercontent.com/14315709/181094609-9bf192d8-0d5f-400b-9829-1c6316837097.png)

And here is the metadata for the track that says it's missing an artist tag:
![image](https://user-images.githubusercontent.com/14315709/181094830-6d18d351-f02b-4878-9868-fb16b8076bb6.png)

**Comment by Marekkon5** [comment]
Maybe the paths in the m3u file are relative and therefore pointing to invalid file. Could you please share the m3u file and onetagger log? Thank you

**Comment by bascurtiz** [comment]
@99Probl3ms 
In order to find the log file do like this:

https://youtu.be/RMxt0bom63k (windows)
or
https://youtu.be/z9HbNycEbGM (macOS)

**Comment by 99Probl3ms** [comment]
Here you go:
[onetaggerlog.txt](https://github.com/Marekkon5/onetagger/files/9193365/onetaggerlog.txt)
[Test.m3u.txt](https://github.com/Marekkon5/onetagger/files/9193373/Test.m3u.txt)

**Comment by Marekkon5** [comment]
The files inside the m3u playlist have relative paths (only filenames). Therefore 1T is looking for them in the directory it's opened in, and can't find them.

You either have to open onetagger inside the folder with the songs, or fix your m3u files to contain the full paths to the audio files.
