### ISSUE TITLE
Feature: Support For .OPUS and .OGG file formats

### ISSUE THREAD

**Issue by ijesaboy** [Marekkon5/onetagger#134]
Kudos on a great app and a growing community of onetaggers

It would be amazing if you added support for .[OPUS](https://opus-codec.org/) or [OGG](https://xiph.org/vorbis/faq/) file formats.

As it is, .opus and .ogg files are not visible to any onetagger functions. Thanks for your consideration.

**Comment by DJboutit** [comment]
I would love this to OGG is becoming more popular OGG should have been added a min of 1 year ago S M H

**Comment by Marekkon5** [comment]
I forgot to reply, however back then there weren't any good libraries for OGG in Rust, so we didn't consider adding it. Might check it out now.

**Comment by Marekkon5** [comment]
Added in latest commit. You can get the binary from the actions tab to test it out.
