### ISSUE TITLE
Auto Tag lowers case of previous genres when merge/appending, adds comma if no prior genre exists

### ISSUE THREAD

**Issue by josephjwilk** [Marekkon5/onetagger#135]
Hello! I just started using One Tagger as a way of automating adding genre information (it's the only tag I have been currently using), and I noticed some app behaviors that are making it hard to use in this way. Whenever I have the **Merge/append genre & styles** option checked, it will lower the case of all previous genres in the tag. So, the tag will start like this:

<img width="219" alt="Screen Shot 2022-08-19 at 10 43 21 AM" src="https://user-images.githubusercontent.com/7068951/185644616-13dcf8bf-8824-48ed-81bb-f98dff7b6480.png">

and then after auto-tagging will go to this:

<img width="219" alt="Screen Shot 2022-08-19 at 10 44 02 AM" src="https://user-images.githubusercontent.com/7068951/185659063-08b934d9-57b9-4802-b8c7-9ff453583ee3.png">

Additionally, if I have merge/append set but the track has no prior genre information, it will append to the empty tag with a comma, as seen here:

<img width="219" alt="Screen Shot 2022-08-19 at 11 54 40 AM" src="https://user-images.githubusercontent.com/7068951/185659303-f800a24f-3eed-4496-b1cc-e319fb14218e.png">

**Comment by Marekkon5** [comment]
This is a bug, I'll fix as soon as Vue3 port is done.

**Comment by Marekkon5** [comment]
Should be fixed in the latest commit, you can get the binary from the Actions tab to test it. Sorry for the delays.
