### ISSUE TITLE
Feature request: toggle to switch between fall back or progressive tagging when using Auto Tag

### ISSUE THREAD

**Issue by josephjwilk** [Marekkon5/onetagger#136]
Hello again! I previously mentioned that I am new to OneTagger, primarily concerned with automating adding genre information to my tracks. I'd love if there was a toggle that would allow the many tag source options to be progressive sources, instead of fall-back sources. By this, I mean that if I choose Beatport, Traxsource, Spotify, and Discogs, that it would automatically cycle through and add all genre and style information across the platforms instead of choosing the top one and only adding the rest if no information can be found.

Obviously, one can currently do this manually (and there would need to be some logic to disallow duplicates), but automating this process would be extremely helpful. Thanks for the time and consideration!

**Comment by Marekkon5** [comment]
Added in latest commit, you can get the binary from the Actions tab to test it out. Let me know if it works for you. Thanks
