### ISSUE TITLE
More than one mood value in quick tag

### ISSUE THREAD

**Issue by mtsbh** [Marekkon5/onetagger#137]
Hi, guys,

First of all thanks for the fantastic app. I like it and use it a lot. I have one small question - Is there any way for mood in Quick-Tag to be more than 1 value? I'm trying to configure it according to my please, but I would like to have more than one mood entry because it overrides the first one when I try to add a second one. I settled up moods to be written in the comments section but would be amazing if I could be able to write more than one.

Thanks again and big ups!

**Comment by Marekkon5** [comment]
Hello, we kinda decided for moods to be a single value field and designed 1T with it. So there is no option for that. However you can just use one of the custom tags on right, put all your moods there and pick and tag field you want. 

Feel free to comment or open if you have any more issues. Thanks
