### ISSUE TITLE
Feature: Move successfully tagged files to folder

### ISSUE THREAD

**Issue by 3nigm4** [Marekkon5/onetagger#138]
Hey, thanks so much for OneTagger, there is nowhere else to get good meta data for electronic music!

Please give me the option to move files that were successfully tagged to a different folder.

**Comment by Marekkon5** [comment]
Hello, we are currently rewriting the frontend to Vue3, so I will add this when it's done.

**Comment by Marekkon5** [comment]
Added in latest commit. You can get the binary from Actions to test it out.
