### ISSUE TITLE
audio features error

### ISSUE THREAD

**Issue by obelavic** [Marekkon5/onetagger#139]
Hey! Thanks for this amazing software. Sadly I couldn't make it work completely yet.

In Audio Features I do exactly as in the video shown, but I get an http error: status code 400 in the OneTagger Software. I could accept the authorization before in the webbrowser, but that's it.

Cheers : )

**Comment by bascurtiz** [comment]
Hi!
In the video it shows `http://localhost` something, but you should actually literally copy/paste, since in the newer versions it's:
`http://127.0.0.1:36914/spotify`

Let me know if that that's the case, thanks!

**Comment by obelavic** [comment]
Hey! I tried it with http://127.0.0.1:36914/spotify and get the error.

**Comment by Marekkon5** [comment]
Could you please send the full log? Thank you.

**Comment by obelavic** [comment]
It must have been my fault. I just reinstalled the software and it logs in now. Thanks for the help and the great software. <3
