### ISSUE TITLE
save beatport release id (same as track id - just for the release)

### ISSUE THREAD

**Issue by benjaminlewandowski** [Marekkon5/onetagger#14]

**Comment by Marekkon5** [comment]
Which tag should it be written to?

**Comment by benjaminlewandowski** [comment]
Currently, I am using a Custom field with the name "BEATPORT RELEASE ID" (mostly yate manual fixing via mp3tag)

**Comment by Marekkon5** [comment]
Added in latest commit for all platforms. Reopen if you have any issues with it, thank you.
