### ISSUE TITLE
issue passing path to onetagger-cli.exe

### ISSUE THREAD

**Issue by Hexactly** [Marekkon5/onetagger#140]
Hi
Truly excited about the possibility of running this amazing program in an automated script.
I'm running the following command successfully but 0 files are actually passed and tagged.
Running on windows 10 system using locally compiled latest code.

my command is:
onetagger-cli.exe autotagger --path "E:\PREPARE\process\test1\" --config "X:\onetagger_auto_script.json"

Result:
2022-09-06 10:37:25 [INFO] onetagger_autotag: Starting tagger with: 0 files!
2022-09-06 10:37:25 [INFO] onetagger_autotag: All tagged succesfully!

Also tried without passing the path in the command line and using the saved path in the json config file:
onetagger-cli.exe" autotagger --config "X:\onetagger_auto_script.json"

with setting.json:
"path": "E:\\PROCESS\\process",

This results in error: 
error: The following required arguments were not provided:
    --path <PATH>

I guess I'm getting something wrong passing the config file.

Any help would be great.

Thanks!

**Comment by Marekkon5** [comment]
Hello could you try using double \ (`E:\\PREPARE\\process\\test1`).

Also what is the format/extension of the files in that directory? Thanks

**Comment by Hexactly** [comment]
Hi
Tried your suggestion:
onetagger-cli.exe autotagger --path "E:\\PREPARE\\process" --config "X:\onetagger_auto_script.json"
onetagger-cli.exe autotagger --path "E:\\PREPARE\\process\\" --config "X:\onetagger_auto_script.json"

both result in:
2022-09-06 11:48:12 [ERROR] onetagger_shared: PANIC: panicked at 'Failed loading config file!: Error("invalid type: integer `2`, expected a boolean", line: 591, column: 0)', crates\onetagger-cli\src\main.rs:44:49
2022-09-06 11:48:12 [ERROR] onetagger_shared: LOCATION: File: crates\onetagger-cli\src\main.rs, Line: 44

the folder contains both flac and mp3 files.


thanks a lot

**Comment by Hexactly** [comment]
onetagger-cli.exe autotagger --path "E:\\PREPARE\\process\\\" --config "X:\onetagger_auto_script.json"

this version does run successfully but still no files detected.

**Comment by Marekkon5** [comment]
I'll manually test in on Windows bit later

**Comment by Hexactly** [comment]
Ok, so I realized I was working with the master branch.

Recompiled using vue3 branch and retried commands.

Unfortunately getting the same results exactly.

Here is my config file
[onetagger_auto_script.txt](https://github.com/Marekkon5/onetagger/files/9498084/onetagger_auto_script.txt)

Thanks again for looking into this.

**Comment by Marekkon5** [comment]
Hello, you've sent the full onetagger config, while the CLI version only accepts either autotagger config (for the autotagger part) or the audiofeatures config (for the audiofeatures part).


You can run `onetagger-cli --autotagger-config` which will only print the relevant default autotagger config, which you can save into your `X:\onetagger_auto_script.json` file and make the necessary changes there.

**Comment by Hexactly** [comment]
Aha! will try that.
Cheers

**Comment by Hexactly** [comment]
I tried using the correct config file. 
[autotagger_config.txt](https://github.com/Marekkon5/onetagger/files/9498395/autotagger_config.txt)

Getting the same result using this command:
onetagger-cli.exe" autotagger --path "e:\process\prepare\" --config "X:\autotagger_config.json"
Result - 0 files detected

Also not sure why the command doesn't accept without --path (using the path from the json).
onetagger-cli.exe" autotagger --config "X:\autotagger_config.json"

Seems the config file still not accepted.

**Comment by Marekkon5** [comment]
As for the `--path` argument - it is always used, overriding the one in the config (it is because you can set all the stuff using CLI arguments, rather than just config). 

Also the config you sent was invalid (missing quotes in `filenameTemplate` and missing a `}` at end). Is it just because of GitHub upload or locally also flawed?

However it's super weird that you get 0 files detected. Only thing that is different to my attempts is you using E: drive (maybe try some test folder on C: or wherever onetagger is stored). Or is that E: drive a USB disk perhaps, so I can test more? 

Are you running it inside Powershell or cmd or some other shell/terminal? 

Also since you're running from source - could you try the debug version (without `--release`) it has more info, and could you send the full output? 

Thanks

**Comment by Hexactly** [comment]
I fixed the errors in config file (my bad).
changed the command to run from c:\
'onetagger-cli.exe" autotagger --path "c:\tmp\test1\" --config "c:\tmp\onetagger_auto_script.json"

result:
2022-09-06 19:30:00 [INFO] onetagger_cli:

Starting OneTagger v1.5.0 Commit: unknown OS: windows


2022-09-06 19:30:00 [INFO] onetagger_autotag: Starting tagger with: 0 files!
2022-09-06 19:30:00 [INFO] onetagger_autotag: All tagged succesfully!
2022-09-06 19:30:00 [INFO] onetagger_autotag: Written failed songs to: C:\Users\MEJ\AppData\Roaming\OneTagger\OneTagger\config\runs\failed-1662481800096.m3u, successful to: C:\Users\MEJ\AppData\Roaming\OneTagger\OneTagger\config\runs\success-1662481800096.m3u
2022-09-06 19:30:00 [INFO] onetagger_cli: Tagging finished, took: 0 seconds

I'm running CMD in windows terminal Version: 1.14.2281.0

Could you direct me how to get the debug code?

**Comment by Marekkon5** [comment]
I'll test with Windows Terminal for sanity check, however:

1. Does normal onetagger work for you (using the UI)?

2. How did you obtain the executable? (Since you mentioned you locally compiled it - if that's the case you can run `cargo build` (without the `--release`) and the .exe will be in `target/debug/onetagger-cli.exe`).

Sorry for the inconvenience and thank you.

**Comment by Hexactly** [comment]
Normal onetagger works perfectly including the server mode

I will compile without the --release command as you suggest and get back to you.

Very happy to help and thank you for an amazing application!

**Comment by Hexactly** [comment]
Normal onetagger works perfectly including the server mode

I will compile without the --release command as you suggest and get back to you.

Very happy to help and thank you for an amazing application!

**Comment by Hexactly** [comment]
Finally managed to get it working!
Tested using vue3 debug & release.
I didn't check the master release again.
Seems it was a combination of using double / in the cmd + the correct config file.
`onetagger-cli.exe" autotagger --path "E:\\PREPARE\\process\\" --config "X:\autotagger_config.json"`
Thanks for your time & effort :)

**Comment by Marekkon5** [comment]
Thanks
