### ISSUE TITLE
OneTagger not picking up tracks in my folders

### ISSUE THREAD

**Issue by rangeahmed** [Marekkon5/onetagger#141]
I was facing an issue where my songs weren't showing up in the 'Edit Tags' section.

I chucked my folder through the 'Auto Tag' feature. About 50% of the songs were picked up; of these, about 90% of them were only picked up through the forced Shazaam feature.

Now when I head over to the 'Edit Tags' section, only the auto-detected songs are showing. 
The remaining 100 or so tracks don't show up.

Let me know if you require any more info.
System settings attached.

Thanks in advance!

<img width="295" alt="Screen Shot 2022-09-06 at 9 03 25 PM" src="https://user-images.githubusercontent.com/112937100/188594227-a318aeab-eb21-43d4-8813-107cae254065.png">

**Comment by rangeahmed** [comment]
Apologies, when I mention 'Edit Tags', I actually meant 'Quick Tag'. 
My songs aren't showing in the Quick Tag section.

**Comment by bascurtiz** [comment]
Do those non-tagged tracks have atleast Artist and Title tag filled in?
If not, those don't show in QT.

Also be aware, we support High Sierra and above.

**Comment by rangeahmed** [comment]
Ah okay that makes sense, no they don't have Artist & Title filled in.

Thanks for taking the time to answer.

OneTagger is amazing, love to see you guys supporting it.
