### ISSUE TITLE
Feature: Append custom tags from comment field

### ISSUE THREAD

**Issue by djrasmusp** [Marekkon5/onetagger#142]
Hey @Marekkon5,

First of great work with application - really great work.

It the moment Im trying to "convert" my workflow from the Beatport Pro desktop app to OneTagger. But im was wondering, if It would be possible to append custom tags from the comment field. 

<img width="1065" alt="Screenshot 2022-09-10 at 01 05 50" src="https://user-images.githubusercontent.com/896398/189457049-ee663124-2142-4511-bf33-9c9fa2a0df97.png">

As shown on the image above, when I import the file to OneTagger, the comment field contains the following "10A, My Edit, Dansk" and i have the tags "My Edit" and "Dansk" in my custom tags, but they are not checked/append. 

Would it be possible to append the tags from the comments field, if the tag exists in the custom tags ?

**Comment by Marekkon5** [comment]
Hello, are the custom tags Language and Extras set to the same field (comment field) as the original tags?

**Comment by djrasmusp** [comment]
@Marekkon5 - that worked, but i found some other GUI bug, where the the text and background are both white, as you can see in the image
<img width="587" alt="Screenshot 2022-09-11 at 20 15 28" src="https://user-images.githubusercontent.com/896398/189542879-d3f700f0-89f8-4e8e-aa8b-27d197eca95a.png">

**Comment by bascurtiz** [comment]
@djrasmusp 
What OS are you running?
I've tried Win10 + macOS Monterey, but they look proper.

**Comment by bascurtiz** [comment]
@Marekkon5 
I can replicate on macOS Catalina.
Still would be handy to know what OS version u run @djrasmusp .

**Comment by djrasmusp** [comment]
@bascurtiz im runing Mojave (10.14.6)

**Comment by Marekkon5** [comment]
Hello, all the UI issues should be fixed in the latest vue3 commit.

**Comment by Marekkon5** [comment]
It is now on master as well.
