### ISSUE TITLE
Feature: Regex based auto-tagger

### ISSUE THREAD

**Issue by wodinga** [Marekkon5/onetagger#143]
Some of my music's metadata has been tagged incorrectly. Software like Mixed in Key make it easy to change the titles of your tracks to include extra tags like key and BPM, but impossible to reverse if you would instead prefer to rely on metadata fields instead.

The below image is an example
<img width="493" alt="image" src="https://user-images.githubusercontent.com/3639900/190556859-ba6ac239-064e-425a-8fb3-72f32297102e.png">

I'd love to be able to automatically handle some of this renaming with regex!

Ideally, the flow could work similarly to the existing auto-tagger, with visual feedback on what your regex is matching as you type, and a review screen before applying the operation. Undo functionality would be really helpful here as well.

**Comment by Marekkon5** [comment]
Hello, you can use Autotagger to fetch the key/bpm data, and then the Renamer tab to put the metadata into your filenames.
