### ISSUE TITLE
new option to failed match

### ISSUE THREAD

**Issue by luamzx** [Marekkon5/onetagger#146]
Congratulations for the APP has helped me a lot!

after auto tag you could have the option to open the failed match tracks in explorer/finder already selected 
so that we can move files or delete them. like matched tracks

*translated text*

**Comment by Marekkon5** [comment]
I do believe you can't open explorer with tracks already selected. I can add moving failed files or you can use the playlists with failed tracks generated by OneTagger.

**Comment by luamzx** [comment]
got it thks

**Comment by Marekkon5** [comment]
Added in latest commit, you can get the binary to test it out from the Actions tab. Feel free to comment / open new issue if you have any more problems. Thanks
