### ISSUE TITLE
compare time before importing tag

### ISSUE THREAD

**Issue by benjaminlewandowski** [Marekkon5/onetagger#15]
Maybe with selection how much difference is okay - yate has a selection between 1 and 10 seconds

**Comment by Marekkon5** [comment]
I've tried implementing it in past in other taggers, however it drastically decreased the match rate. Do you have any example songs where it would help in 1T?

**Comment by benjaminlewandowski** [comment]
I have some tracks in the short version - sometimes 1t assigns the tags of the longer version (as only those are available on Beatport)

**Comment by Marekkon5** [comment]
Makes sense, will consider it.

**Comment by Marekkon5** [comment]
Added in latest commit, reopen if you have any issues with it. Thank you.
