### ISSUE TITLE
"Tag same track on multiple platforms" option scanning but not tagging

### ISSUE THREAD

**Issue by josephjwilk** [Marekkon5/onetagger#150]
Hello, thank you so much for adding this feature per my request in #136! I just wanted to give you a heads-up that I was able to test it, and I noticed that while it will scan and match tracks across all selected platforms, it won't actually add the additional genre tags from any platforms beyond the first. I currently have the "Overwrite tags" and "Merge/append genre & styles" options checked, which both work as expected when choosing only one tag source. I can confirm because if I keep the same number of tag sources checked but change their order, it will append the top-most source (which I double-checked by running only that source on a second copy of the tracks).

**Comment by Marekkon5** [comment]
Hello, should be fixed in the latest commit, you can get the binary from the Actions tab, let me know if it works for you. Thanks

**Comment by josephjwilk** [comment]
This appears to be working as expected now! Thank you for the continued development.
