### ISSUE TITLE
AutoTag broken with Traxsource "Error matching track: Missing artist tag!"

### ISSUE THREAD

**Issue by variablenix** [Marekkon5/onetagger#152]
Super happy One Tagger exists after seeing a Reddit post mention it, so I converted all my Traxsource WAV files to AIFF as there is no WAV support. Unfortunately, the AutoTag feature always fails to tag. I have tried using both Traxsource and Beatport and a few other platforms to no avail. I am running the latest 1.5.0 Windows setup release. Tags have failed with the same error in both the app itself and local web app listening on localhost. The two messages in the log file that stand out...

> creating new tag. InvalidInput: invalid chunk header
> [ERROR] onetagger_tagger: Track is missing artist tag

I think the main problem is that One Tagger is somehow "missing artist tag" but I do not understand why. It doesn't matter which tags are selected because the error always comes up. There is nothing wrong that I can see or tell with the AIFF files I am trying to tag as they play fine with iTunes/Music, VLC, Serato.

![onetagger - missing artist tag why how](https://user-images.githubusercontent.com/472631/196329238-c055487d-210a-4f73-b5c5-0be11284a48e.PNG)

I saw there was a closed AutoTag issue but the underlying OS was macOS and not Windows. I am not sure how to proceed. I don't want to manually tag close to 400 audio files obtained from Traxsource.

**Comment by Marekkon5** [comment]
OneTagger requires an artist and title tag inside the files you're trying to tag (to search for the song on the platforms). If you don't have title/artist tags in your songs, you can either enable Shazam matching in advanced settings, or use the parse filename feature.

**Comment by variablenix** [comment]
For some reason VLC was losing my saved ID3 tag (artist, title) when I would re-open a AIFF file. I installed Mp3tag to manually add the artist to a couple tracks to test. I can confirm having the artist in the file allows AutoTag to work. Many years ago, I remember Traxsource would properly tag basic tags like title/artist. Today the entire track info details are in the title only.

Thanks so much, OneTagger absolutely rocks!

**Comment by variablenix** [comment]
Not sure why my results are so inconsistent, but after spending a good amount of time adding the artist to each track, 1T continued to fail tagging. I get both "no match" and "Error matching track: No results!". So even with the artist added to 4x AIFF tracks I am testing with, 1T can't find the tracks at all. I'm not sure if I am hitting some API limit or what. I will post back if I get any progress in the next day or so.

**Comment by Marekkon5** [comment]
What platforms do you have selected? What is the exact artist/title (maybe it doesn't exist on the given platform or has some different version)?

**Comment by variablenix** [comment]
These are strictly tracks downloaded from Traxsource, so I have been primarily only using the Traxsource platform. I pulled out 4 tracks without their ID3 tags corrected into a folder. These are all vanilla tracks as in no tag modifications -- they are as is directly from Traxsource. The odd thing is I simply add the artist only (no version anywhere), and 1T says "No match". If I search the full title the way Traxsource ships their tracks, they are found. I don't know how else to make 1T find these songs.

**Comment by variablenix** [comment]
Now I'm very confused. So I _think_ this works regarding Traxsource.

1. manually edit the ID3 tags of the original downloaded Traxsource AIFF files
- only leave song title in the "title" section, so needing to manually edit each downloaded Traxsource song
- remove the version number that is added to the END of each title

2. manually add (copy/paste) the artist originally in the title into the artist section

Retried 1T on 4x tracks and I got green checkmarks. I almost think Traxsource should fix the way their purchased tracks are tagged. I don't know why all the track information is dumped in the "title" section.

I'm going to try more tracks and see if I stumble upon any more errors.

**Comment by variablenix** [comment]
There is at least one track purchased from Traxsource that will absolutely not match. If I search the existing default tags on Traxsource.com, it is found. 1T is unable to identify the track regardless of the above that made other tracks get properly tagged. There are two versions of the same track/remix on Traxsource -- both with a different genre but are the same song. I'm not sure why 1T just cannot find certain tracks, but the track it is unable to match is definitely on Traxsource.

**Comment by Marekkon5** [comment]
Could you please send the exact track title & artist so we can test and see what's wrong? Thank you.

**Comment by variablenix** [comment]
Track source https://www.traxsource.com/track/9667203/get-down-and-dirty-samuele-sartini-jonk-and-spook-remix

The title is the only tag with any data as, `Blakej, Samuele Sartini, Jonk - Spook - Get Down And Dirty (Samuele Sartini, Jonk - Spook Remix) 1`.
<img width="713" alt="Screen Shot 2022-10-19 at 4 09 48 PM" src="https://user-images.githubusercontent.com/472631/196827377-6e1e5339-f5d6-4e49-8257-5526e8651966.png">

The good news is that so far other tracks have been getting tagged correctly after making the edits I noted.

**Comment by variablenix** [comment]
Another one that cannot be found by 1T. For the 1-offs I am just manually applying the tags.

https://www.traxsource.com/track/7210857/i-left-carlo-remix

**Comment by Marekkon5** [comment]
1T AutoTagger expects the artist and title tags to be proper/clean to properly find and match the tracks.

The artist tag should be: `Blakej, Samuele Sartini, Jonk`
The title tag should be: `Get Down And Dirty (Samuele Sartini, Jonk - Spook Remix)`

So you have to manually correct the tags.

If you don't wanna manually correct them, you can use the Parse Filename feature (if your filename looks like the current title tag) or the Shazam feature which will try to determine the artist/title using audio data using Shazam.

Thank you

**Comment by variablenix** [comment]
Understood. What I do not understand is why a couple tracks were being picky even though they were manually ID'd like 300+ other tracks (clean artist + title). In any case, 1T tagged the large majority of them and for that I am very grateful for OneTagger. 

Thank you very much for the assist.
