### ISSUE TITLE
Music Deleted

### ISSUE THREAD

**Issue by melbourne-j9494** [Marekkon5/onetagger#153]
Hi,

I've just had 1362 tracks deleted that I was trying to tag. Basically if you have "Move files failed to get tagged" as the folder you are looking to tag, the input, folder then the files that don't get tagged get deleted...

If you have any idea how to recover those 1362 tracks, I would really appreciate it.

**Comment by Marekkon5** [comment]
Hello, I am terribly sorry for this, didn't consider this edge case (target should never be same as source). Since 1T doesn't move files to trash but deletes them, you have to try tools like Recuuva or some other file recovery tool. I'll fix this asap

**Comment by melbourne-j9494** [comment]
Yeah... you've really created a nightmare for me, not going to lie...

**Comment by Marekkon5** [comment]
Sorry again, I've pushed a fix, which you can get from the Actions tab, I'll also release 1.5.1 hotfix asap.

**Comment by Marekkon5** [comment]
Sorry again for this, it should all be fixed in the latest 1.5.1 release.
