### ISSUE TITLE
Auto Tag with .m3u file not working

### ISSUE THREAD

**Issue by djrasmusp** [Marekkon5/onetagger#154]
Hey,

I'm having troubles with using the "Auto Tag"-function with .m3u-files.
When using it doesn't tag any files and just give me the choice to open tagged files folder.

The way im using it, is exporting a playlist from iTunes, then I drag & drop the file, and click on the play button.

My system is:
MacOSX 12.6
OneTagger 1.5.0

**Comment by Marekkon5** [comment]
Could you share the playlist and the log file? Thank you

**Comment by djrasmusp** [comment]
The problem with the no tag files, was because the path to the folder was to the .m3u file.. 
But when i remove it, I dont get the chance to click on the "Tag"-Button.

I have made a video and shared my .m3u of the problem

https://user-images.githubusercontent.com/896398/198846957-b5e311dd-5b1c-4da0-9c4e-3a3b4065869e.mov
[Re-fix.m3u.zip](https://github.com/Marekkon5/onetagger/files/9894323/Re-fix.m3u.zip)

**Comment by djrasmusp** [comment]
Its says that im using the 1.5.0 release
<img width="1392" alt="Screenshot 2022-10-31 at 21 05 32" src="https://user-images.githubusercontent.com/896398/199100521-1d38d402-12f4-4c30-ac56-82a9615d6a10.png">

I have attached the log file her
[onetagger.log](https://github.com/Marekkon5/onetagger/files/9904715/onetagger.log)

**Comment by djrasmusp** [comment]
I have just updated to 1.5.1 and it works now :)
