### ISSUE TITLE
FLAC support missing ?

### ISSUE THREAD

**Issue by grogcw** [Marekkon5/onetagger#155]
Hi !

I'm attempting to use OneTagger on a collection of FLAC files.

I tested both MacOS and Linux (FreeBSD) and the result is the same on both systems : `Error loading file: FLAC ID3 not supported!`

What am I doing wrong ?

Thanks for taking care,

Cheers !

**Comment by onetagger** [comment]
![image](https://user-images.githubusercontent.com/83558131/199318567-33ce9ad3-8a51-453a-9fef-7c86acf631fd.png)

As stated above, you shouldn't use ID3 tags with FLAC and use Vorbis insteead.
Which program are you using to edit metadata?

**Comment by grogcw** [comment]
Hi !

I use Meta (on MacOS) and kID3 (on freebsd) and both show that the tags where in vorbis, they're now stripped.

The problem remains tho.

I don't really understand as I - for sure - have tagged FLAC files before.

Maybe something's wrong with that batch...

**Comment by Marekkon5** [comment]
Hello, your files probably still have the ID3 header. Could you send some as an example? Also you can remove the ID3 header in Kid3 and only keep the Vorbis one. Thank you.

**Comment by grogcw** [comment]
You're actually right, I decoded them to WAV then to FLAC again, it fully stripped all the headers and the batch was processed right away !

Thanks for the heads-up !

Cheers !
