### ISSUE TITLE
Unable to rename a file

### ISSUE THREAD

**Issue by Surfoo** [Marekkon5/onetagger#157]
Hello,

I'm trying to rename some tracks in a folder (I'd like to add a dash between the tracknumber and the title), but I got this error:

> onetagger_renamer: Failed copying xxxxx/02 Tout simplement.mp3 -> "xxxxx/2\0 - Tout simplement.mp3": data provided contains a nul byte

How can I help you to solve this issue? Thanks.

**Comment by Marekkon5** [comment]
Hello, what is your filename template? Maybe the tags you're using contain a null byte.

**Comment by Surfoo** [comment]
the template is `%track% - %title%`

**Comment by Marekkon5** [comment]
I've pushed a fix, you can get the binary from the Actions tab to try it out (should be ready in 20 minutes). Feel free to comment/reopen if you have any more issues. Thanks

**Comment by Surfoo** [comment]
Thank you, it works, but the first `0` has been skipped in the filename.

**Comment by Marekkon5** [comment]
Maybe you want to pad the track number:

```
%track.pad("0", 1)% - %title%
```

It will convert `2` into `02`, `10` into `10` and so on...
