### ISSUE TITLE
Wav files not loaded

### ISSUE THREAD

**Issue by prisse89** [Marekkon5/onetagger#158]
Hello and congrats a lot for this software.
I just install it and so far enjoy its features, but unfortunately, it seems that the .wav files can't be loaded.
Am I doing something wrong or the feature is missing? If it's missing, can it be added in a later update? 

Thanks and keep up the good work.
Best regards,
Stefan

**Comment by Marekkon5** [comment]
WAV files by definition do not have tags. There is no standard for them for tags. So 1T doesn't support WAV files.

**Comment by prisse89** [comment]
Thanks for your swift feedback.
Just found this on the web.
perhaps it helps digging more into the subject,
![image](https://user-images.githubusercontent.com/118156165/201783447-b155b9ba-f120-4107-a654-1e7cde6ba775.png)

**Comment by Marekkon5** [comment]
In the latest commit I've added WAV support (not fully tested yet), and it will only edit the ID3v2 portion of the RIFF metadata. You can get the binary from the Actions tab to test it out. Thank you

**Comment by Marekkon5** [comment]
Latest commit adds support for reading from RIFF info as well.

**Comment by prisse89** [comment]
Tested and it seems to be working, at least for some files of my files.
However, I've got some files failing even though they can be found on Beatport for instance.

**Comment by Marekkon5** [comment]
Can you send the files here so we can test? Thank you

**Comment by prisse89** [comment]
Please see the download link below with some failed files existing no Beatport or Discogs. 
It was too large to attach the files directly here.
https://we.tl/t-hKmSBpY5Zy

References for the files:
https://www.beatport.com/track/ozup/4171829
https://www.beatport.com/track/benediction/5711678
https://www.discogs.com/release/18688234-Barut-Cuantiz-EP

**Comment by Marekkon5** [comment]
Hello, those files don't have title and artist tags. 1T needs title and artist tags to search for the the track on the platforms and to correctly match them. You can either add those tags manually (in Edit tags, or software like Kid3), or enable the Shazam option, or enable the filename parsing option.

**Comment by prisse89** [comment]
Thanks for your reply and continuous support.

I had the Shazam option switched on, also the parsing option, but it doesn't seem to be making a difference.

Can it be because some of the files have also the track album number or other characters in front of the %artist% in the filename and the sequance is not %artist% - %title% like in the "filename scheme" of the parsing option?  

Please see some examples below and their links from Beatport / Discogs: 

14291819_Meuse_Original_Mix - https://www.beatport.com/track/meuse/14291819
131 - 5A - Mathijs Smit - Bad Birdy - https://www.beatport.com/track/bad-birdy/16901311
A1 Jamahr - Panorama VINYL ONLY  [Dighop Records] - https://www.discogs.com/release/13147208-Jamahr-Ray-Mono-Lowwaxx-DHR003
[UVARBLK002] B1 Vid - Machine MST - https://www.discogs.com/release/18370063-Vid-Machine-EP
01. DJOKO - Red Drank - https://www.discogs.com/release/18061981-DJOKO-3-DJ-Wer-Suffe-Kann-Kann-Och-Arbigge-EP

Could you please advise if there is a format in the "Filename Scheme" which might suit all the different filenames mentioned above?

Also, please see below the settings I've used for the Auto Tag. 
![image](https://user-images.githubusercontent.com/118156165/202526408-a7bb6fba-1277-4255-92c7-68fc089a6008.png)

PS: My library is very messy and I am trying to use software to clean it. 
Once I will get the whole tags, including the artist and title, I could also use the "auto rename" function from 1T to rename everything :). 

Best regards,
Stefan

**Comment by Marekkon5** [comment]
As for the filename matching - you can't do it in your case. It is intended for libraries where every track is in the same format (such as %track%. %artist% - %title%), however every track in your library is different, so you can't make use of it (unless you manually rename first).

As for Shazam - I found a bug which prevented matching some of the tracks. I've fixed it in the latest commit. Now all the songs you've sent before can be matched using Shazam:

![image](https://user-images.githubusercontent.com/15169286/202539557-fdf0c368-5928-49a4-b5ae-7cafcd373387.png)

**Comment by Marekkon5** [comment]
I've fixed the playlist paths in the latest commit.

**Comment by prisse89** [comment]
Thanks you very much and congrats for the app. It's super cool.
