### ISSUE TITLE
Nested folder support for quick tagging

### ISSUE THREAD

**Issue by gabrielsoule** [Marekkon5/onetagger#16]
My music library isn't flat; the top layer is a list of artist folders, and in each of those folders, there are album folders, and in those folders live all my songs. 

Quick tagging doesn't seem to support non-flat folder structures, which renders the functionality somewhat moot, since I have hundreds of artist folders, and hundreds of albums, and having to select each album folder for each artist manually makes it, well, not at all quick.

Is there a way to have onetagger search nested folder structures when using the quick tag feature?

**Comment by Marekkon5** [comment]
Already implemented for 1.2.0. Wait for release or use latest version from master (you can get binary from the "Actions" tab)
