### ISSUE TITLE
How do I install this on Linux (CLI)

### ISSUE THREAD

**Issue by CrazyWolf13** [Marekkon5/onetagger#160]
Hey there i hope anyone can help, i searched everywhere but couldn't find any guide on how to install the cli version.

Thanks for any help.

**Comment by Marekkon5** [comment]
Hello, both the CLI and GUI versions on Linux are just binaries. You can download the latest release from Releases or Actions (for bleeding edge) tab, extract it and start it.

```
tar zxvf OneTagger-linux-cli.tar.gz
./onetagger-cli
```

**Comment by CrazyWolf13** [comment]
Hey, thank you very much for the help.
The first command i knew but then i was stuck with this one file.

But sadly the command results in an error.

./onetagger-cli 
bash: Can't execute the binary file. Error in the file format.

Raspian(RaspberryPi 3b+)

**Comment by CrazyWolf13** [comment]
> ./onetagger-cli

![image](https://user-images.githubusercontent.com/96661824/204339446-8e3ce8c8-89a3-4eff-a162-92907f4dbde1.png)

**Comment by Marekkon5** [comment]
The precompiled binaries are for x86_64, Raspberry Pi is ARM. You have to compile from source in this case (maybe cross compiling might be more viable, since it would take an hour on single core RPi).

**Comment by CrazyWolf13** [comment]
> The precompiled binaries are for x86_64, Raspberry Pi is ARM. You have to compile from source in this case (maybe cross compiling might be more viable, since it would take an hour on single core RPi).

Thanks for the help.
Oh that makes sense.
If have got a windows pc any way to do compile it there and then load it to my Pi?
I'm quite new to this compiling.

**Comment by Marekkon5** [comment]
You could try this guide: https://stackoverflow.com/questions/39705213/cross-compiling-rust-from-windows-to-arm-linux

Or wait until I figure it out.

**Comment by CrazyWolf13** [comment]
> You could try this guide: https://stackoverflow.com/questions/39705213/cross-compiling-rust-from-windows-to-arm-linux
> 
> Or wait until I figure it out.

Hey,
Thanks for the link.
For me its a bit difficult, because all that rust, and compiling is new to me.
I would really appreciate if you could help me.
No problem, take the time needed, I have got a temporary fix to use get_album_cover which works, but not with all audio files, cause the ones the lack media tags won't get recognized. So I hope I can do this with your tool, it looks awesome.

**Comment by Marekkon5** [comment]
What model is your Raspberry Pi? Are you running armhf or aarch64 (run `uname -a`)?

**Comment by CrazyWolf13** [comment]
> What model is your Raspberry Pi? Are you running armhf or aarch64 (run `uname -a`)?

Hey, sorry for the delay didn't get any notification, so I missed it.
I have a Raspberry Pi 3 B+
The Command gives me an error lol
But thanks for looking into this for me :)

**Comment by Marekkon5** [comment]
Hello, I've cross compiled the latest CLI version from my machine to aarch64. Let me know if it works for you.

[onetagger-cli-aarch64.zip](https://github.com/Marekkon5/onetagger/files/10179081/onetagger-cli-aarch64.zip)

**Comment by CrazyWolf13** [comment]
Hey thank you very much.
![image](https://user-images.githubusercontent.com/96661824/206270581-74ccb05b-c4c2-4710-8d5b-76debd48b014.png)
But sadly this message appears.

**Comment by Marekkon5** [comment]
I probably compiled with too new glibc, I will recompile it on Ubuntu system

**Comment by Marekkon5** [comment]
Here's a version compiled on Ubuntu 22.04 Docker container. If it doesn't work I can try Ubuntu 20.04. The glibc version seems to be 2.35

[onetagger-cli-aarch64-ubuntu.zip](https://github.com/Marekkon5/onetagger/files/10179407/onetagger-cli-aarch64-ubuntu.zip)


Compile instructions in case someone tries to replicate (intended for docker/clean machines, don't run on host):
```
#!/bin/bash
set -e

# Rust must be already installed
# EDIT IF DIFFERENT, WORKS FOR UBUNTU 22.04
export SYSROOT=/usr/aarch64-linux-gnu

# Install packages
apt install -y crossbuild-essential-arm64 wget make git curl pkg-config
curl https://sh.rustup.rs -sSf | sh -s -- -y
source "$HOME/.cargo/env"
rustup target add aarch64-unknown-linux-gnu

# Download alsa and libsndfile
cd /tmp
mkdir packages
cd packages
wget https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.8.tar.bz2
wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
tar xf alsa-lib-1.2.8.tar.bz2
tar zxf libsndfile-1.0.28.tar.gz

# Compile ALSA
cd alsa-lib-1.2.8
./configure --enable-shared=yes --enable-static=no --with-pic --host=aarch64-linux-gnu --prefix=/usr/aarch64-linux-gnu
make -j`nproc`
make install
cd ..

# Compile libsndfile
cd libsndfile-1.0.28
./configure --enable-shared=yes --enable-static=no --host=aarch64-linux-gnu --prefix=/usr/aarch64-linux-gnu
make -j`nproc`
make install
cd ..

# Clean
cd /tmp
rm -rf /tmp/packages

# Compile
git clone https://github.com/Marekkon5/onetagger.git
cd onetagger
export PKG_CONFIG_SYSROOT_DIR="$SYSROOT"
export PKG_CONFIG_PATH="$SYSROOT/lib/pkgconfig"
cargo build --release --target aarch64-unknown-linux-gnu --bin onetagger-cli
aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/onetagger-cli
```

**Comment by M0Rf30** [comment]
Hi @Marekkon5,
I'm providing a package definition in Arch Linux User Repository
Check it out here
https://aur.archlinux.org/packages/onetagger

Thanks for this cool project

**Comment by Marekkon5** [comment]
@M0Rf30 Looks good! Thank you

**Comment by M0Rf30** [comment]
So to stay on-topic: on Arch you can install it with the following instruction:
```
yay -S onetagger
```

**Comment by CrazyWolf13** [comment]
> Here's a version compiled on Ubuntu 22.04 Docker container. If it doesn't work I can try Ubuntu 20.04. The glibc version seems to be 2.35
> 
> [onetagger-cli-aarch64-ubuntu.zip](https://github.com/Marekkon5/onetagger/files/10179407/onetagger-cli-aarch64-ubuntu.zip)
> 
> Compile instructions in case someone tries to replicate (intended for docker/clean machines, don't run on host):
> 
> ```
> #!/bin/bash
> set -e
> 
> # Rust must be already installed
> # EDIT IF DIFFERENT, WORKS FOR UBUNTU 22.04
> export SYSROOT=/usr/aarch64-linux-gnu
> 
> # Install packages
> apt install -y crossbuild-essential-arm64 wget make git curl pkg-config
> curl https://sh.rustup.rs -sSf | sh -s -- -y
> source "$HOME/.cargo/env"
> rustup target add aarch64-unknown-linux-gnu
> 
> # Download alsa and libsndfile
> cd /tmp
> mkdir packages
> cd packages
> wget https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.8.tar.bz2
> wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz
> tar xf alsa-lib-1.2.8.tar.bz2
> tar zxf libsndfile-1.0.28.tar.gz
> 
> # Compile ALSA
> cd alsa-lib-1.2.8
> ./configure --enable-shared=yes --enable-static=no --with-pic --host=aarch64-linux-gnu --prefix=/usr/aarch64-linux-gnu
> make -j`nproc`
> make install
> cd ..
> 
> # Compile libsndfile
> cd libsndfile-1.0.28
> ./configure --enable-shared=yes --enable-static=no --host=aarch64-linux-gnu --prefix=/usr/aarch64-linux-gnu
> make -j`nproc`
> make install
> cd ..
> 
> # Clean
> cd /tmp
> rm -rf /tmp/packages
> 
> # Compile
> git clone https://github.com/Marekkon5/onetagger.git
> cd onetagger
> export PKG_CONFIG_SYSROOT_DIR="$SYSROOT"
> export PKG_CONFIG_PATH="$SYSROOT/lib/pkgconfig"
> cargo build --release --target aarch64-unknown-linux-gnu --bin onetagger-cli
> aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/onetagger-cli
> ```

Good evening
Huge thanks for doing this for me.
Sadly i didn't had any time recently so i tried it some minutes ago. But sadly my commands are wrong or there are still some errors. 
![image](https://user-images.githubusercontent.com/96661824/210630741-a4c7b076-2c0b-46c7-ac4f-c3a73c299e0f.png)

**Comment by Marekkon5** [comment]
@CrazyWolf13 

Since it doesn't work, you can try compiling directly on the Raspberry Pi.

Dependencies:
```
sudo apt install -y autogen libsndfile1-dev libasound2-dev pkg-config make libssl-dev gcc g++ curl wget git libwebkit2gtk-4.0-dev
```

Node JS:
(https://github.com/nodesource/distributions/blob/master/README.md)
```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```

Rust:
(rustup.rs)
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

Compile:

```
git clone https://github.com/Marekkon5/onetagger.git
cd onetagger

cd client
npm i
npm run build
cd ..

cargo build --release --bin onetagger-cli
```

The binary should be at `target/release/onetagger-cli`

Thank you.

**Comment by CrazyWolf13** [comment]
> @CrazyWolf13 
> 
> Since it doesn't work, you can try compiling directly on the Raspberry Pi.
> 
> Dependencies:
> ```
> sudo apt install -y autogen libsndfile1-dev libasound2-dev pkg-config make libssl-dev gcc g++ curl wget git libwebkit2gtk-4.0-dev
> ```
> 
> Node JS:
> (https://github.com/nodesource/distributions/blob/master/README.md)
> ```
> curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&\
> sudo apt-get install -y nodejs
> ```
> 
> Rust:
> (rustup.rs)
> ```
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> ```
> 
> Compile:
> 
> ```
> git clone https://github.com/Marekkon5/onetagger.git
> cd onetagger
> 
> cd client
> npm i
> npm run build
> cd ..
> 
> cargo build --release --bin onetagger-cli
> ```
> 
> The binary should be at `target/release/onetagger-cli`
> 
> Thank you.
> 

Thank you for this detailed guide.
