### ISSUE TITLE
Remove tags button

### ISSUE THREAD

**Issue by prisse89** [Marekkon5/onetagger#161]
Hello again,

After multiple tests with my large music library, I noticed that several tracks got the wrong tags/metadata.
Since I didn't back up my files before processing them with 1T, I was wondering if you can add a button also to delete all the tags/metadata from all the tracks within a folder/playlist :)

Cheers!

**Comment by Marekkon5** [comment]
Hello, 1T doesn't have such functionality, however bulk tag editors such as mp3tag should do this fine.

**Comment by prisse89** [comment]
Yes, it does. Thanks for the tip ! 
Cheers!
