### ISSUE TITLE
Spotify not working properly 

### ISSUE THREAD

**Issue by Brentnhh** [Marekkon5/onetagger#164]
Spotify stopped tagging my music after 30 seconds. tried to delete and install the app, still not working properly.

**Comment by chriswill0w** [comment]
same thing happening for me

**Comment by peter9811** [comment]
Same here

The log file is almost empty:
`2023-02-05 13:54:28 [INFO] onetagger: 

Starting OneTagger v1.5.1 Commit: ff05c2d4 OS: windows


2023-02-05 13:54:28 [INFO] onetagger::ui: Starting server on http://127.0.0.1:36913 ws://127.0.0.1:36912
`


and the Spotify web show "INVALID_CLIENT: Invalid redirect URI"

**Comment by Marekkon5** [comment]
Hello, did you set properly the Redirect URL on your Spotify account settings, when creating the app there? It should be `http://127.0.0.1:36914/spotify`
