### ISSUE TITLE
Beatport match not found

### ISSUE THREAD

**Issue by KeelDev** [Marekkon5/onetagger#17]
Hi,

Just going through some/all tracks which failed to match on beatport with auto tag in onetagger and checking manually against site search.

Onetagger cannot match a .flac file with meta set as:
ARTIST=808 State
TITLE=In Yer Face (Bicep Remix)

This is with strictness at 0%, match duration off, and even tried against filename with no success. How can onetagger not find this track which is located at:
https://www.beatport.com/track/in-yer-face/8376922 ?

I will let you know of any other cases i find if you wish. Note: Auto tag was only run against beatport, none of the others. Cheers

**Comment by KeelDev** [comment]
Just had a case where this didn't get a match, with 0% strictness:
ARTIST=Alan Braxe, Fred Falke
TITLE=Intro (Original Mix)

It is the artist which is the issue. I like to have the main artist first but beatport often puts it last. I got the match with either:
ARTIST=Alan Braxe & Fred Falke
ARTIST=Fred Falke, Alan Braxe (as is on beatport site)

I don't use & sign in my library and prefer to just use comma , to seperate artists. I know this is a personal thing and you may decide this is correct operation and doesn't require addressing. Just making you aware of cases where even 0% strictness cannot find a match but it is there.

Just to make you aware, the software is amazing, I am just trying to help, I will give you feedback and you can do literally whatever you like with it :-)

**Comment by KeelDev** [comment]
Another none match: 50% strictness (cannot see 1 symbol or letter difference though)
Title: Disco Inferno (Qubiko Remix)
Artist: Antonio Lanotte
Year: 2017-05-19

https://www.beatport.com/track/disco-inferno/9307875

**Comment by KeelDev** [comment]
Title: Morning Falls (Original Mix)
Artist: Ben Bohmer
Year: 2018-01-05

https://www.beatport.com/track/morning-falls/10090488

**Comment by KeelDev** [comment]
Title: What I Might Do (Club Mix)
Artist: Ben Pearce
Year: 2012-01-01

https://www.beatport.com/track/what-i-might-do/12227416

**Comment by KeelDev** [comment]
Title: Anbar (Original Mix)
Artist: D-Formation
Year: 2018-12-07

https://www.beatport.com/track/anbar/10332696

**Comment by KeelDev** [comment]
Title: Testify (Danny Krivit Edit)
Artist: Davie
Year: 2020-09-11

https://www.beatport.com/track/testify/14143594

**Comment by KeelDev** [comment]
ok, that is enough examples for tonight, hopefully they offer some insight into what the issue is. All above tested at about 50% strictness. Had about 2500 tracks matched no issue. Let me know if you find anything and if this was helpful. Cheers

**Comment by KeelDev** [comment]
Sorry, forgot to add something which is probably really important, although not sure if it matters, I am running the absolute latest version from github actions.

**Comment by Marekkon5** [comment]
Hey, thanks for the research, I've tested them one by one copy pasting the title & artist you provided, using 70% strictness, only Beatport.

- In Yer Face (Bicep Remix) = I got successful match. 
- Alan Braxe - Intro = I actually found out there was a bug caused by one of 1.2.0 features, so I fixed it and got it matched.
After this all the following tracks got matched successfully, so I assume that was the culprit. 
The latest commit contains the fix, you can again try the binary from Actions tab.

Reopen if you have more issues, thanks.
