### ISSUE TITLE
 Export Configuration (Backup)

### ISSUE THREAD

**Issue by fabianolops** [Marekkon5/onetagger#174]
How do I export the configuration of genres and quick tags defined by me?

**Comment by Marekkon5** [comment]
You can go to Settings > Advanced > Open data folder and there the settings are saved as `settings.json`

**Comment by ripapi** [comment]
Would it be possible to add this setting into the software for next releases please ? 
= Being able to save a configuration and choose which one to set directly from 1T 

This would be great. Thank you for your work !

**Comment by Marekkon5** [comment]
You mean like several QT profiles with different settings? Isn't that redundant? Whats your use case?

**Comment by ripapi** [comment]
I mean several autotag option sets, for exemple one to get only the album art or one to get only genre ans style with shazam off depending on what data is missing in your tracks. I have few itunes playlists for this and I wish it would be quicker to select what data I want to add to my tracks.
