### ISSUE TITLE
Rekordbox not loading new metadata

### ISSUE THREAD

**Issue by eldirto** [Marekkon5/onetagger#177]
Currently, I am unable to get Rekordbox to load any of the new metadata that OneTagger has added to some of the mp3 tracks in my collection.  I have checked that the ID3 tags are being updated using another application but when reloading tags via Rekordbox, I don't see any changes to the relevant fields; rating, mood, or anything I have added to the comments field.

Please could you advise on what either I am doing incorrectly or have not setup correctly inside of OneTagger or Rekordbox.  I appreciate any advice/support.

**Comment by bascurtiz** [comment]
Strange? I'll record how I'd do it, then you might spot the difference between your approach and mine.
So brb.

**Comment by eldirto** [comment]
> Strange? I'll record how I'd do it, then you might spot the difference between your approach and mine. So brb.

Thank you for taking the time.

**Comment by bascurtiz** [comment]
Here you go: https://youtu.be/CYJUOOIz1fQ
Let me know what could've been different with your approach.

**Comment by eldirto** [comment]
Thanks for the detailed walkthrough of how you'd get the auto-tagged data to load in RB.  I haven't used this feature yet.  My issues are occurring when using the QuickTag section of OneTagger.

**Comment by bascurtiz** [comment]
The same principle applies to Quick Tag though. 
See: https://youtu.be/I-GQwT4lllQ

**Comment by eldirto** [comment]
Followed your video but still experiencing issues.  Anything I add in OneTagger isn't being picked up by RB when using the Reload Tag function.  I thought it might be because I had cloud sync enabled for that playlist, so turned it off.  Also turned off the cloud sync option inside of RB, still doesn't work.  I feel like either RB isn't actually reloading the ID3 tag data or it is getting overwritten somehow.

NB:  I am able to edit ID3 tag data inside of RB.

**Comment by eldirto** [comment]
OK, I have figured it out and hopefully this will be a nice note for anyone in my situation.

If you have RB set to Cloud Sync, even if you switch it off, it still lists file location in the cloud.  You have to right-click and move the playlist or files to local storage.  Then when you reload tags, it works.

Thanks for taking the time to show me how you do things and helping me figure my issue out.  Great software by the way!

**Comment by bascurtiz** [comment]
Thanks! And I learned something new too :)
Next time we get such issue reported, I'll refer them to your post here.
