### ISSUE TITLE
Search bar and tracklists disappear in 11f631a

### ISSUE THREAD

**Issue by martyn0ff** [Marekkon5/onetagger#179]
In commit 11f631a, as soon you start typing in the search bar in Quick Tag, the track list and search bar disappear. The following error shows up in the terminal:
```
http://127.0.0.1:36913/assets/index.c9d21a48.js:1:15206: CONSOLE ERROR TypeError: q.toLowerCase is not a function. (In 'q.toLowerCase()', 'q.toLowerCase' is undefined)
```

**Comment by Marekkon5** [comment]
Hello, should be fixed in the latest commit. You can get the binary from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues. Thanks
