### ISSUE TITLE
Quick Tag view does not load completely the first time you open a folder

### ISSUE THREAD

**Issue by lord-carlos** [Marekkon5/onetagger#18]
Version 1.2.1

Steps to reproduce:

- Open Quick Tag view
- Select a folder for the first time

Observe:

- Songs get loaded, but left, right and bottom bar don't show up. No ability to play to song or tag them

Workaround:

- Switch to another tab and back to Quick Tag

![image](https://user-images.githubusercontent.com/155855/124379654-9eb9c500-dcb8-11eb-95bc-d64f9ac81f95.png)

**Comment by Marekkon5** [comment]
I actually wasn't able to reproduce this specific issue with picking folder, however I do know that it happens after refreshing while on Quick Tag tab. I've implemented fix for it, which might fix this too. Please reopen this issue if it doesn't work and I'll try other fixes. Thanks.

**Comment by lord-carlos** [comment]
Thanks. Seems like that fixed it.
