### ISSUE TITLE
Request: Cancel button for auto tag process

### ISSUE THREAD

**Issue by andylundqvist** [Marekkon5/onetagger#180]
See title, I am currently auto tagging hundreds of files and there is something wrong with the lookup but I see no way of manually stopping the process. A button for this (maybe next to the progress bar) would be helpful.

**Comment by Marekkon5** [comment]
You can safely close the window.

**Comment by rosgr100** [comment]
Not sure about recent releases but long time ago i found out -through mp3diags- that "force" closing the window was causing corruption to the files.

**Comment by Marekkon5** [comment]
ok well i assumed it would just work, considering that closing window should "gracefully" terminate it, but whatever. I didn't want to add it earlier, because it's messy to add. Added in latest commit. Binary to test is in the Actions tab.
