### ISSUE TITLE
Log file for written tags

### ISSUE THREAD

**Issue by ThisIsOniBaku** [Marekkon5/onetagger#182]
Is there a way to see a log file for what tags have been written by the auto tagger? I would like to be able to have a record of the changes made in case there is a false identification. That way I will have some idea of what the song should be without having to manually identify and re-tag it.

**Comment by Marekkon5** [comment]
Yes, the log is located in the 1T data folder ( Settings > Advanced > Open data folder)

**Comment by ThisIsOniBaku** [comment]
Awesome, I was looking in the folder where the application is for a log file. Forgot to check for a data folder. Also missed the button in the settings, it shows at the top of the 'General' tab for me. Thanks!
