### ISSUE TITLE
[Feature Request] Ability to backup QuickTag associations

### ISSUE THREAD

**Issue by martyn0ff** [Marekkon5/onetagger#183]
I had an idea for the feature today, which I think many would appreciate. We already have the ability to back up QuickTags structure, which is great. Consider introducing the ability to back up QuickTag associations themselves with the ability to recover them later on in case a user loses all of their music. It may go something like this:
1. User selects which tags uniquely identifies a track as a global option (I can think of a standard catalog number and/or artist-title pair since these are unlikely to change)
2. OneTagger produces a JSON file with the structure like this:
```json
{
    [
        {
            "identified_by": [
                {
                    "CATALOGNO":"CATNO042"
                }
            ],
            "tags": [
                {
                    "MyCustomTag":"MyCustomValue",
                    "MyOtherCustomTag":"Comma, Separated, Values"
               }
            ]
        }
    ]
}
```
3. User recovers their lost audio files, and re-tags them again with an AutoTag
4. OneTagger scans files provided for the presence of tag `CATALOGNO` with value `CATNO042` and if it finds it, it populates this audio file with these two tag-value pairs  Tags can be different for MP3/FLAC/APE.

**Comment by Marekkon5** [comment]
Hello, I do understand Your point and the purpose, however I do believe that this is super niche, and 99% of users won't even use. Also you can just solve this same way most people do - by backing up your original library (which should be even more correct and reliable).
