### ISSUE TITLE
Genre / beatport

### ISSUE THREAD

**Issue by ScrewedDriver** [Marekkon5/onetagger#185]
I've got a bunch of albums and tracks which have the Tags like i'd like them to have.
For these tracks I would like to use onetagger to **only** pull the genre from beatport.
Is there a way to archive this?

**Comment by Marekkon5** [comment]
You can just tick Beatport in the platform selection and just tick Genre in the tags selection.

**Comment by ScrewedDriver** [comment]
Thank you!
