### ISSUE TITLE
Weird results from discogs

### ISSUE THREAD

**Issue by bladerelic** [Marekkon5/onetagger#187]
once again, i can't express how much i love this program.  it has helped me out a lot even though it has a few quirks.

when using discogs, some songs pull up some strange results for the Genre.

for instance, onetagger will tag "The Beach Boys - Good Vibrations" genre as "4th Of July".  i guess that makes sense until you look through the releases on discogs and notice that none of them have the genre marked as "4th Of July".  you can even do a genre/style search on the website and it will show no results.

another song is "Total - Kissin' You".  this one shows the right genres, but for style it shows "RnB/Swing, Soul, Pop Rap".  the "RnB/Swing" part is correct, but none of the song releases even mention "pop rap".

any clue as to why these weird results appear for certain songs?

**Comment by Marekkon5** [comment]
It is possible that 1T doesn't correctly match the given song and therefore the genres/styles you see are from a different song. You can enable writing track id / release id to see the matched track id.

**Comment by bascurtiz** [comment]
Weird...
Can't reproduce with these songs?

See: https://youtu.be/yEO4zM215e8

Maybe upload these 2 files, so we can inspect?
And try the latest build from the Actions tab?

**Comment by bladerelic** [comment]
i am going to try Marekkon5's idea and write the track & release ids.  that will help me diagnose what could be going on.  this also happens when i use the shazam feature, so i never thought about the track ids.  by the way, i am using the latest version from the actions tab  (thanks for including deezer)

**Comment by bladerelic** [comment]
the Release ID it finds for "Total - Kissin You" is 78490. for "The Beach Boys - Good Vibrations" it is 199469, although now it seems to be pulling the correct info for the beach boys.  i dont know what changed

**Comment by bladerelic** [comment]
oh i see what is going on now.  its finding the songs on the album release even though the song singles also exist on discogs. so the album that contains the song is "pop rap".  i dont know if there's a way to fix that since its not really an issue/bug
