### ISSUE TITLE
It's possible add other methods to support?

### ISSUE THREAD

**Issue by peter9811** [Marekkon5/onetagger#189]
I'm on Australia and my account of PayPal don't work for now 

It's possible put/buy a "donator" key or something else on your website?

**Comment by Marekkon5** [comment]
Hello, thank you for trying to supporting us. You can support us on [patreon.com/onetagger](https://patreon.com/onetagger) or on GitHub Sponsors https://github.com/sponsors/Marekkon5

**Comment by peter9811** [comment]
Thanks. I tried before with Patreon, but I really don’t like it 

I just did through GitHub. Have a good one

**Comment by Marekkon5** [comment]
Thank you very much.
