### ISSUE TITLE
Spacebar will not always play/stop, but press the last button

### ISSUE THREAD

**Issue by lord-carlos** [Marekkon5/onetagger#19]
- Be in Quick Tag view
- Have songs loaded in
- With the mouse click on setting gear icon or "browse folder to load"
- close the settings menu again
- Press spacebar to play / stop the currently selected song

Observe: 
- Settings menu opens again

Expected:
- song plays / stops

**Comment by Marekkon5** [comment]
Should be fixed in latest commit. You can get binary from Actions tab. Reopen if you have any issues with it, thanks.

**Comment by lord-carlos** [comment]
I think it's fixed for setting menu, but not for open folder or drag 'n drop button. 

I don't think I can re-open the issue.

**Comment by Marekkon5** [comment]
Should now work in latest commit.
