### ISSUE TITLE
Auto Tag request

### ISSUE THREAD

**Issue by nmycps** [Marekkon5/onetagger#190]
As vinyl and CD both have their original catalog numbers, so far only Discogs has the 'CatalogNumber' information. It would be great to be able to extract it in Auto Tag.

**Comment by bascurtiz** [comment]
Wym?
You can already?
See:
![image](https://user-images.githubusercontent.com/34075088/222741022-b66e5a69-bec0-4e4b-a886-be5aa5b0c95a.png)

**Comment by nmycps** [comment]
I missed it. Thanks!
