### ISSUE TITLE
Deezer

### ISSUE THREAD

**Issue by TommyMcMusic** [Marekkon5/onetagger#195]
Gettin API ERROR 500 on all scanned items

**Comment by Marekkon5** [comment]
Hello, Deezer works fine for me, could you specify some example track name + artist, so I can reproduce? Also if you could provide the log (delete old one, and send smaller one with just the Deezer session). Thank you.

**Comment by TommyMcMusic** [comment]
I decided to do a fresh download and it started to work, its still a bit hit and miss but it is for the most part working well!

**Comment by Marekkon5** [comment]
Feel free to comment / reopen if you can reproduce the issue again with some more info.
