### ISSUE TITLE
Skipping Not Quite Working

### ISSUE THREAD

**Issue by TommyMcMusic** [Marekkon5/onetagger#196]
So i have been scanning some music today and I noticed there was tracks that were being skipped in the scanning process that didn't have a 1T, artwork or any release year, after a bit more digging it seems to happen quite alot. Any thoughts?

As this music is part of my rekordbox collection there is some meta data it does contain but non of the above, the only info i have on my tags prior to scanning is the Genre, BPM & Key, all of which come from Rekorbox itself.

The tracks that are skipped didn't seem to have a common issue, it seemed to be random becuase as I said, all my mp3s have the above info on the meta data but digging further I have found that the ones that are skipped are tags that are ID3V2.4.0 where as the tracks that are scanned as normal are ID3V2.3.0

So for whatever reason, its seeing 2.4.0 tags as already tagged even though they aren't

**Comment by Marekkon5** [comment]
1. You can check the log for the skip reason
2. Your tracks must have title + artist tag (or Shazam or parse filename enabled)
3. 1T checks for `1T_TAGGEDDATE` tag whether to skip or no

**Comment by TommyMcMusic** [comment]
I already do have Shazam & parse filename enabled

**Comment by Marekkon5** [comment]
Could you provide the log? (Maybe delete the old one first, run once and then send). Thank you.

**Comment by TommyMcMusic** [comment]
2023-03-11 13:09:12 [INFO] onetagger_autotag: [spotify] State: Skipped, Accuracy: None, Path: /Volumes/Core Drive/Music/Student/Beastie Boys - Fight for your Right (To Party).mp3

This is an example of one of the tracks that does not scan

**Comment by Marekkon5** [comment]
1. Could you send the whole log as it contains more information?
2. You can hover with your mouse over the yellow skipped icon to see the reason it was skipped.

**Comment by TommyMcMusic** [comment]
Yeah sure here we go
[onetagger.log](https://github.com/Marekkon5/onetagger/files/10948615/onetagger.log)

**Comment by Marekkon5** [comment]
It seems that the skipped tracks do not have title + artist, so they fallback to using Shazam, however Shazam fails because the file seems to be corrupt (or have some little corrupt audio frames). 

You can use tools like AudioTester to check if your files are corrupt https://codecpack.co/download/audiotester.html

**Comment by TommyMcMusic** [comment]
Ok thats possible but why are the skipped tracks almost exclusively 2.4.0?

**Comment by Marekkon5** [comment]
Most likely because of the source? 1T seems to read your ID3v2.4 tags fine, but fails to find the title + artist, and then it fails on decoding the audio data for Shazam, so the tag seems to be fine/readable, the audio not (perfecrly).

**Comment by TommyMcMusic** [comment]
Can it be relaxed in some way so it doesn't need a perfect read, its not tagging a massive amount of music because of how seemingly perfect it needs to be, in large collections such as mine, its likely to be a problem alot of people come up against, any way to get around this?

**Comment by TommyMcMusic** [comment]
I also tried putting in the title and artist manually and it still skipped

**Comment by TommyMcMusic** [comment]
Ok so I got it to scan correctly, i reconverted the mp3's and it found everything just fine

**Comment by Marekkon5** [comment]
There are also tools which can "repair" the mp3 files. Or reencoding should work too.

**Comment by TommyMcMusic** [comment]
I still don't know how to identify mp3's in batch that don't have artwork, how can I do that on mac, i can't seem to get a clear answer on google

**Comment by Marekkon5** [comment]
Depends on what is the purpose of it:

- If you want to add artwork using 1T to files which don't have it: enable just the Album Art tag, and disable overwriting tags.
- If you want to just view a list of tracks whether they have artwork or no, you can probably use tag editors such as Mp3Tag, or Kid3, or some Mac equivalent.
- If you want to copy/move tracks without artwork, you probably have to make some script utilizing cli tools such as mediainfo or ffprobe. (optionally I could add this to renamer in 1T).

**Comment by TommyMcMusic** [comment]
So here is an example of a track that I can't get any hits on, it comes up as failed not skipped

Block & Crown - Take Control

I used a mp3 repair tool only to find it doesn't need repair, i then reconverted the mp3 and scanned again and it still doens't find anything

I double checked on google to amke sure its still available for sale on all the stores and streaming platofrms and it is

**Comment by Marekkon5** [comment]
I've copy pasted the title and artist to a dummy mp3 file and started 1T with Deezer enabled. It detected the track.

Are your title & artist tags correct? 

![image](https://user-images.githubusercontent.com/15169286/224489793-51ba00c6-be6b-4a5d-b901-0868c35808b5.png)

**Comment by TommyMcMusic** [comment]
It seems that MusicBrainz was the issue, it has now found it, and on another 2 tracks i had disable shazam for them to be found

**Comment by Marekkon5** [comment]
You might want to keep Shazam on, but disable the "Force Shazam" to make it not always Shazam if tags are available.
