### ISSUE TITLE
RateYourMusic.com

### ISSUE THREAD

**Issue by bladerelic** [Marekkon5/onetagger#198]
are you able to add the ability to search and parse data from www.rateyourmusic.com?

**Comment by Marekkon5** [comment]
Hello, I've actually implemented RateYourMusic.com, however in the testing phrase I noticed that they're blocking the traffic, detecting scraping etc.

So won't be added to 1T.

![image](https://user-images.githubusercontent.com/15169286/224966451-f39d1db4-8522-4941-b50d-906bfcb576d3.png)
