### ISSUE TITLE
multiple disc compilation fail

### ISSUE THREAD

**Issue by nmycps** [Marekkon5/onetagger#199]
A particular CD box set I was trying to tag was a wreck when using Auto Tag. Multiple disc sets seem to get completely mislabeled, at least this one does. Spent at least 2 hours trying to make it work. I tried tagging all discs at once; individual discs; but it writes the tags in the wrong order from the '#' tag. The box set I am working on is [(https://www.discogs.com/release/8473451-Masters-At-Work-The-Tenth-Anniversary-Collection-Part-One-1990-1995)].

**Comment by Marekkon5** [comment]
Hello, what do you mean by the '#' tag? Is it track/disc number? I also don't understand the issue correctly, can you tell which track from this release gets mislabelled and which tags are incorrect? Thank you

**Comment by nmycps** [comment]
For example, on the first CD of this box set entitled 'Vocals', the track numbers were already labeled correctly on my files after I ripped the CD, and I added the discogs_release_id as well, but then when using Auto Tag, it wasn't assigning  the title, artist, and track numbers correctly. In other words, the tags looked correct, but was not the correct file. Examples:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/61409851/224558974-ac074efc-ab34-4290-a453-9085ac7ba2bb.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/61409851/224559019-fea8aeef-cdc1-4dbd-ae02-9fa65ce2b5af.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/61409851/224559041-ee1bf371-093e-4745-ac1d-43153008ae0b.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/61409851/224559102-83ed4fc2-b52a-44b6-8fcf-8ceb7e565dd1.png">

**Comment by bascurtiz** [comment]
By any chance, u have Shazam enabled?
Perhaps Shazam mis-identified these tracks?

When I purely use artist + title as input, it finds 3/4 fine:
https://user-images.githubusercontent.com/34075088/224567601-b547c1be-c5cb-4194-bf4b-a0ac2c85b715.mp4

**Comment by nmycps** [comment]
I don't have Shazam enabled. I noticed in your video that the files it tagged all had different catalog numbers, discogs release id and artwork. I'm trying to get the exact match so I must enter the discogs release prior to running Auto Tag. If I leave the Tracknumber (unchecked) it tags fine. But if I overwrite the Tracknumber that's already there, it will assign tagging info to the wrong files. So it seems to be okay if I do not tell Auto Tag to overwrite the existing track numbers.

**Comment by Marekkon5** [comment]
The track number and rest of the tags in Autotag come from the same album, so it probably matches the songs it found from different albums rather than from the compilation. You can disable the track number if it solves your issue.

**Comment by nmycps** [comment]
Yes, I think it will. Thanks!
