### ISSUE TITLE
Mouseover text does not display in full | Scaling | Windows

### ISSUE THREAD

**Issue by lord-carlos** [Marekkon5/onetagger#20]
Hi

The mouseever text on bottom right in Quick Tag does not display properly. Might be a scaling issue, as I run with 125%
![image](https://user-images.githubusercontent.com/155855/124380001-ac704a00-dcba-11eb-8552-dde51972741e.png)

But the ones in Auto Tag do work:
![image](https://user-images.githubusercontent.com/155855/124380022-c742be80-dcba-11eb-9073-1357deb231b7.png)

Version 1.2.1
OS: Windows
Scaling: 125%

**Comment by Marekkon5** [comment]
I've just checked it, this is more of Quasar improperly calculating the tooltip size when Windows scaling is enabled. However making the window just slightly wider and taller (for some reason) it works properly.

**Comment by lord-carlos** [comment]
Oh, I just notice it does not work for me when maximized.
It work when it's almost maximized. Weird.

**Comment by Marekkon5** [comment]
What's your resolution?

**Comment by lord-carlos** [comment]
1440p, (2560 x 1440)
125% scaling
Same issue on my vertical screen.

It works if the windows is just below minimum resolution. It also works if the windows is larger than screen resolution. It stops working when the windows is maximized.

**Comment by Marekkon5** [comment]
We tested it, very weird behavior but pretty much a Quasar issue, rather than 1T. Unless we get some new ideas I won't be really fixing / solving this as Windows is infamous for breaking stuff at higher scaling and it's just a informational tooltip. Sorry for the inconvenience.
