### ISSUE TITLE
Live Feedback/Genius - source

### ISSUE THREAD

**Issue by TommyMcMusic** [Marekkon5/onetagger#200]
I was telling a friend about OneTagger (now downloaded) and he told me he uses VirtualDJ's "Live Feedback/Genius" for artwork at the like, he said this is has a VirtualDJ user generated element to it so maybe instead of OneTagger having its own Community source, you could maybe talk to VirtualDJ about making its Live Feedback/Genius a source?

**Comment by bascurtiz** [comment]
Too niche imo. And probably property of VirtualDJ / closed-source.
So let's not get into their territory.
