### ISSUE TITLE
Start playback immediatley on skip

### ISSUE THREAD

**Issue by KeelDev** [Marekkon5/onetagger#203]
Hi, Awesome work!

On skipping to the next track, playback will start automatically once the track has fully loaded. I can start playing immediately by pressing the spacebar but would like this automatic and instant. It can take quite some time on longer tracks before the track starts to play.

Is this possible? Thank you

**Comment by Marekkon5** [comment]
What OS are you using? It is done this way because on Windows it would throw an error if file was read twice at the same time.

**Comment by KeelDev** [comment]
Oh I see, I am on macOS Ventura

**Comment by Marekkon5** [comment]
Since this has been requested before, and it works on Linux (and apparently on Mac too), I added a patch, however on Windows it will have the same behavior.
