### ISSUE TITLE
OGG Files

### ISSUE THREAD

**Issue by byecoco** [Marekkon5/onetagger#209]
Perfect software, finds info for FLAC & MP3 songs but not for my OGG files. 

Version (1.6)
[onetagger.log](https://github.com/Marekkon5/onetagger/files/11142618/onetagger.log)

**Comment by Marekkon5** [comment]
Hello, it should be fixed in the latest commit. You can get the binary from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues. Thank you.
