### ISSUE TITLE
Music folder location does not get saved 

### ISSUE THREAD

**Issue by lord-carlos** [Marekkon5/onetagger#21]
Unless you switch away from the Quick Tag tab, the settings don't get applied.

* delete your settings.json
* open the application
* switch to quick tag tab
* select your music folder, do you thing with tagging :)
* close the application
* open the application

Observe:
* You have to find your music folder again

Expected:
* Setting should be saved after you select your music folder.

Workaround:
* select your folder
* switch to another tab

**Comment by Marekkon5** [comment]
I guess you selected the folder using the "no folder selected" screen rather than settings, right?

**Comment by lord-carlos** [comment]
> I guess you selected the folder using the "no folder selected" screen rather than settings, right?

That is correct.

**Comment by Marekkon5** [comment]
Should be fixed in latest commit.
