### ISSUE TITLE
Musicxmatch don't work

### ISSUE THREAD

**Issue by peter9811** [Marekkon5/onetagger#211]
I just clean the log to catch only the problem with it
[onetagger.log](https://github.com/Marekkon5/onetagger/files/11182500/onetagger.log)

Where can I search to found the problem?

**Comment by Marekkon5** [comment]
Hello, unlike other platforms, Musixmatch does the matching on their side, so 1T just passes the title + artist and hopes Musixmatch does return the correct track. There isn't much we can do (I could perhaps improve it by sending ISRC or combining with iTunes to get the ID). 

Check if your metadata is clean and correct and if those songs are really available.

**Comment by peter9811** [comment]
I think maybe it’s the quantity or something. Because, the first songs are of Adele (so popular, I think. And I already checked on MusicXmatch before and the songs are there) 

What could I do to check the possible problem?

**Comment by Marekkon5** [comment]
If you think that's the case I'll try to debug it later with your tracklist.

**Comment by Marekkon5** [comment]
I've noticed that Musixmatch starts to return 401 (Captcha) error after several requests. I've made it retry with some delays, and regenerate token as well, however because of the captcha the process is now super slow. You can get the binary from the Actions tab.

**Comment by peter9811** [comment]
Thanks, mate. I going to check in a couple of hours. Probably was that
Maybe with free account of MusicXmatch, but I think would be the same for the amount of requests, on my case 4K songs

**Comment by peter9811** [comment]
Ohhh… Right. I used to used modded version on Android, but yeah, normally only 30 % lyrics or advertisement

**Comment by Marekkon5** [comment]
The Android API is obfuscated... So no go for 1T.


Also you might wanna try the Apple Music plugin which has lyrics as well and should be faster. However it requires paid subscription.

**Comment by peter9811** [comment]
I think I would get the modded APK with the “premium” thinks, but I don’t
know if would be worth or totally useless if you said that have the API
obfuscate

**Comment by peter9811** [comment]
I think is working perfect now. A little slow like you said, but any big problem :)
