### ISSUE TITLE
id3 date fields: TDAT

### ISSUE THREAD

**Issue by certuna** [Marekkon5/onetagger#214]
In [tags.ts](https://github.com/Marekkon5/onetagger/blob/2ed122aecd12e6001df30e38fc04f83e7dbd4b02/client/src/scripts/tags.ts#L19   ) there's the following tag mapping:
```
"TDRC": "Date Recorded",
"TDOR": "Original Year",
"TDAT": "Release Date",
"TDRL": "Releasetime",
```
I get the first two, these correspond directly to the [id3v2.4](https://github.com/id3/ID3v2.4/blob/516075e38ff648a6390e48aff490abed987d3199/id3v2.4.0-frames.txt#L591) specs, and same with `TDRL` (also a valid frame), but is there a reason why `TDAT` in there? It's not a valid id3 frame, and AFAIK not used by any tagging application?

Most tagging apps/libraries (mutagen, ffmpeg, TagLib, kid3, mp3tag, etc) have the following mapping:
`TDRC` -> `date`
`TDOR` -> `originaldate`
`TDRL` -> `releasedate`

**Comment by onetagger** [comment]
`TDAT` is used in combo with `TYER` with Traktor Pro, to form `Release Date` when reading/writing `ID3v2.3` for example.
See https://docs.google.com/spreadsheets/d/1Atb26winoLgb_w_oX12npmZzqx3IVkCbkzn9Ug6R6B8/edit?usp=sharing
And also: https://picard-docs.musicbrainz.org/downloads/MusicBrainz_Picard_Tag_Map.html

**Comment by Marekkon5** [comment]
The `tags.ts` mapping is used just for UI (like when you're picking the tags in dropdowns, typing them or viewing in Tag Editor). Therefore it's mixed ID3v2.4 with ID3v2.3 since in those scenarios both versions can be present and it doesn't matter which one is which in the file.
