### ISSUE TITLE
Quick tagging into mp4 files

### ISSUE THREAD

**Issue by bmac6996** [Marekkon5/onetagger#215]
If i add a single tag into an mp4 file in the "grouping" field, is it normal for it to add a "," in the beginning of the tag even though it's just a single tag? 

I have only seen this behavior on mp4.  Mp3, it does not do this.

the tags i'm adding do not have leading or trailing white spaces

seperator is set both for id3 and mp4/m4a as ","

Thanks in advance.

Great software BTW!  Have been a saving me alot of time in quick tagging songs for advance crates.

**Comment by Marekkon5** [comment]
Hello, what do you use? Tag editor? Quick tag?

**Comment by bmac6996** [comment]
Hi, I'm using the quick tag feature.  Setup custom tags tagging to "grouping".  for mp4/mfa, it's setup to "@grp".  While  id3 is set to TIT1.

**Comment by Marekkon5** [comment]
Hello, should be fixed in the latest commit. You can get the binary from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues. Thanks

**Comment by bmac6996** [comment]
Hello, I am using the new version as stated.

The comma in the beginning quick tag is fixed, but now in order to recognize a tag for mp4s, there needs to be a space after the 1st tag.

For example:

![image](https://user-images.githubusercontent.com/22140612/236065964-acb11662-27f6-46b7-b6e3-d5ee5f00bbf3.png)


"lv3,lv4" = reconized this is an mp3
"lv3,lv4, lv3, lv4" = 1st "lv3,lv4" not reconized in program but "lv3, lv4" is not.  this is an mp4

hope that makes sense.

Thanks

**Comment by Marekkon5** [comment]
Perhaps your MP4 separator is `, ` (comma with space)?

**Comment by bmac6996** [comment]
sigh.. long day.. that was it.  Thank you for the direction.
