### ISSUE TITLE
What is the syntax for the functions in auto-rename?

### ISSUE THREAD

**Issue by ev0net** [Marekkon5/onetagger#216]
I tried variations of %bpm% - uppercase(%title%) - %artist% produces BPM - uppercase(Title) - Artist rather than BPM - TITLE - Artist

I couldn't find syntax in help or video. Thanks in advance and for the awesome software!

**Comment by Marekkon5** [comment]
`%title.uppercase()%`

**Comment by ev0net** [comment]
Thank you!
