### ISSUE TITLE
Ignoring parentheses and brackets

### ISSUE THREAD

**Issue by bmac6996** [Marekkon5/onetagger#217]
Feature request:

For better matches, adding the ability to ignore words within parentheses and brackets.

Alot of record pools with extends, cuts, remixes, etc put the name and/or type in parentheses and brackets.   Could help?

Thanks for the hard work.

**Comment by Marekkon5** [comment]
Hello, a lot of the words in parentheses are already cleaned up when matching. If you need more there is a clean for matching regex option in the advanced settings. Thank you.

**Comment by bmac6996** [comment]
I saw that field.  Do you enter the complete format of what to ignore in regex or what it should match and then ignore everything else?

**Comment by Marekkon5** [comment]
It removes the match, so the regex should match the bad parts
