### ISSUE TITLE
Quick Tag doesn't prompt to save on exit, potential data loss

### ISSUE THREAD

**Issue by Muppetteer** [Marekkon5/onetagger#22]
Quick Tag only prompts to save a file if you select another track without hitting CTRL+S first. This leads to a bug where you can exit the program without saving the last track that you quick tagged and you lose your changes.

To reproduce:
1. Quick tag mode.
2. Tag a file then press arrow down, you are prompted to save.
3. Tag another file, now don't save or change selected track, instead exit the program.
4. OneTagger exits and changes to the last file are lost.

As an aside, I find the save prompt kind of redundant and would prefer if it just saved files without prompting me.

**Comment by Marekkon5** [comment]
Due to library limitations, I can't register the window closing event on other platforms than Windows, so I won't be implementing this right now. You have to use CTRL + S or enable autosave and skip to next track.

**Comment by Muppetteer** [comment]
Oh well not to worry. Thanks for the autosave tip, I had not noticed that option.

**Comment by Marekkon5** [comment]
Bit late, but added in latest commit due to change in webview libraries. You can get the build from Actions tab. Feel free to comment or reopen if you have more issues.
