### ISSUE TITLE
Genre/Style merge uses wrong format

### ISSUE THREAD

**Issue by sonofevil** [Marekkon5/onetagger#222]
**How to reproduce:** Run the autotagger and select "Merge to Genre tag" in the "GENRE / STYLE / SUBGENRE OPTIONS".

**Expected result:** Files are tagged with multiple string values for the genre tag.

**Actual result:** Files are tagged with one long string value containing a comma-separated list of genre/styles.

I don't know the tech behind it, but Foobar2000 and Dolphin file browser are able to tell the difference between multiple values for the same tag and one long string with comma separated values. In Dolphin for example, a file tagged as both "metal" and "death metal" as separate values will be shown as "metal and death metal" in the file properties panel, whereas a file tagged with the value "metal, death metal" will instead be shown as such. 

In Foobar2000 this distinction very much matters, because if you browse your music library by tags, files tagged in the former manner will be shown _both_ under the "metal" _and_ the "death metal" tag, whereas files tagged in the latter manner will _only_ be shown under the "metal, death metal" tag. Obviously the latter is practically useless. Foobar2000 lets you assign multiple values to the same tag field by separating values with ";" when typing in the tags. The semicolon is not parsed as part of the string, but as an instruction to add a new value to the array.

Unfortunately One Tagger uses the latter formatting. I.e. it seems it treats the "Genre" field as a single-value variable rather than as an array of values. Again, I don't know how exactly this difference is handled in the actual tag encoding, but it looks very much like a variable/array distinction.

**Comment by Marekkon5** [comment]
Hello, what is your file format? If it's m4a/flac/ogg then you can delete the tag separator for 1T to write it into multiple genre fields.

**Comment by sonofevil** [comment]
I was using mp3.

**Comment by Marekkon5** [comment]
Hello, ID3 (mp3, wav, aiff) does not support multiple tags. It is not in the id3 standard, and most players have problems with this, therefore it is not supported in 1T.
Either use format which does support multiple tags (flac, ogg, m4a...), or it's some other tag separator.

**Comment by sonofevil** [comment]
ID3 v2.4 supports multiple values for tags.

**Comment by Marekkon5** [comment]
Hello, the ID3v2.4 standard uses the null byte as a separator. You can try using `\0` as tag separator to get multiple values.

**Comment by sonofevil** [comment]
That works, thank you. :)
