### ISSUE TITLE
Auto Tag Completes instantly with Zero Matched, Zero Failed, and Zero Skipped 

### ISSUE THREAD

**Issue by kidemperor** [Marekkon5/onetagger#223]
I am not sure if this is the right location for this or if I did something stupid that caused this myself, but after running auto tag, it completes in zero seconds with zero matched, zero failed, zero skipped. However, the total shows the correct number of songs that I attempted to auto tag. The songs are in ogg format and I am only using Discogs as my source. I made sure to input the token of my account and I double checked that the album was indeed on Discogs. I am using the latest version 1.6.0 of onetagger. Any idea what I did wrong? Let me know if I need to provide more information. Thanks.

**Comment by Marekkon5** [comment]
Hello, could you please send the log? Settings > Advanced > Open data dir and there's onetagger.log. Thank you

**Comment by kidemperor** [comment]
> Hello, could you please send the log? Settings > Advanced > Open data dir and there's onetagger.log. Thank you

[onetagger.log](https://github.com/Marekkon5/onetagger/files/11520940/onetagger.log)

Here's the log file. You can see that I tried autotagging all 1000+ songs and then again with just one album of 13 songs when I was trying to figure out the issue. Thanks.

**Comment by Marekkon5** [comment]
The log says Discogs returned Unauthorized.
- Can you double check your token if it perhaps doesn't have extra spaces at start/end and if it's the correct one?
- Perhaps you could try invalidating it and making new one.

**Comment by kidemperor** [comment]
That fixed it. I clicked generate a new token when I was first having this problem to check if the token was the issue, but the problem persisted after using the new one. It seems a had to delete the token first and then generate the token for it to fix.
Thanks for the help!
