### ISSUE TITLE
Still does not work with OGG

### ISSUE THREAD

**Issue by DJboutit** [Marekkon5/onetagger#224]
I have played aground with One Tagger it seems to be seeing FLACs and Wavs no problem but I think it does not see OGG files even though the newest version should work with them well I can say it does not.  I have tried 35 OGG tracks and it does not see any of them.

**Comment by DJboutit** [comment]
I am am using Autotagger 

Log 

2023-05-22 00:45:03 [INFO] onetagger: 

Starting OneTagger v1.6.0 Commit: 429b0e82 OS: windows


2023-05-22 00:45:03 [INFO] onetagger::ui: Starting server on http://127.0.0.1:36913 ws://127.0.0.1:36912
2023-05-22 01:50:41 [INFO] onetagger: 

Starting OneTagger v1.6.0 Commit: 429b0e82 OS: windows


2023-05-22 01:50:41 [INFO] onetagger::ui: Starting server on http://127.0.0.1:36913 ws://127.0.0.1:36912

![One Tagger](https://github.com/Marekkon5/onetagger/assets/38142712/4eaaf231-6f14-400a-a009-2494c2ecc03a)

![One Tagger 2](https://github.com/Marekkon5/onetagger/assets/38142712/15feb598-d6b5-4781-8327-2c2046233abc)

![One Tagger 3](https://github.com/Marekkon5/onetagger/assets/38142712/b020dcb6-d473-4e3a-888f-3f97f7387fdb)

![One Tagger 4](https://github.com/Marekkon5/onetagger/assets/38142712/6b4d8a2d-d0e5-4941-b501-23fb7d4ac653)

**Comment by Marekkon5** [comment]
Hello, the log is not full, could you please send it as file? Also what extension are your files? Thank you

**Comment by DJboutit** [comment]
Tracks are all OGG Vorbis

When I go to settings then general then click data folder it does nothing

**Comment by Marekkon5** [comment]
Maybe the folder is already open? Or try to manually open the folder by going to AppData (Start > %appdata% and enter should open it) and there it should be in OneTagger folders.

**Comment by Marekkon5** [comment]
Hello, that is not the full log. Either you have not started the tagging process, or you don't send the entire log. Could you send it as file here? Thank you

**Comment by DJboutit** [comment]
[onetagger.log](https://github.com/Marekkon5/onetagger/files/11529354/onetagger.log)

[000003.log](https://github.com/Marekkon5/onetagger/files/11529358/000003.log)

**Comment by Marekkon5** [comment]
Hello, the log doesn't contain any useful info yet.

Could you start the tagging process, wait for it to finish/fail, exit onetagger and send the log again? Thank you.

**Comment by DJboutit** [comment]
![One Tagger Does Nothing](https://github.com/Marekkon5/onetagger/assets/38142712/116c4942-980a-4225-9f39-40b0b0bdccf9)

This is all it does for OGG tracks nothing

**Comment by Marekkon5** [comment]
1. At this point, can you close onetagger and send the log again? It should have some info.
2. Is your path valid? It seems 1T did not detect any tracks. Maybe even some sort of permission error?

**Comment by DJboutit** [comment]
Log file is exactly the same as before

**Comment by Marekkon5** [comment]
I've tested and OGG works for me and @bascurtiz as well. What is your path? Perhaps the folder you're scanning is too large, so it stalls. Also because the log is empty, do you have free space on your drive?

**Comment by DJboutit** [comment]
> You could also try using the latest Actions build since it has some ogg related fixes.

Where is this version??

**Comment by bascurtiz** [comment]
@DJboutit 

https://github.com/Marekkon5/onetagger/assets/34075088/b3578e83-2733-4f0d-9e43-fe422c186697

**Comment by DJboutit** [comment]
I tried the actions build still same thing nothing happened.  This time I got a setting folder here is a copy of my settings

[One Tagger Settings.txt](https://github.com/Marekkon5/onetagger/files/11530948/One.Tagger.Settings.txt)

**Comment by Marekkon5** [comment]
1. We recommend NOT sharing settings as they might contain sensitive information like Discogs token or BPMSupreme login.
2. Settings do not contain any relevant info (path, or log)
3. Are you sure the log is still empty even after running 1T? It should at least say tagging started.
4. What is your path? Maybe you're trying to tag a massive folder?
5. Do you have enough space on the C: drive?

Thank you

**Comment by DJboutit** [comment]
Yes log file is still empty
Path is F:  more than 500gb available 

When I click the Green button in the lower right the progress bar stays at 0%

**Comment by Marekkon5** [comment]
Is it just "F:"? If that's the case then maybe 1T is trying to scan too many folders before starting. Try using some smaller folder with only few tracks at first.
And "C:" is a bit more important to have space on because it writes the log file.

**Comment by DJboutit** [comment]
The folder I am using only has 24 tracks in it it on the F: drive

**Comment by Marekkon5** [comment]
That is extremely weird, maybe 1T is detecting some hidden files. Try moving those few files to a subfolder or maybe even different drive to see if it helps.

**Comment by bascurtiz** [comment]
@DJboutit 
FWIW I tried to mimick your settings/input:
https://youtu.be/3ZGBqT84EHQ

**Comment by DJboutit** [comment]
I finally got One Tagger to work what I did was I tested with one FLAC tracks with more than just album cover I set 5 or 6 tags to update it update the metadata for the track.  Then I just set it to update only album covers with OGG I did two different runs and it worked.  Looks like I am good to go now hopefully weird how I got it to work.
