### ISSUE TITLE
Language Comment Field

### ISSUE THREAD

**Issue by wfarrr** [Marekkon5/onetagger#227]
Have found that when I save tags into custom field it has "xxx" included in the language comment field. I think this is causing errors in iTunes and some other software as it doesn't read this field. Is there a way to stop this happening?
<img width="649" alt="Screenshot 2023-05-29 at 15 31 34" src="https://github.com/Marekkon5/onetagger/assets/133810845/9c1f7788-ad8d-4417-8236-a928ebb17bb6">

**Comment by Marekkon5** [comment]
According to the ID3 standard the language field has to be present. I do believe we use xxx because of Windows Explorer requiring it.

**Comment by wfarrr** [comment]
Do you know if there is a way to bulk remove this from the tags?

**Comment by Marekkon5** [comment]
You cannot remove it, only change to something else. Maybe mp3tag will help.

**Comment by wfarrr** [comment]
iTunes reads it correctly when the language is 'eng' is it maybe a future suggestion to have OneTagger set this

**Comment by Marekkon5** [comment]
Hello, added in latest commit for both AT and QT. You can get the build from the Actions tab. Feel free to comment or reopen if you have more issues. Thanks

**Comment by andreapavoni** [comment]
@Marekkon5 I can see from the sources that the default comment field is still filled with `xxx`, why not default to `Eng` so that, at least, it's more recognized by other players by default?

thanks in advance

**Comment by Marekkon5** [comment]
@andreapavoni we used xxx because it was displaying properly in Windows.

**Comment by andreapavoni** [comment]
first of all, thanks for the quick reply :-)

any chance to set `xxx` only on windows? or maybe having some place where to set its default? I only tried it on Apple Music (aka iTunes) and Rekordbox on mac.

I'm not an expert in cross-compiling Rust for other non-linux/mac platforms, but using `features` should help in doing this.

Being a massive tagger, when I run OneTagger on my collection, each song comment is changed into `xxx` making the field unreadable. I have to go one-by-one and change it properly, it's really annoying, considering that the COMM field is one of the most used to add custom informations to tracks.

**Comment by Marekkon5** [comment]
I mean sure, I can change the default, however it's just a default option, so at this point you've already changed it too, so I don't see what's the gain? + @bascurtiz did all the testing and research, so `xxx` was decision by him for most compatibility.

**Comment by Marekkon5** [comment]
Added in latest commit, however it's really just the default value, so if you've set custom COMM language in AT/QT whatever it won't change anything.

**Comment by andreapavoni** [comment]
thanks for the commit!

> however it's just a default option, so at this point you've already changed it too, so I don't see what's the gain?

I don't have many troubles in retagging again, I only have ~400 songs as of now, I can retag them from scratch until I don't find a decent, repeatable/predictable workflow.

My point is: I usually need to do this tagging once per 1-2 weeks with a bunch of new tracks added to my collection (10-50 new tracks). Sure, I can do it manually once for all the collection, but the next ones will have the same problem.

I don't know how many DJs are using OneTagger (but I'm sure many would love to use it if it really helps cutting times), but this is a sort of repetitive/annoying task.

> @bascurtiz did all the testing and research, so xxx was decision by him for most compatibility.

I'm sure they did a wider/deeper research and testing than me about compatibility. I'm also aware there are many music players which can read whatever COMM language (including the `xxx` one). What I can say is that I'm not the only DJ using iTunes+Rekordbox to organize the music collection: making (dynamic) playlists (bpm, genere, COMM contents) on the former, importing on the latter.


Anyway, thanks for this fix!
