### ISSUE TITLE
OneTagger Audio Tagging stops at 8% 

### ISSUE THREAD

**Issue by leandroxape** [Marekkon5/onetagger#229]
Hi

when Auto Tagging, OneTagger just kept "freezing" at 8%. I then delete and reinstalled ii. It worked, except for for WAV-format. After 20 attempts with WAV it finally initiated the Auto Tagging again. However, it started freezing again at 8%.

What can I do to solve that problem=

Many thanks in advance and friendly regards,
Leo

**Comment by Marekkon5** [comment]
Hello, could you send the log? Settings > Open data folder > onetagger.log

**Comment by leandroxape** [comment]
Hi, problem solved! It was an issue with my files!
