### ISSUE TITLE
DIfference between Failed and Skipped

### ISSUE THREAD

**Issue by B1zguy** [Marekkon5/onetagger#23]
I'm trying to understand the numbers when Auto Tag finishes. It seems that the same files being recounted everytime it has failed/is skipped. Most importantly what do these status' mean and what is happening under the hood?

Thanks in advance.

**Comment by bascurtiz** [comment]
Hover over the big colored icons on top, for more info.

I agree the amount can be a bit confusing, but it's a total amount. 
Example: 
It fails to find the track on Beatport, counts for 1. 
It fails to find the track on Traxsource, counts for 2. 
It fails to find the track on Juno Download, are u counting with me? 
It does find the track on Discogs, match count 1.

So in total it failed 3 times, and matched 1 time. Hope it makes more sense now.


https://user-images.githubusercontent.com/34075088/125156265-e8952600-e164-11eb-8c56-a61c9f096256.mp4

**Comment by Marekkon5** [comment]
In the latest commit this should be less confusing:
Matched = successful
Failed = how many tracks actually failed
Skipped = tags that do not have metadata / are invalid.

You can get it from the Actions tab. Thank you.
