### ISSUE TITLE
Using an external player

### ISSUE THREAD

**Issue by bmac6996** [Marekkon5/onetagger#231]
More of a feature request:

I understand your built-in player cannot play every type of problematic mp3/mp4 music/video file.  Maybe provide an option to use your OS's associated external player when you hit play, stop, FF, RW buttons?

Thanks for your hard work!

**Comment by Marekkon5** [comment]
Hello, that would be possible, however 1T wouldn't be able to control the playback anymore, therefore making it more clunky to use. Is this what you meant or you have more ideas? Thank you.

**Comment by bmac6996** [comment]
That would make sense that you don't have control anymore from within the APP.  

But yeah, thats what I meant.  Have it open to an external player instead.

**Comment by Marekkon5** [comment]
Added in latest commit. You can get the build from Actions tab to try it out. Feel free to comment or reopen if you have any more issues. Thanks

**Comment by bmac6996** [comment]
Just tried it out.. Work as intended.  When you hit space bar, the song opens up to the OS default music player.

Now when I ALT-TAB back to Onetagger, I was expecting to be able to move up/down and/or start adding and editing the tags i need.  I have to physically use my mouse to click into the part of the window with all the tracks in order to make that the active window.  My question is, what is the active window after hitting space bar to turn on external player, then ALT tab back to Onetagger?  If it's not the main window, can the main window be the default after activating the new external player to open?

(just tried a different way, when using my mouse to click on play and it plays on external player, but it's 50/50 if Onetagger and the main window is the active window to continue moving up and down the list and tagging music)

**Comment by Marekkon5** [comment]
OneTagger has just one window, however what you're describing is probably caused because it's technically a webbrowser window. You can try using Chrome / Firefox or any other browser directly which might solve this (http://127.0.0.1:36913 when 1T is running). However it also might be the behavior of your OS.

**Comment by bmac6996** [comment]
Tried as you suggested and that worked.  Opened it in Chrome and was able to hit spacebar to play the song, while player was opened and never lost focus on chrome and was able to make tag changes.
