### ISSUE TITLE
Feature add or maybe something I dont know how to do

### ISSUE THREAD

**Issue by bmac6996** [Marekkon5/onetagger#233]
Is there a way I can select multiple files in quick tag and I can tag those selected files at the same time? Running into a issue in my work flow where I'm duplicating my work to different cuts of the same song.

Also is there a way to copy and paste the tags to another file?  Either with right clicks or better yet, shortcut keys?

Thanks in advance.

**Comment by Marekkon5** [comment]
Hello, neither are possible as of now, there has been few issues open related to this already, however it requires a larger rewrite so it's not been done yet.

**Comment by bmac6996** [comment]
Understood.  I appreciate the explanation and I hope a rewrite is in the near future.  Thanks again.
