### ISSUE TITLE
Tag songs with the Explicit Flag

### ISSUE THREAD

**Issue by DJ-Satanica** [Marekkon5/onetagger#235]
Deezer and Spotify provide explicit track metadata and use the 🅴 symbol to tag such tracks. While DJs are no longer able to stream music from Spotify for performances, Deezer allows it. In Virtual DJ, the 'Explicit' text is displayed in the comments field, as shown here: [[image link](https://i.imgur.com/PJtOqSR.png)].

It would be extremely valuable if One Tagger could incorporate a feature to retrieve metadata from Deezer and/or Spotify and automatically add the 🅴 symbol at the end of the song title for explicit tracks. This enhancement would greatly assist DJs in marking their tracks with an 🅴xplicit warning when performing for general audiences. Additionally, it would help avoid offending sensitive ears, including children and older listeners.

By appending the 🅴 symbol to the song title, DJs would easily identify explicit tracks in their collection without the need to check the comments field. During searches, the clean versions would appear adjacent to the explicit versions, providing a clear distinction.

Could you kindly consider adding this feature to One Tagger? It would greatly streamline the process of identifying and marking explicit tracks, improving the efficiency and convenience for DJs who prioritize audience appropriateness.

We are in your debt.

**Comment by Marekkon5** [comment]
Hello, OneTagger relies on title and artist tags to identify songs. So adding 🅴 symbol to it would make the tracks unsearchable in 1T, and most likely also broken in some other apps. OneTagger also does not have a way to bulk change tags (other than QuickTag, but it's not useful in this case), so I'd recommend you use mp3tag or similar tool to accomplish this, however I'd not recommend doing it because of the aforementioned reason. The most you can do in 1T is to add the `🅴` symbol in the renamer tab, however that only changes the filename, not the tags.

I hope you understand, feel free to comment or reopen if you have any more issues or suggestions. Thank you

**Comment by DJ-Satanica** [comment]
I see, you need to preserve the artist and title fields - so it remains
searchable to any databases that 1T scrapes, then perhaps writing to the
comments field, like Deezer does, is possible?
I hoped I could rescan my library and add  🅴 symbols, just like we add
SPOTIFY "AudioFeatures"  like the very useful 'energy high' tag. I can't
think of any other way to automate marking them.
Thank you for your consideration and thoughtful explanations!

**Comment by Marekkon5** [comment]
We can consider adding the explicit tag, however it won't really be accurate. 1T picks whatever track has the highest match, and in platforms like Deezer, some songs have exactly same metadata but one is explicit and other one not. So it might seem to pick randomly. 1T can't really tell if your song is explicit or not, and therefore won't be able to accurately select the proper explicitness.

**Comment by DJ-Satanica** [comment]
I understand 1T itself can't tell if a track is Explicit, it can only report that Deezer or Spotify says it is and marked a track with the Explicit flag,  rating that was (required to be) added by the producer, or one of their music curators listened to it and marked it. Hopefully they know what they are doing. It is understood some or many tracks will slip through the cracks, a false negative result -  but tracks marked Explicit are highly probable to be correctly marked.  Thank you for your time!

**Comment by DJ-Satanica** [comment]
Thank you for tackling the issue and getting it done so quickly!  I am
testing it now, using MP3's and MP4's by fetching the %ITUNESADVISORY% tag
that reports 1 for Clean and 2 for Explicit.  That should get me good
results. Thanks for the hard work.

**Comment by DJ-Satanica** [comment]
whoops..  1 is the Explicit, my bad!
