### ISSUE TITLE
Tags won't write on .m4a files

### ISSUE THREAD

**Issue by Waffled-II** [Marekkon5/onetagger#236]
Recently got a CD and wanted to copy the tags with Shazam. The problem is that it finishes instantly with no fails and no matches, only the total number is shown. When I converted them to MP3 however it seemed to work. The file format these songs are in is m4a (ALAC) and there are 12 songs total.
Here's the log: 
[onetagger1.log](https://github.com/Marekkon5/onetagger/files/11928711/onetagger1.log)

**Comment by Marekkon5** [comment]
Hello, should be fixed in latest commit. You can get the binary from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues. Thank you
