### ISSUE TITLE
Capitalise Spotify Genres

### ISSUE THREAD

**Issue by KingWizard1** [Marekkon5/onetagger#237]
Hey team,

First off, excellent software. Really brilliant, thank you so much.

How feasible is it to have genre's returned from Spotify's API to be capitalised? As can be seen below, and in DJ software as well, the tracks that had their genre's tagged from Spotify are all lower-case, whereas others from other sources are proper-cased.

Obviously there will be edge case issues with abbreviations like "atl" (for "Atlanta") being converted to "Atl" as a result, instead of the correct "ATL", but I can forego those as they're much harder to capture and correct 😄 

![image](https://github.com/Marekkon5/onetagger/assets/47585882/fdc9cf1b-f3f4-4844-a3a3-806ef6f1d439)

Thanks folks!

**Comment by Marekkon5** [comment]
Hello, the feature is available in the latest unreleased build. You can get it from the Actions tab. Feel free to comment or reopen if you have more issues.
