### ISSUE TITLE
Move Comment to Tag in Rekordbox

### ISSUE THREAD

**Issue by leandroxape** [Marekkon5/onetagger#238]
Hi, I have a question regarding the quick tag function: How can I (easily) move the information stored in the comment section the tag section in Rekordbox (I know it is possible the other way around when tagging within Rekordbox)?

Thanks in advance!

**Comment by bascurtiz** [comment]
You could ask on the rekordbox forum, but afaik, there is no way to put Comments into Rekordbox' My Tag.
Here you see I tagged it inside Rekordbox as a My Tag with 'Acid House', but it's not written as metadata inside the file.
Rekordbox' My Tag are actually written to their internal db.

![image](https://github.com/Marekkon5/onetagger/assets/34075088/4e6a2a9b-d053-41f6-b9e8-cec47e58fe0e)

**Comment by epper** [comment]
I think it should be possible to have the tags added by One Tagger become imported as "My Tag" in rekordbox.

This should allow tags to be filtered live in CDJs given that tags in the comments section [don't seem to be searchable](https://forums.pioneerdj.com/hc/en-us/community/posts/207476386-How-do-you-keyword-search-comments-field-on-CDJ-2000NXS2).
(I can't test as I don't have a CDJ but I think that's may be the main benefit)

How could this be done?
It seems it's just about writing the tags in the comment field in a specific format:
- Here it explains how "My tags" can be [imported in rekordbox from the comment field](https://www.lexicondj.com/guide/rstoring-your-rekordbox-my-tags-from-the-comment-field)
- And here it explains how [tags in the comment field need to be formatted for rekordbox to import/export them](https://forums.pioneerdj.com/hc/en-us/community/posts/900001887546-How-does-Add-My-Tag-to-the-comments-exactly-work-and-how-does-it-deal-with-comments-that-were-there-before)
