### ISSUE TITLE
Auto Rename issue

### ISSUE THREAD

**Issue by nmycps** [Marekkon5/onetagger#239]
When I change the input folder path, the preview doesn't update automatically to reflect the new filenames, and the preview still shows the file names from the last time. So I have to enter the template field, make a small change, such as press the spacebar and then backspace, then the preview updates to the new content in the path.

**Comment by Marekkon5** [comment]
Hello, sorry for the delay, should be fixed in the latest commit. You can get the binary from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues.
