### ISSUE TITLE
Support for automatic detection of tags inside the filename

### ISSUE THREAD

**Issue by flocked** [Marekkon5/onetagger#24]
Currently the user has to predefine the filenama structure to use it as tag. An option to detect tags automatically would be great.

Here are regex definitions for parsing.

1. Get track number if available:
`(\w\d+|d+)\s*[-|_|.|+]?\s*`
Remove the parsed track number from the string

2. Get Artist and Title
`^(.*?)\s?[-|_|+]\s?(.*?)$`

-------
These regix support parsing tags with many filename variations: 

- "01. Artist - Title"
- "B1-ArtistTitle"
- "02_Artist_Title"
- "02 - Artist - Title"
- "Artist+Title"

**Comment by Marekkon5** [comment]
The feature is already there in Auto Tagger as "Parse metadata from filename". It uses templates like `%title% - %artists%` however those get converted to regex internally.
