### ISSUE TITLE
They have just updated the beatport page and it is not displaying the tracks.

### ISSUE THREAD

**Issue by marioserinal** [Marekkon5/onetagger#240]
![image](https://github.com/Marekkon5/onetagger/assets/105318129/04bf930e-5470-45ba-89f5-85dd3ed6932d)
Look

**Comment by marioserinal** [comment]
No problem, I look forward to the update

**Comment by eshy** [comment]
From a quick look, it seems they switched to NextJS and all of the data is in a script node for client side hydration with no server side rendering

**Comment by Marekkon5** [comment]
Thanks for the info, I just hope they didn't add Cloudflare or some sort of protection that would make it unuseable in 1T. Feel free to make PR or implement custom platform for it, as I said I am unable to do so for the next 2 weeks. Thanks

**Comment by marioserinal** [comment]
At the moment it seems that the site is working better than before and that they only changed the API.

**Comment by jberginc** [comment]
I've moved on to Yate. It's a pretty good replacement.

**Comment by maksalonica** [comment]
> At the moment it seems that the site is working better than before and that they only changed the API.

Okay. I hope it will work again! 

Any options to donate about your work?

**Comment by jberginc** [comment]
> 

It is only for Mac. I didn't see a Windows option.

And yes, Marekkon5, (it is rude to block replies!) its Beatport integration is working perfectly with no sign of complaints on its forum. In fact, I prefer to do my files one by one for more accuracy. 
I like OneTagger because it offers more tagging sources and has been the backbone of my workflow for a few years now. But I would definitely like to confirm the changes instead of blindly trusting the batch process. Who knows how many songs I have mislabeled in my collection??

**Comment by Marekkon5** [comment]
@jberginc I did not block any replies. I only said I will fix it as soon as I am able to, and closed the other issue due to being duplicate.

**Comment by Marekkon5** [comment]
Should be fixed in latest commit, to test it out download the latest binary from the Actions tab. If everything will work, we will most likely push new update for everyone, since Beatport seems important/popular. Feel free to comment or reopen if there's more issues. Thanks

**Comment by jberginc** [comment]
I can't figure out how to download and try the latest binary from the Actions tab. I guess I'll wait until it hits the main page.

**Comment by bascurtiz** [comment]
@jberginc 
In order to try the latest binary from the actions tab, see: 
https://user-images.githubusercontent.com/34075088/239883920-b3578e83-2733-4f0d-9e43-fe422c186697.mp4

**Comment by jberginc** [comment]
> @jberginc In order to try the latest binary from the actions tab, see: https://user-images.githubusercontent.com/34075088/239883920-b3578e83-2733-4f0d-9e43-fe422c186697.mp4

Aha! My screen got stuck while scrolling.

**Comment by jberginc** [comment]
OMG! It's working! Thank you!
