### ISSUE TITLE
autorename doesnt fill bpm

### ISSUE THREAD

**Issue by neurall** [Marekkon5/onetagger#241]
Apr 15
@[Marekkon5](https://github.com/Marekkon5) Marekkon5
[ 1.6.0](https://github.com/Marekkon5/onetagger/tree/1.6.0)
https://github.com/Marekkon5/onetagger/commit/429b0e82f0fe0bae07c1ec5b8f1cef7a418e4550
%genre% - %key% - %bpm% - %title% - %artist%
leads to empty spaces in all my m4a files all having bpm and recognized in dj sw vdj or recordbox. 
example: circuit - 4A -  - Take That Feeling - Pagano.m4a
the same happening in autotag

**Comment by Marekkon5** [comment]
I am currently away, will fix in 2 weeks. Sorry for the inconvenience

**Comment by Marekkon5** [comment]
Hello, should be fixed in the latest commit. You can get the binary from the actions tab to test it out. Thank you.
