### ISSUE TITLE
Beatport Fail

### ISSUE THREAD

**Issue by Foons** [Marekkon5/onetagger#243]
Hello Marekkon, greetings from Spain.

I have seen in the workflows that you are with the Beatport error, I don't know if it will be the same one that I have.

A few days ago Beatport.com has changed the page, in my opinion to dynamic in the search engine, it may be the result of a bug in all the versions I have tried of One Tagger. I have tried the versions: 1.6.0, 1.5.1, 1.5.0 and 1.4.0 with the same result: not found.

I have done tests with mp3 already updated with the program and it does not recognize them.

Is this a general problem or does it just happen to me?

My setup in case it helps:

- Select Platform: only Beatport.

- Select Tags:
Album Art , Album Artist , Artist , Title , Version , Remixers , Genre , Style/Subgenre , Label , release Id , Track ID , BPM , Key , ISRC , Publish Date , Release Date , Other.

- Album art resolution: 500 , Max pages: 1

- Advanced:
Overwrite tags, ID v2.4, Short title, Camelot key notation, track or Release ID, Include subfolders.

- Multiple matches ordering: Default

- Strictness: 100%

- Search Threads: 18

- Match duration: active

- Max difference: 1s

I have changed the values ​​of match duration and max difference to test but it doesn't work either.

I would be very grateful if you tell me something when you can.

Thank you so much.

**Comment by Marekkon5** [comment]
Hello, Beatport updated their page and that broke all old 1T versions. I've already updated 1T to support the new changes, and you can get the binary from the Actions tab to test it out, or you can wait few days until we release 1.7.0. Thank you.

**Comment by Marekkon5** [comment]
Feel free to comment / reopen if it doesn't solve your issue.

**Comment by Foons** [comment]
https://github.com/Marekkon5/onetagger/actions/runs/5635898683 , see it. Thanks

**Comment by Marekkon5** [comment]
That is 3 days old, there has been some fixes related to this. Always use latest build. https://github.com/Marekkon5/onetagger/actions/runs/5657580811
