### ISSUE TITLE
BEATPORT automatic tagging does not work

### ISSUE THREAD

**Issue by DrumskiDJ** [Marekkon5/onetagger#244]
Hello, i just want to report that Beatport does not work for me when I select it as a platform for automatic tagging of mp3 songs.
This was perfectly working before and now all that is doing is scrolling trough folder not matching any song. Any chance for this to
be fixed?

**Comment by Marekkon5** [comment]
Hello, Beatport updated their site. It is already fixed in 1T, you can get the latest build from Actions tab to test it out. We will also release a full version in few days. Feel free to comment or reopen if you have more issues. Thanks

**Comment by DrumskiDJ** [comment]
Thank you but where do I find ACTIONS tab? In OneTagger or somwhere else?

**Comment by DrumskiDJ** [comment]
Nevermind, I found it. Its on this website :) Thanks I already downloaded 1.70 version now...testing it.
