### ISSUE TITLE
Unable to Match Songs to Beatport when Beatport includes (Extended Mix) in the Title

### ISSUE THREAD

**Issue by drsgfdds** [Marekkon5/onetagger#245]
I have a number of tracks that I am trying to label by Genre.  Beatport frequently only has one version of the song (ie the Extended Mix or the Original Mix) and many of my songs simply have the Title without specifying which mix (both in the filename and in the ID3 tags.

Some of my songs are the same version as the Beatport track (ie both are Extended Mixes, but mine is missing the Extended Mix title) and other times my song is actually an Original Mix, while the version on Beatport is an Extended Mix.

Either way, since I am simply trying to tag the Genre, I am not concerned, if 1T matches to a slightly different version of the song.

Is there any way to include Extended Mix in the search? Or use the regex to force it to search for "%title%" OR "%title% (Extended Mix)" ?

Currently Autotag throws an error for these tracks saying, "No match."  When I dial down the Strictness, Autotag matches to a completely unrelated track, even though typing artist+title into the Beatport search, returns results with the Extended Mix version of the song as the #1 top result.

Like I said, I am just trying to tag genre right now.  I do understand that an Extended Mix may technically be a different track, however, I would really appreciate a mechanism to scrape data from this version of the track when Beatport has their track either labelled differently or they don't have the exact same version I have - instead of being matched with a completely different, unrelated song.

Thanks in advance!

**Comment by Marekkon5** [comment]
Hello, added it in latest commit as a Beatport specific setting. It will ignore the version when matching against your tracks. You can get the binary from the Actions tab to test it out. Feel free to comment or reopen if you have any more issues. Thanks
