### ISSUE TITLE
Audiobooks

### ISSUE THREAD

**Issue by L0garithmic** [Marekkon5/onetagger#249]
Allow us to tag audiobooks using Audible as a tag source?

**Comment by Marekkon5** [comment]
We have no idea what metadata do audio books have. Do they have title + artist? Is there any point in doing that?

**Comment by L0garithmic** [comment]
Audiobooks are super simple. Just like music, all the same tags. Just for M4A, M4B and MP3 tags and usually use ID3.

Artist is the author
Title is the book name.
Album is the book name
Year is the year released
Composer is the Narrator.

MP3Tag has some third party audible search sources that work good. I just thought your software looked and worked nicer!
Also, since it's called ONE tagger, it seemed like it would be the ideal platform to implement audio-books AND music!

MP3 Tag Audible source I use
https://pastebin.com/raw/4fj2h9Vq
