### ISSUE TITLE
Auto Rename empty output folder

### ISSUE THREAD

**Issue by trinsky** [Marekkon5/onetagger#250]
Hi! first of all congratulations for your app! it is amazing!
I have had an issue when using Auto Rename. The first time I run it I only inputed source folder and leaved empty the output folder.
It worked perfectly!
Then I used the output folder variable to rename the files to another folder. This also worked, but when I then try to leave empty the target folder again the program fails due to it tries to rename to C folder (without the path)

I realised that in settings.json file, the variable outdir gets defined as "outDir": "" and then the program is trying to move to C: folder which end in (os error 5) access denied.
<img width="368" alt="image" src="https://github.com/Marekkon5/onetagger/assets/141788349/d1ddc8d8-17cc-40d4-8da8-ffebf7b4fb52">

I solved it by moving the outdir after path is defined as "outDir" : path >> then it works again.

Hope this helps you and thanks again for your work!

**Comment by trinsky** [comment]
Also, in case of adding subfolders the program does not mantain the subfolder structure.
I have one folder with Artist/Disc1 and another with Artist/Disc2.
I want to rename the files in Artist folder (and subfolders) but that they are mantained in their subfolders (not moved to Artist folder.

**Comment by Marekkon5** [comment]
Hello, what is your goal with the empty output folder? You should always let it be filled (ie. browse to the dir of 1T if you wanna same output folder as none). As for the subfolder structure: You need to make the template match the folder structure you want (for example: `%artist%/%discnumber%/%title%`) . Perhaps send your template and the intended folder structure so I can help with that. Thank you.

**Comment by trinsky** [comment]
I have all music in a folder named MUSIC. There I have one folder for each album already. I want to rename the files inside each subfolder without moving them.
<img width="640" alt="image" src="https://github.com/Marekkon5/onetagger/assets/141788349/d15844f9-9a2b-4631-901d-093973228694">
If I do it like this, all files from the subfolders are moved to the main folder "MUSICA". The subfolder structure is not mantained. I know that I could use %artist% - %album% / %title%, but some times the album is not correctly retrieved in some songs and it makes a mess (with remixes or similar songs, shazam fails some times - Are you just sending to shazam the first X seconds of the song? Maybe you could try with a pair of comparisons sending the beggining and some seconds in the middle of the song)
Hope I explained the case. Just try to say that if the output folder is empty, it should not move any file from the subfolders, but rename them in the same place they are.
And also the issue that I told, If I paste a output folder first - execute (it works) when I try to leavy the output folder "empty" again, the system fails as it tries to move without any path. This is trying to move the file to "C:\Program Files (x86)\OneTagger".
2023-08-09 00:15:51 [ERROR] onetagger_renamer: Failed copying C:\Users\len\OneDrive\MUSICA\Funambulista - Animal\Bienvenido.mp3 -> "Funambulista - Bienvenido.mp3": Acceso denegado. (os error 5).

Hope this helps you! And congrats again for you app.

**Comment by Marekkon5** [comment]
Hello, I've fixed the empty output folder issue, and added a new option `Keep original subfolders`, which should solve your other issue. You can test it out by downloading a build from the Actions tab. Feel free to comment or reopen if you have any more issues. Thank you
