### ISSUE TITLE
Missing webkit2gtk

### ISSUE THREAD

**Issue by fwn0** [Marekkon5/onetagger#252]
onetagger: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
How can I add webkit2gtk with all deps to your go binary ?

**Comment by Marekkon5** [comment]
Hello, statically linking webkit2gtk is probably a bad idea and most likely isn't a fun way to spend the afternoon. You should just install `libwebkit2gtk-4.1-dev` as dependency on your machine (using apt or whatever package manager you use).

**Comment by fwn0** [comment]
Yes, with installing of libwebkit2gtk runs onetagger perfect, but I'd like get the independent portable binary. I see here in the topic (  https://bugs.webkit.org/show_bug.cgi?id=181695 ), that it's not easy and very complicated to build static webkit2gtk.

**Comment by Marekkon5** [comment]
Yes, that's what I said. You can try yourself, or perhaps try the easier way of using AppImage or zipping the .so files alongside the binary. I won't officially support this and probably close this issue, because I don't see any advantages or purpose in doing this, however feel free to comment or reopen if you have more questions.
BTW: -cli version doesnt depend on any system libraries.

**Comment by Marekkon5** [comment]
@fwn0 Just a note if you're actually going to try this: consider building for -musl target and using Alpine linux (container), since those are intended for building fully static binaries.

**Comment by SimonDedman** [comment]
Hi @Marekkon5 sorry to necromance but I have this issue on a fresh xubuntu 24.10 build and can't solve it. From the appimage:

`./onetagger`

> error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

`sudo apt install libwebkit2gtk-4.1-dev`

> libwebkit2gtk-4.1-dev is already the newest version (2.46.5-0ubuntu0.24.10.1).

`find` says I have the same file thrice in snaps:

```
/snap/gnome-42-2204/202/usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so
/snap/gnome-42-2204/176/usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so
/snap/gnome-3-38-2004/143/usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so
```

Should I set `LD_LIBRARY_PATH` to `/snap/` or something similar?

I spent ages trawling through posts like [this](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s), and have been trying to install node.js with no success (standalone binary readme links to compile/build instructions which aren't present), so have also stalled on compiling from source.

Cheers!

**Comment by Marekkon5** [comment]
@SimonDedman there has been a related issue recently and the solution was to try latest Actions build.


Optionally you can try building from source or symlinking the libraries.

**Comment by SimonDedman** [comment]
Ah, you beauty, that worked a treat. Thanks mate!

**Comment by Marekkon5** [comment]
Yes, those warnings/errors are generated most likely by GTK / not by 1T, if it works, can be ignored.
