### ISSUE TITLE
Audio Features not placing tags

### ISSUE THREAD

**Issue by rossyp87** [Marekkon5/onetagger#254]
When I run audio features it says the tracks are being matched successfully but nothing is actually being tagged to the files?

here are my settings, I want them all in the comments tag.

![screen](https://github.com/Marekkon5/onetagger/assets/142145663/375adf57-a8ca-4dfc-8163-1f3152b82076)

**Comment by Marekkon5** [comment]
Hello, could you give example title - artists of your tracks? Perhaps the danceability, energy and valence values are out of range (grey area). Thank you

**Comment by rossyp87** [comment]
it seems to happen with most of my tracks (I have over 5000), I have previously tagged the energy before only using the numbers rather than a written value which seemed to have worked, but ever since doing that, when i try to re tag it, it doesn't. its just blank. does the grey area not tag the values in the medium range?

**Comment by rossyp87** [comment]
I played around a bit and have figured out the problem. I went into MP3tag and deleted all the comments tag fields on my tracks. After that I went back into Audio Features and it is now tagging in the comments section field, I had "Skip already tagged tracks" turned off, so i am not sure why it wasn't tagging.

**Comment by Marekkon5** [comment]
What are your advanced audio features settings? Perhaps the tags don't get updated/overwritten if you have "Skip already tagged tracks". Also could you provide few title - artist names so we can manually test? Thank you

**Comment by Marekkon5** [comment]
Oh my bad, didn't see that reply, feel free to comment or reopen if you have more issues.

**Comment by rossyp87** [comment]
sure i was testing with "1-800 GIRLS - Primary Thoughts" and "Anthony Naples - OTT"

my advanced settings were
Write OneTagger Meta Tag = True
Skip Already Tagged Tracks = False
Include Subfolders = True

Yeah its tagging fine now, I just need to clear my comments tags if I want to retag the Audio Features. Thanks so much anyway, loving everything that you do!
