### ISSUE TITLE
No issue - just a note to say this is f***ing brilliant!!

### ISSUE THREAD

**Issue by electric-monk-2000** [Marekkon5/onetagger#258]
Seriously ...  I had been searching for a way to efficiently re-tag an entire digital DJ library built over 20+ years and Onetagger is quite literally the answer to my dreams.   I also use Metadatics and /or MP3Tag - which have their uses for other aspects of metadata management, but for easily organising a DJ library in a way that can work seamlessly between Denon DJ/Engine, Rekordbox and other formats - this is priceless.   The auto-tagging from the internet is a nice touch, but not for me the core function since I want my own tag system rather than rely on online sources.  Quicktags is perfect for that.  And the linked Google sheets guides to what tags work with each DJ software format is also incredibly useful.

THANK YOU!

**Comment by bascurtiz** [comment]
Thanks - Glad you like it!

**Comment by Marekkon5** [comment]
Glad you like it! Feel free to open issues if you have any problems or suggestions.

**Comment by RDeluxe** [comment]
Just chiming in to confirm: thanks for one-tagger, and your effort. I know very well how hard it is to create something new (product vision, features management, community management, UX and the development itself) and I think you are killing it.

I don't use one-tagger for djing especially (though I hope to try to DJ soon), but simply to tag + rename my files to fit in my audio library, which is quite diverse (a lot of electronic music, but only 50%), and one-tagger does a wonderful job.

There are a lot of music afficionnados out there who are going to love one-tagger, outside the techno/dj scene.

Keep up the good work. I sadly know nothing about rust, but I started checking the repo a bit, so thanks for that learning opportunity too.
