### ISSUE TITLE
Bug Report: Blocking recursive search not interruptible for Quick Tag; no filter for file types?

### ISSUE THREAD

**Issue by eejd** [Marekkon5/onetagger#259]
Hi, everyone and especially @Marekkon5 and @bascurtiz. I want to start my first submission by saying that One Tagger has been an amazing find and is an excellent project and application. I hope to start contributing towards bug fixes and improvements. I was searching for something like this for years. I have a number of feature requests and ideas for contributions, but I am still in the process of gaining experience with the app and developing and testing different workflows to understand how best to use 1T and areas for potential contribution. That said, here is the first simple bug report. (Please let me know if you have guidelines for reporting, etc.)

Summary:
Scanning for audio files (and/or m3u files) is very slow if you select a directory with a lot of child directories and there is no way to interrupt the scan.

Platform: MacOS 12.6.6, Apple Silicon
1T version: Git  [b902044], forked and configured for local M1 compilation testing

Bug:
When you have 'Include Subdirectories' selected change the directory in the Quick Tag source, unless the directory has a low file/inode count and no sub directories, scanning takes a long, long time and there is no way to cancel except killing the 1T process. I experienced this when realizing that success and failure m3u playlists do not correctly list most recently processed files if you have 'multiple platforms' selected. It seems to represent only the most recent platform used. [see [261](https://github.com/Marekkon5/onetagger/issues/261) bug report on this issue and [260](https://github.com/Marekkon5/onetagger/issues/260) feature request]. Specifically, if I select any folder on my system to navigate (i.e. a root level folder, a mount directory) that has a large sub directory or file count space, 1T then seems to scan for every audio file and/or m3u file and therefor navigating by setting the directory field is impossible. That is, entering a starting folder and then navigating via the browser below. Further, I could find no way to interrupt the scan short of killing the 1T process itself.

Possibly fixes:
1. Use a file system dialog to allow navigation directly to a location. This would at least prevent accidental scans of the entire drive if you, for example, enter the root of the drive.
2. Allow for interruption of the process. Use a thread to queue the audio file/tag browser so that the main UI thread can cancel, change dir, etc.
3. First filter by file type (xattr/ext/etc) to allow fast browsing, then populate the Quick Tag window from a separate queue process that is in a separate thread so that the display of files in the side browser is independent of loading the files into the audio file/tag browser. This could then allow a queue clear and restart if you navigate to another directory from the side panel.

**Comment by Marekkon5** [comment]
Hello, thank you for the reports.

1. You can press the like path (see image) to open native file dialog.
![image](https://github.com/Marekkon5/onetagger/assets/15169286/29ab1a4a-2df9-496d-8883-16e77ee81020)

as for 2 / 3 ill try to optimize / add interrupting.

**Comment by Marekkon5** [comment]
Hello, cancelling is quite a bit complicated in current 1T and lazy loading is also complicated because to sort the files you have to get metadata of them all (so we can't load periodically, unless we keep some internal DB, however then it might get out of sync with the actual tracks, and the whole point of 1T is to write metadata directly and not have some internal DB). Anyway the loading is now capped to 500 tracks by default (which should be relatively fast) and once you select your folder you can click to load them all. 
And as I said you can use native browser by clicking the path or by clicking the icon in settings. 
You can get the build from Actions tab to test it out.

I do believe this is a enough solution for now, feel free to comment or reopen if you don't think so. Thanks
