### ISSUE TITLE
iTunes + Spotify API & some other suggestions

### ISSUE THREAD

**Issue by aleixjf** [Marekkon5/onetagger#26]
Hello and congratulations for your amazing work!

Inspired by the BeatportTagger project, I started my own tagger earlier this year, because I wanted to create a similar project which would allow me to get metadata from Spotify/AppleMusic (iTunes) too. Unfortunately, I had to focus on other things and stopped the project, but I implemented a few things which could be easily ported to this OneTagger version. I currently don't have time to get involved in this project, but i'll definitively do in the future since I find it a very useful and necessary tool for DJs! Anyway, here are a couple of suggestions:

1. Ability to choose wether to overwrite each specific field/tag.

To overwrite all tags may not always be a feasable option. Imagine you only want to overwrite the Genre Tag but also want to fill the missing release dates. Right now you need to do the process 2 times, which is rather uneffecitve. I can add a screenshot of how I had it done (in terms of UI), but I believe it would be a good approach to let users chose if they want to overwrite all fields, or just some of them.

2. Search engine

I modified the search engine algorithm to have some even better results (haven't checked the current algorithm/code yet):

The idea was to get, on one hand, the "clean" title + (re)mix, and on the other hand, the artist + remixer + featurers, in order to use all this info in a better way, rather than using the Title/Artist in a generic way. To get all that info, I would try to read it from the tags themselves, using regex expressions to get them from the title/artist fields of the local & server files/tracks.

You'll find the functions in the "helper.py" file inside the attached ZIP file. Here's my suggested Search engine, which you'll also be able to find inside the itunes/spotify/beatport.py files.

[API Tagger.zip](https://github.com/Marekkon5/onetagger/files/6825405/API.Tagger.zip)

```
        # Start match process
        for track in results:
            # Create track object for each result
            track = Track(result)

            # Title match
            if fuzz.ratio(metadata.title, track.title) >= fuzzywuzzy_ratio:
                # Duration match
                if abs(metadata.duration - track.duration) <= timeTolerance:
                    # Artists match
                    if fuzz.ratio(metadata.artists, track.artists) >= fuzzywuzzy_ratio:
                        return track
                    # Main artists + featurers match
                    elif fuzz.token_sort_ratio(', '.join(metadata.mainArtists), ', '.join(track.mainArtists)) >= fuzzywuzzy_ratio and fuzz.token_sort_ratio(', '.join(metadata.featuringArtists), ', '.join(track.featuringArtists)) >= fuzzywuzzy_ratio:
                        return track
                    # Main artists + remixer match
                    elif fuzz.token_sort_ratio(', '.join(metadata.mainArtists), ', '.join(track.mainArtists)) >= fuzzywuzzy_ratio and fuzz.token_sort_ratio(metadata.remixer, track.remixer) >= fuzzywuzzy_ratio:
                        # Duration match
                        if abs(metadata.duration - track.duration) <= timeTolerance:
                            return track
                    else:
                        continue

            # Name match
            elif fuzz.ratio(metadata.name, track.name) >= fuzzywuzzy_ratio:
                # Mix match
                if fuzz.ratio(metadata.mix, track.mix) >= fuzzywuzzy_ratio or (metadata.mix == '' and track.mix == 'Original Mix'):
                    # Duration match
                    if abs(metadata.duration - track.duration) <= timeTolerance:
                        # Artists match
                        if fuzz.ratio(metadata.artists, track.artists) >= fuzzywuzzy_ratio:
                            return track
                        # Main artists + featurers match
                        if fuzz.token_sort_ratio(', '.join(metadata.mainArtists), ', '.join(track.mainArtists)) >= fuzzywuzzy_ratio and fuzz.token_sort_ratio(', '.join(metadata.featuringArtists), ', '.join(track.featuringArtists)) >= fuzzywuzzy_ratio:
                            return track
                        # Main artists + remixer match
                        elif fuzz.token_sort_ratio(', '.join(metadata.mainArtists), ', '.join(track.mainArtists)) >= fuzzywuzzy_ratio and fuzz.token_sort_ratio(metadata.remixer, track.remixer) >= fuzzywuzzy_ratio:
                            return track
                        else:
                            continue

                # Original/API track doesn't have mix info
                elif metadata.mix == '' or track.mix == '':
                    # Duration match
                    if abs(metadata.duration - track.duration) <= timeTolerance:
                        # Artists match
                        if fuzz.ratio(metadata.artists, track.artists) >= fuzzywuzzy_ratio:
                            return track
                        # Main artists + featurers match
                        if fuzz.token_sort_ratio(', '.join(metadata.mainArtists), ', '.join(track.mainArtists)) >= fuzzywuzzy_ratio and fuzz.token_sort_ratio(', '.join(metadata.featuringArtists), ', '.join(track.featuringArtists)) >= fuzzywuzzy_ratio:
                            return track
                        # Main artists + remixer match
                        elif fuzz.token_sort_ratio(', '.join(metadata.mainArtists), ', '.join(track.mainArtists)) >= fuzzywuzzy_ratio and fuzz.token_sort_ratio(metadata.remixer, track.remixer) >= fuzzywuzzy_ratio:
                            return track
                        else:
                            continue
```

3. Explicit Spotify support + iTunes API

I'd love to fetch some data from the Spotify API or the "free" iTunes API (limits the number of request/time, just as discogs I believe). Feel free to check my spotify.py/itunes.py code :)

Finally, in the future, I'd love to see the app using OAuth in order to use properly Beatport's API + other APIs (such as Spotify API/AppleMusic/Tidal or other APIs). And also,  as a Traktor user, I'd love to read and modify the collection.nml to fill the Mix/Remixer field... I believe that this would make the app an even more DJ focused app for tag editing! And using the functions above to extract all that, we could definitively make it work!

**Comment by Marekkon5** [comment]
Hey, thanks for the suggestions, however I have few notes to add there:

1. Actually if the tag is empty the value will be written anyway. The overwrite function applies only if the existing tag has value and you wanna overwrite it. 

2. The search query passed to search engine of platforms is with minimal changes, however the actual track matching algorithm does pretty much all of the stuff you mentioned. It matches just single artist (with fuzziness, fallbacks in case of improper separators) instead of all, and track title is compared (incl. fuzziness) without any special characters, keywords like "edit" and such.  If you want to just check the matching code it's in `src/tagger/mod.rs` on line 525 (the impl contains functions shared across all the platforms). Let me know if you have more detailed suggestions there.

3. Spotify API is actually implemented (incl. OAuth login), but it's only used for Audio Features right now. However I do plan adding it to Auto Tagger too. As for iTunes we'll consider it, I've personally never used their service.

As for the other APIs:
- Beatport API - it has worse search results than their actual website (@bascurtiz tested and compared them), and it isn't really publicaly available, so I don't see any benefits of adding it.
- Spotify - as I said, already there, planned for AT, has proper OAuth, no scrapping
- Apple Music - gotta check
- Tidal - Last time I checked they didn't have public API, only private one. I mean no problem adding it in future, just that there probably isn't any "proper" way to use it.

As for the Traktor collection - gotta discuss with @bascurtiz, never used it. 

Thank you.

**Comment by aleixjf** [comment]
Hi Marekkon, I'm trying, unsuccesfully, to add the iTunes Search API (the free API, not the Apple Music one).
The search requests are limitted to 20/minute aprox...
Here's more info about the API, I'd love to help but Rust isn't my language.. Here's more info about the API, and I'll do a merge request with the few things that are working for you to be able to add it quicker.
https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/

**Comment by Marekkon5** [comment]
Closing since iTunes and Spotify is now avIlable. Thanks for the help
