### ISSUE TITLE
Feature request : specify features by source

### ISSUE THREAD

**Issue by RDeluxe** [Marekkon5/onetagger#270]
Hello there.

I did some tests with One-tagger, re-ordering the sources to get the best match possible and the best tags.

I found that some sources are less reliable than others when it comes to a song Title (e.g. using some Anniversary edition tracklist instead of the original one), but perform well on the "genre", and the opposite (correct track match, but poor genre).

I know that there is an option to fetch the genre from several sources + merge them, but it could be useful to be able to select "fetch the genres" for each source individually. This could also be expanded to other tags.

This comes with UX challenges, although we could re-use the "select tags" component for each source, behind a toggle : 
![CleanShot 2023-08-31 at 14 02 33](https://github.com/Marekkon5/onetagger/assets/2767681/d9dbdb89-e706-4b66-a4fc-9a7f5331a0ce)

I suppose than code-wise, each source is taking an array of tags to fetch anyway?

Regards

**Comment by Marekkon5** [comment]
Hello, sorry, but I don't fully understand what do you mean / what do you want to accomplish? If you want to fetch title / artist from one source, and genres from rest, move the source to top, disable overwrite, and enable merging genres.

**Comment by Grenoybel** [comment]
Hello, RDeluxe wants to be able to choose wish tags to fetch from each preferred source, without having to make the auto tagging search the preferred source for the appropriate tag one by one, it's a nice idea, but like he said probably difficulty to manage with the current UI.

**Comment by Marekkon5** [comment]
It would be very clunky and probably overcomplicated with the UI, and would have to refactor bunch of the config and such as well, however is there an issue with

a) Just running multiple times with different platforms and tags?
b) The overwrite disabled + genre merge + proper order of platforms?

**Comment by RDeluxe** [comment]
Hello, sorry for the late answer.

a) With the CLI, I guess not. With the UI I would argue that it could be a bit cumbersome. Still, it will take longer.
b) Not sure about this one. E.g. if I get the correct title and album from my first source, does the second source uses the new data or not?

**Comment by Marekkon5** [comment]
b) yes it does

**Comment by RDeluxe** [comment]
Alright, so that could work. I guess I was not aware that "genre merge" + disabling overwrite would work !
