### ISSUE TITLE
error "invalid utf-8 sequence of 1 bytes from index 73"

### ISSUE THREAD

**Issue by timokaaa** [Marekkon5/onetagger#272]
Hi,

lately I'm always getting an error "invalid utf-8 sequence of 1 bytes from index 73" when I try to start Auto Tag. I thought it might be because of non-latin characters in the playlist or folder that I want to tag, but there are none.

How can I solve this?

I was using Version 1.6 and just updated to 1.7, but same behaviour.

Thank you so much for your work! I've been using One Tagger for about a year and it's the best thing!

Timoka

**Comment by Marekkon5** [comment]
Hello, could you please send the log? (Settings -> Open data dir -> onetagger.log). Also it is possible that one of your tracks has just bad / non-utf-8 characters.

**Comment by timokaaa** [comment]
Hi, thanks for getting back so quickly! I wanted to re-creat the error with a small folder (that I had tried before) and it worked fine! Then I tried a playlist and the error came up. So it probably is indeed due to characters in a track. However, the error re-appear with any folder/playlist now (also the one that first worked), until I restart the program.

Do you know a way to detect the faulty track?

Thanks again!

PS: Do you still want the log? How can I send it to you privately?

**Comment by timokaaa** [comment]
Ok it seems to be the playlist file (m3u created with foobar) itself, not a specific track. Tried with the same playlist as created by Media Monkey and it works

**Comment by Marekkon5** [comment]
The log should give us more info on how to fix. It shouldn't reveal any info (other than path names) so it is safe to just post here, however if you want to send privately send it to: onetagger (at) mail (dot) com.
You could also attach the playlist so we can fix for future. Thanks
