### ISSUE TITLE
Inaccurate tags in few tracks

### ISSUE THREAD

**Issue by Progressive-Soul** [Marekkon5/onetagger#273]
Hi,
Could you please check this for me:

**Alex O'Rion - Drift (Auditoria Remix)** is getting tagged as the Original Mix in the title. 
I've attached the mp3 along if it helps. Thanks!

**Comment by Marekkon5** [comment]
Hello, what platform(s)? Also there is no MP3 attached. Thank you.

**Comment by tripolarspace** [comment]
On Beatport. I'd attached the mp3 though, weird. Let me know if I can email it to you

**Comment by Marekkon5** [comment]
Hello, should be fixed in latest commit, you can get the build from Actions tab to test it out.
Just a note: keep "Ignore version when matching" disabled in Beatport options, otherwise it won't match.
Feel free to comment or open new issues if you have more problems.
Thanks.

**Comment by tripolarspace** [comment]
Hi, it is working in the latest commit with that option disabled. 
Thank you :)
