### ISSUE TITLE
Using Quick tag separators

### ISSUE THREAD

**Issue by smokingbehind** [Marekkon5/onetagger#278]
<img width="552" alt="2023-09-09 в 18 56 09" src="https://github.com/Marekkon5/onetagger/assets/34321240/0590662c-737e-4927-bc8a-da2d3c35587c">

<img width="865" alt="Снимок экрана 2023-09-09 в 18 56 00" src="https://github.com/Marekkon5/onetagger/assets/34321240/523038f3-79aa-44e1-bc6a-d5102fb7bacc">

If you change genre separators to / (space+slash+space), first time it will work. 
In tags it will look like: House / Tech 
in OneTagger it will look like: House, Tech

But if you close OneTagger and will open again, than all genres in files tags will merge like: House Tech

**Comment by Marekkon5** [comment]
Hello, should be fixed in the latest commit (on the python branch).
You can get the build from the Actions tab to test it out.
Feel free to comment or reopen if you have any more issues.
Thanks
