### ISSUE TITLE
Suggestion: Auto-save when changing to another track while on "Edit tags" tab

### ISSUE THREAD

**Issue by geiras** [Marekkon5/onetagger#28]
Similar to what happens while on "Quick tag" tab when the setting is enabled.

**Comment by geiras** [comment]
Also consider keyboard shortcuts to navigate between songs on "Edit tags" tab. If autosaving is not possible, a save shortcut would be useful already.

**Comment by Marekkon5** [comment]
I've added autosave option to settings and `CTRL+S` shortcut now works there. Reopen / comment if you have any issues with it. You can get latest binary from the Actions tab. Thank you.
