### ISSUE TITLE
#REQUEST || Can we please get an android app for this? 

### ISSUE THREAD

**Issue by zerobun** [Marekkon5/onetagger#283]
Having this as an app on your phone would be a really amazing and very very helpful.

Please make an android app for this 🙏

**Comment by Marekkon5** [comment]
Hello, Android version of AT is available, you can download it from the Releases page of 1.7.0
 (current latest version).
https://github.com/Marekkon5/onetagger/releases/tag/1.7.0


However I've moved the Android part source to separate repo and didn't update it yet for latest commits: https://github.com/Marekkon5/onetagger-android


Feel free to comment or open new issue if you have more problems. Thanks
