### ISSUE TITLE
Skipped track =/= Failed track

### ISSUE THREAD

**Issue by jmelbourne** [Marekkon5/onetagger#287]
Is it possible to make it so that skipped tracks are not moved into the same folder as failed to tag tracks? When skipping already tagged tracks by release ID, which have been successfully tagged, it makes it hard to find the failed to tag tracks when batch tagging.

**Comment by Marekkon5** [comment]
Hello, there has been some changes recently which actually fixed this. You can get the latest build from the Actions tab to test it out. Feel free to comment or open new issue if you have more problems. Thanks
