### ISSUE TITLE
Shazam fails in the Android App

### ISSUE THREAD

**Issue by Esokrates** [Marekkon5/onetagger#289]
Hello,

Kudos for the great application!
In Android 14 (Google Pixel 6) it fails to use Shazam to identify tracks:

![image](https://github.com/Marekkon5/onetagger/assets/17780185/b92f0fee-d52d-4a5b-9d3f-b3f532fe0100)

**Comment by Marekkon5** [comment]
Hello, could you please send one of the files as sample? Perhaps it's some format that 1T struggles with. 
Also are you using the release build or Actions build? 
Thank you

**Comment by Esokrates** [comment]
Hello,

Using the OneTagger-android-arm64.apk from https://github.com/Marekkon5/onetagger/releases/tag/1.7.0

Find all the files here: https://drive.proton.me/urls/PN6GMMWFSM#COSr1I6AiuRO
Password is your Github username (case sensitive!)

**Comment by Marekkon5** [comment]
Hello, thank you for the files, I've fixed it in the latest commit, you can get the PC version form the Actions tab to test it out, however there's been a lot of recent changes, which I did not copy over to the Android version yet, because

a) It requires kinda effort
b) It broke compiling on random because of dependencies and such
c) It didn't get much attention, so I didn't bother updating it so far

So it will probably take me some time to make this work on Android. 
Thanks

**Comment by Marekkon5** [comment]
Hello, should be fixed in latest commit. You can get the apk files from Actions tab in https://github.com/marekkon5/onetagger-android
Thanks

**Comment by Esokrates** [comment]
@Marekkon5 Awesome, thank you very much. I tested it, it seems recognition works now, however writing the tags to the file seems to fail because the app did not acquire writing permission:

![image](https://github.com/Marekkon5/onetagger/assets/17780185/2765f924-f684-4451-a1b0-6f72b3bf7dee)

Reviewing the app permissions explicitly states read permission only:

![image](https://github.com/Marekkon5/onetagger/assets/17780185/a8ab71ec-084f-4503-a6ed-8609be25eae6)

**Comment by Marekkon5** [comment]
Hello, Android 14 again changed some things in storage permission handling, and again made it even harder to access the storage, because storage bad, we full iPhone now. 
Anyway, the latest commit has a fix/workaround, you can get the build from Actions tab on the onetagger-android repo. Thanks

**Comment by Esokrates** [comment]
Thanks, tested it and it works, great job!
Only thing I noticed that does not work: Album artwork in not embedded into the files, is that not supported on Android?

**Comment by Marekkon5** [comment]
Android uses same code as desktop version, so they should work, however
a) what format do you use?
b) can you provide track name + platform so we can test?
c) perhaps your player program has trouble displaying it for some reason?

**Comment by Esokrates** [comment]
a) m4a again, see sample file here https://drive.proton.me/urls/WZN6QAV9FM#fq9wE_-Ii3Ru (this is already tagged by 1T, but the artwork is not visible in any program I use).
b) used Deezer as sole platform
c) I can rule that one out, when I tag the file under Android none of the music player apps display the artwork, nor my desktop music players do. However when I tag the file with 1T on desktop (Linux) I can see the album artwork in all my music player apps.

**Comment by Marekkon5** [comment]
I've just tried on Android 13 emulator, and Android 14 device, with your song + Deezer all default settings, and I got correct album art both times.
Do you have overwrite tags on? Do you have save cover to file off? Did you change the Deezer resolution (altho it shouldn't matter in Deezer, and should show up in log)? Is there anything in log?

**Comment by Esokrates** [comment]
@Marekkon5 Turns out Album Art was ticked off in the App, sorry for noise. Thank you very much for having a look and the great work altogether!
