### ISSUE TITLE
Unable to Play M4A Files: Invalid Data Type Error

### ISSUE THREAD

**Issue by leobowenwang** [Marekkon5/onetagger#290]
## Description
When trying to play M4A files in the Quick Tag section, the application shows an "Invalid Data Type" error. 

## Steps to Reproduce
1. Open OneTagger
2. Navigate to Quick Tag section
3. Attempt to play an M4A file

## Expected Behavior
The M4A file should play normally.

## Actual Behavior
An error message appears saying "Invalid Data Type."
<img width="203" alt="image" src="https://github.com/Marekkon5/onetagger/assets/59091252/9616e9fc-6165-4738-984b-e4d297f0bf38">

**Comment by Marekkon5** [comment]
Hello, this has been fixed in latest commit. You can get the build from Actions tab. Feel free to comment or open new issues if you have more problems

**Comment by psyjafo** [comment]
> Hello, this has been fixed in latest commit. You can get the build from Actions tab. Feel free to comment or open new issues if you have more problems

I see this has been asked in the past.. could you enlighten me how to fix it again?

Thanks!!!
