### ISSUE TITLE
Quick Tag Custom section field selection not retained when moving sections in settings

### ISSUE THREAD

**Issue by MartinJoy** [Marekkon5/onetagger#294]
Let's say I have a couple of custom tag sections configured in Settings > Quick Tag Custom and both sections write to a different field, e.g.: 1) Situation written to TALB, 2) Instruments written to COMM.
When I change the order and move Instruments above Situation the respective tag fields to write to get exchanged and I end up with 1) Instruments written to TALB, 2) Situation written to COMM

**Comment by Marekkon5** [comment]
Hello, should be fixed in the latest commit, you can download the binary from the Actions tab. Feel free to open new issues if you have more problems, thanks.
