### ISSUE TITLE
Copy/Paste keyboard shortcuts don't work in the Edit Tags searchbar with MacOSX 

### ISSUE THREAD

**Issue by davidfarinha** [Marekkon5/onetagger#299]
Keyboard shortcuts (command + c for copy, command + v for paste, command + a for select all) don't work in any of the text fields on the Edit Tags screen both for the search bar and the ID3 metadata tag text inputs. This makes it very slow and inefficient to edit search for tracks and edit tags for hundred/thousands of songs this screen effectively.
![Uploading image.png…]()

**Comment by Marekkon5** [comment]
Hello, should be fixed in the latest commit, you can download the build from the Actions tab. Feel free to comment or open new issues if you have more problems. Thanks

**Comment by davidfarinha** [comment]
@Marekkon5 Thankyou!

**Comment by Marekkon5** [comment]
> @Marekkon5 Hi, the issue still exists in Version 1.7.0.

1.7.0 was released before this fix. You should try using the development build from Actions tab.
