### ISSUE TITLE
Suggestion: Add search field on "Edit tags" tab

### ISSUE THREAD

**Issue by geiras** [Marekkon5/onetagger#30]
I want to be able to isolate specific tracks that I need to update certain tags on. Right now, I can only do it trough scrolling. Would be nice to quickly drag and drop or search to isolate and find those tracks quickly.

**Comment by Marekkon5** [comment]
Hi, thanks for all the suggestions, I've read them but I am on vacation right now so will add them later. Thanks

**Comment by Marekkon5** [comment]
Added in latest commit, you can get binary from Actions tab. Thank you.
