### ISSUE TITLE
Unexpected frame, header error when trying to play a track

### ISSUE THREAD

**Issue by NAWTBOY** [Marekkon5/onetagger#300]
![image](https://github.com/Marekkon5/onetagger/assets/151057792/ab9df87a-db8b-4a08-b955-4437b915eb17)

Any ideas what could be causing this?

**Comment by Marekkon5** [comment]
It usually means that the file isn't 100% correct (might be corrupted at some point or have non standard data). While most players just skip those corrupted parts and play it perfectly fine, onetagger is strict. Tagging should work normally, however playback won't. We recommend using some sort of MP3 repair tool.

**Comment by Marekkon5** [comment]
Hello, should be fixed in latest commit, you can get the build from Actions tab to test it out. Feel free to comment or open new issue if you have more problems. Thanks
