### ISSUE TITLE
About the general skills

### ISSUE THREAD

**Issue by kaya9999** [Marekkon5/onetagger#306]
Hello,

1. Is the One Tagger application completely free? Will there be a paid plan in the future?
2. Can local files in wav format store these tags?
3. Can it keep genre tags from different platforms together?
4. Are you considering automatic hotcue feature and coloring? (Most valuable topic)
5. Can it automatically perform instrument information, male and female voice information, beat scale information, mood and key tags? (Data pool available)
6. Do you consider automatic updating of tags such as popularity at regular intervals? (Sorting information, change arrow direction and step counter in the lists would also be nice)

It would be very useful for everyone if you could help clarify these questions. There may also be new features that are overlooked. I'd be very happy with that.

**Comment by Marekkon5** [comment]
Hello, 

1. Yes, in future I don't know, however even if we decide to make paid version, all the current and future features before that change will remain free.
2. Yes, it uses ID3 and basic RIFF tags, however tagging wav files is not recommended. 
3. Yes
4. No
5. Technically yes, however AutoTagger just fetches data that's available on public websites and writes them to tags. So there would have to be a website that provides such information. Also there is a problem of where to save them. Some standards (ID3, Vorbis, etc) might have a field for some of those tags, however many DJ apps just do whatever they want and store it differently.
6. As I said before, AutoTagger just fetches info from various websites. If a website has popularity it can be fetched and updated, however it isn't implemented for any of the current sources.

Thanks

**Comment by kaya9999** [comment]
Thank you very much for your interest and answering the questions. I read it in detail and tried to understand the logic.

1. You are very brave in approaching this question. In the future, you can provide reward points for those who provide a pricing plan and data support.

I have great confidence in this application and it may evolve from an automatic tag application profile to an automatic collection management application in the future. Everything is automated and may have more information from streaming platforms. The issue of standards applicable in question 2 is overcome by keeping the application with its own standards compatible with every platform.

2. Do you have a chance to share why tags are not recommended for Wav format? Which tags can we use and which can't we use?

4. If this question is not a costly question, I would like to support it with a sentence. Hotcues take a lot of time and if you are a professional you need to plan the sequence. Frankly, people don't do this. If hotcues are colored automatically and according to their type, there is no need for any application other than this application. If we have a file, everything is always ready.

5. For this question, I understood it better and saw that it was related to Questions 1 and 2. Not every format can store data and not every platform can read it correctly. That's why, after a while, this application should be the center and be ready to produce the appropriate output for whatever platform we will perform with. I think there is no information such as vocals, instruments and languages ​​on broadcast platforms. That's why I think there is a need for a pool that we support.

Do you have a chance to tell us which tags we can get automatically?

6. For this question, I think it is not possible because there is no information from the sources.

**Comment by Marekkon5** [comment]
2. Generally, by definition WAVs are supposed to be "raw audio data". They're not supposed to have tags. There is the RIFF header, and ID3, however it's not a standard, and some apps might decide to not read it or do it differently.  You should use FLAC or other formats.

4. (Hotcues): Every DJ app has own implementation and own system. Therefore we would have to maintain an implementation for every app (which is also problematic because some are proprietary etc). OneTagger (Autotagger) just fetches data from the internet and saves it into the tags. It doesn't do any processing of cues. So we won't be doing this.

5. Which tags are available = which tags you can read on each site. If a site where you can see the vocalist / popularity or other info exists, it can probably be added to OneTagger.
As for where to save this info - different formats (ID3, Vorbis etc) might not have a standard fields for this info, so saving it might cause most apps to not read it / ignore it.

**Comment by kaya9999** [comment]
Thank you very much. In general, I was informed. Some issues are difficult because they go beyond the purpose of the application and there may be limitations.

As a last question, can we transfer our playlists to our playlists on our music platforms? Any chance we can add this ? Thus, we are synchronized everywhere.

I used One tagger when talking to you, the matching rate seems to be 70%. Although the music is downloaded from popular apple music, it may not be available there.

Should I turn on the shazam feature?

**Comment by Marekkon5** [comment]
OneTagger only tags local files, it doesn't convert / manage playlists on online platforms. You can use playlist convertors such as soundiiz.com. The Shazam feature is for tagging files which do not have any metadata (not even title/artist). 

Feel free to comment or open new issues if you have more questions. Thanks
