### ISSUE TITLE
Error Shazaming file - invalid data type

### ISSUE THREAD

**Issue by markosopcic** [Marekkon5/onetagger#308]
Hi! I'm trying to create a music library by downloading music from youtube in .m4a format with yt-dlp and ffmpeg. I would love to have an automatic way of tagging the music so my music library can pick up what artist or album the songs are. 

I tried OneTagger with shazam on 33 songs, and 30 of them get skipped, with the above mentioned error:
`Error Shazaming file - invalid data type`. 
The other 3 songs get recognized fine.
The songs can be played and are not corrupt. 

I've seen that the Shazam part of OneTagger is from the SongRec repository, and I've noticed the SongRec repository also has a python version. I tested the `audio_file_to_recognized_song.py` script with the songs that get skipped in OneTagger, and they work fine. 

Unfortunately I have 0 experience with Rust. I've been fiddling with it for two days now, but can't seem to get debugging to work on my machine to try and figure out why Shazam fails on most of my songs. 

I'd love to provide any help I can to make this work. Please let me know if there's anything I can do to help you resolve this issue, or if I can provide any more information.

**Comment by Marekkon5** [comment]
Hello, could you please try the latest development build from Actions tab. iirc there was similar issue fixed there. Thanks
