### ISSUE TITLE
Spotify Client Secret input does not focus properly with mouse on Mac

### ISSUE THREAD

**Issue by luchak** [Marekkon5/onetagger#31]
All of this is on MacOS 11.5.2.

Keyboard input on the Client Secret input works properly when it is focused with the tab key:

![image](https://user-images.githubusercontent.com/591019/129493090-719dcd1b-e63d-42cc-8655-84f980d8eb1f.png)

... but not when it is focused with the mouse:

![image](https://user-images.githubusercontent.com/591019/129493098-99010836-c5f6-43ef-8733-2a8530ee2fbb.png)

This behavior is extra annoying because:

* the app does not save this field across runs (another bug? or intended?),
* the app does not accept paste into this field via the cmd-V keyboard shortcut, and
* this behavior blocks paste via mouse right click

... and so as a result I have to retype my Spotify client secret by hand each time I open the app. On top of that, backspace does not work in this field either, so if I make a single mistake I have to tab-focus the field again, delete all of its contents, and restart from scratch.

**Comment by Marekkon5** [comment]
Very weird behavior, Mac OS specific I guess, will let @bascurtiz  do the testing. The tonken should be saved after you start tagging.

Also could you please try just opening 1T in background and opening Chrome and going to http://localhost:36913 - it might work withour those bugs there. Thank you.

**Comment by Marekkon5** [comment]
The latest commit should fix it, you can get binary from the Actions tab. Please comment or reopen if it doesnt work, thank you.
