### ISSUE TITLE
FEATURE REQUEST - SUB GENRE in different column

### ISSUE THREAD

**Issue by DJBEWARE** [Marekkon5/onetagger#316]
Allow placing the top level genre in the genre column and one or more sub genres in a chosen column.  

A couple examples:

HIP HOP in the GENRE column but allow me to put "EAST COAST" and or "BOOM BAP" in the comments tag or the remixer column.

HOUSE in the GENRE column and "UK GARAGE" and or "PROGRESSIVE" in the comments column.

INTERFACE wise 
In the QUICK TAG screen the interface could look the same and when one clicks the genre it writes to the Genre column. and IF one clicks one or more of the listed sub genres they go to a separate column that I specify.

**Comment by Marekkon5** [comment]
Hello, I do believe you can use custom QuickTag tags for that - you can create a custom "Subgenre" with the values which you want and write it to any tag you want. Let us know if this isn't what you had in mind. Thanks

**Comment by DJBEWARE** [comment]
It is and that work around works, but it would be nice from a work flow perspective though to do it from the same area in the interface where the Genres are chosen.

**Comment by Marekkon5** [comment]
Added in latest commit, it's in settings on bottom as "Custom subgenres tag". You can get the latest build from the Actions tab to test it out. Feel free to comment or reopen if you have more issues/requests. Thanks
