### ISSUE TITLE
Comments won't transfer to Apple Music app

### ISSUE THREAD

**Issue by Miniraise** [Marekkon5/onetagger#317]
I've set the Vibe for mp3 files to "COMM", and this does add what I want to the file metadata, but the comments sections is blank in the Apple Music app on my Mac. Is this a compatibility issue, or a setting I'm missing? The "Comments" field in the Music app seems different from the "Comment" ID3 tag. Is there a way to merge or fix this this? The metadata matrix says comments should be compatible with the Music app.

This is also happening in RekordBox. The id3 metadata has the Vibes in its "Comment" section, but even when I re-import to RekordBox, RekordBox's "Comments" section is blank.

When I go into the "Edit Tags" section of OneTagger for a specific song, there is a "comment" section below "Year (TYER)", while "Comments (COMM)" is much lower and below the album art - this is where the Vibes go. Should it be writing to "comment" instead, and if so, how?

Photos are a song example - one is showing the Music app info, the other is showing the ID3 tags after using OneTagger.

<img width="332" alt="Screenshot 2024-01-08 at 1 28 13 AM" src="https://github.com/Marekkon5/onetagger/assets/155941371/16418157-bc86-488f-b426-016104f54113">
<img width="572" alt="Screenshot 2024-01-08 at 1 27 39 AM" src="https://github.com/Marekkon5/onetagger/assets/155941371/749a4b5c-bbe0-4888-9969-08cacf33a508">

**Comment by Marekkon5** [comment]
Hello, the proper comment field for ID3 is "COMM". Apple Music is able to read it fine. You should set the vibe to write to `COMM` in case of ID3 (you can select it from the dropdown menu). Field `comment` is written to TXXX field which is a "custom field" and therefore Apple Music won't be able to read it.

**Comment by Miniraise** [comment]
Hi Marekkon5,

Thanks for the fast response! Unfortunately, I am writing it to COMM (as seen in the photos), yet Apple Music and Rekordbox won’t read it.

Any idea why?

I love OneTagger - thank you so much for building it!

Best,
Matthew

**Comment by bascurtiz** [comment]
@Miniraise 
Could you compare to what you do different vs my approach?

See: https://youtu.be/fW2hEUGGx8U

1. I check in Mp3tag whether the tags are ID3v2.3 or 2.4
2. I make sure Quick Tag writes ID3v2.3 (by default) to the ID3v2.3 MP3 file, then add/delete some Custom tags
3. I make sure Quick Tag writes ID3v2.4 instead to the ID3v2.4 MP3 file, then add/delete some Custom tags
All isn't needed, but just to show you Apple Music handles both fine
4. I open them in Apple Music and they show the comments.

**Comment by Miniraise** [comment]
@bascurtiz Is it necessary to identify if it is ID3v2.3 or 2.4? I was trying to avoid buying MP3tag. I'm doing the same as you other than changing the Quick Tag setting that writes to 2.4 and instead of 2.3. Could that be what's causing this issue? Thanks so much for the video!

**Comment by bascurtiz** [comment]
@Miniraise Like I said: _"All isn't needed, but just to show you Apple Music handles both fine"_

Two options:
1. Do enable Quick Tag to write to ID3v2.4 instead (and check if that makes a difference)

2. Upload a mp3 file that refuses to show those COMMENTS in Apple Music.
Maybe some old ID3v1 instead v2 fucks shit up?

U can attach such file , zipped on Github here to your reply, or simply upload it to wetransfer.com or so so we can further investigate. Thanks.

**Comment by Miniraise** [comment]
@bascurtiz 

[03 Beautiful Now (Extended Mix) copy.mp3.zip](https://github.com/Marekkon5/onetagger/files/13865420/03.Beautiful.Now.Extended.Mix.copy.mp3.zip)


Here's a zipped file of one of the songs - as you can see it has comments, but they won't show up in Apple Music or Rekordbox.

**Comment by bascurtiz** [comment]
@Miniraise @Marekkon5 
Looks like a dupe of https://github.com/Marekkon5/onetagger/issues/227

To fix this behavior, set COMMENT language to: `eng`
This way Rekordbox and Apple Music are able to read the COMMENT (they seem to refuse a dummy like `xxx` ).

See: https://youtu.be/ADxuibdICZo

**Comment by Miniraise** [comment]
@bascurtiz Thank you so, so much! I'm so sorry for bringing up an old issue - I didn't see #227 before.
