### ISSUE TITLE
beatbort tags all fail

### ISSUE THREAD

**Issue by Woah-Man** [Marekkon5/onetagger#320]
All beatport tags are failing. ive seen this issue has been posted before but do not see any fixes.

**Comment by mkgilmore** [comment]
I am also now having this issue. MacOS v1.7.0 on Apple Silicon.

**Comment by Woah-Man** [comment]
I should post on the discussion but problem fixed by updating one tagger.
There is not an update link you have to re download from the site.

**Comment by Marekkon5** [comment]
Hello, Beatport should be working fine, if it doesn't:

1. Can you send us the log (Settings -> Open Data Folder -> onetagger.log)
2. Try the latest development version from Actions tab? Thanks

**Comment by Woah-Man** [comment]
Yup update worked I didn't realize there was an update until I deleted and
re downloaded. Thank you
