### ISSUE TITLE
Permission denied when running one tagger as debian-transmission

### ISSUE THREAD

**Issue by kishorkurian123** [Marekkon5/onetagger#322]
I know this is not completely onetagger issue, but I am getting a PermissionDenied error. What I am trying to do is, I am download music using Transmission (torrent client) and once a torrent is finished, it starts a bash script, and the bash script does some things including starting the autotagger on those files.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', crates/onetagger-shared/src/lib.rs:102:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The user is debian-transmission and I am not sure which folder/ file to change ownership or chmod to solve this problem. This is definitely a small permission issue, but I cant figure out which folder/folders/files are causing this.

**Comment by Marekkon5** [comment]
Hello, OneTagger saves its config and log files to `~/.config/onetagger`. Perhaps that folder is unwriteable.

**Comment by kishorkurian123** [comment]
Yes! This was the issue. Thanks a lot.
