### ISSUE TITLE
Edit Tags: Missing Title Tag (M4A)

### ISSUE THREAD

**Issue by OliverGuy** [Marekkon5/onetagger#323]
Hi, thanks for the great software, saved me having to manually tag 400+ files !

In the "edit tags" tab, it seems that there is a missing "title" tag in the dropdown, which should be `©nam` for M4A files from my understanding:

![image](https://github.com/Marekkon5/onetagger/assets/10829642/83570d0e-1a37-4483-a741-fc016d12f2dd)

What may or may not be related is that this tag does not have its helpful nickname for correctly tagged files:

![image](https://github.com/Marekkon5/onetagger/assets/10829642/edc8dc17-0e00-47ca-ba5c-235d3e6c7c4a)

Keep up the good work !

**Comment by Marekkon5** [comment]
Hello, added in latest commit, you can get the binary from Actions tab to test it out. Feel free to comment or open new issue if you have more problems. Thanks
