### ISSUE TITLE
Track seeker doesn't update when autoplaying next song?

### ISSUE THREAD

**Issue by PaperOrb** [Marekkon5/onetagger#332]
I'm using the appimage on linux popOS 22.04 LTS and tracker seeker at the bottom of the "quick tag" pane doesn't update or even reflect that a song is playing when the next song starts autoplaying through my speakers.

**Comment by Marekkon5** [comment]
Hello, sorry for the delay, should be fixed in latest commit, you can get the binary from the Actions tab to test it out. 

Also I have no idea where did you get AppImage from, since we don't distribute any AppImages.

Feel free to comment or open new issues if you have more problems. Thanks
