### ISSUE TITLE
Suggestion: Single/Releases metadata fill

### ISSUE THREAD

**Issue by aleixjf** [Marekkon5/onetagger#34]
HI! There are occasions where I do have a single which has been later released in an Album of the same artist. I don't know if this would be possible, but I'd love to fill the "single" metadata with the "release" metadata, but fill the Release Date with the "single" data.
Do you think this would be possible? In case there are more than 2 similar matches for a search, for example...

**Comment by Marekkon5** [comment]
Thank you for the suggestion - I can add an option to use the oldest release date from within matches that have the same accuracy. However I do believe the scenario will be super rare. Thank you.

**Comment by aleixjf** [comment]
Thank you! The only use case I see is the one already described:

You have a version that has been released as a "Single", but months or even years later, it's released in an Album with more single + unreleased tracks.
I personally prefer to have all the singles tagged as the latter release (the metadata from the track in the Album), rather than having multiple singles. But I do want to have the original "public" release date, for smartlist purposes! Don't know if I'm explainning my use case properly but it makes sense to me jaja ;)

**Comment by Marekkon5** [comment]
I've added the feature to order matches by release date in the newest commit. Your use case (combining 2 different tracks) is very specific, so I will not add it. However you can workaround it right now by just running it twice with different ordering. Let me know if you have any issues with it. Thanks.
