### ISSUE TITLE
Typing in the Input Folder field error

### ISSUE THREAD

**Issue by nmycps** [Marekkon5/onetagger#340]
In the AUTO RENAME, when you type or erase characters in a path, each time a window pops up and gives an error.

https://github.com/Marekkon5/onetagger/assets/61409851/f73a67f3-175c-4646-bde1-83f8079dc101

**Comment by Marekkon5** [comment]
While this is kind of intentional (you're supposed to paste or use browse button), fixed anyway in latest commit.
