### ISSUE TITLE
Problem With .Flac Files

### ISSUE THREAD

**Issue by OnlineAppearance** [Marekkon5/onetagger#341]
The first time I tag a .Flac file with any field, it tags fine. But the second time i do it, it fails no matter the field -other than synced lyrics, which successfully writes the .lrc file to the directory but still says the tagging process was failed for some reason.

When I try to do the same for .mp3 files, everything works perfectly. 

My issue is that I want to overwrite some of the tags with another scan but it fails every time.
Note: Overwrite tags is on

A speedy reply would be very much appreciated. 
Thankyou.

**Comment by Marekkon5** [comment]
Could you please provide the log? Thank you.

**Comment by OnlineAppearance** [comment]
> Could you please provide the log? Thank you.

Thankyou so much for replying so quickly.

I have found the log file, but I can see that it is rather messy (my file path names are really long , so should and i am also not sure how much of the logs I should send).

**Comment by Marekkon5** [comment]
Would be better to delete the log file, re run only on relevant files and send that. Thanks

**Comment by OnlineAppearance** [comment]
I'm so sorry for wasting your time. I realised -through the process of trying to set up some trials to add to the log- that the main issue was not that tagging a .flac file twice causes tagging to fail; it was the fact that the files i was trying to tag were hidden.

I apologise for my lack of thorough research, because i know there are so many issues in this repository you need to attend to.

Thankyou for the helpful replies anyway.
