### ISSUE TITLE
[Enhancement] add TIT3 frame in the list of ID3v2.4 variables

### ISSUE THREAD

**Issue by SP-937-215** [Marekkon5/onetagger#342]
Hello,

Could you please add "subtitle" ([frame TIT3](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.4.0-frames.html#tit3)) in the list of available ID3v2.4 variables?

Thank you!

**Comment by Marekkon5** [comment]
Hello, TIT3 is in the list of abstractions, so it should be available in the tag fields. If it isn't, please try latest actions build, or you can directly just write `TIT3` anyway.

**Comment by SP-937-215** [comment]
Thanks!
