### ISSUE TITLE
Is it possible to use the full release date instead of just the year?

### ISSUE THREAD

**Issue by leon1fcn** [Marekkon5/onetagger#343]

**Comment by Marekkon5** [comment]
1T tries to fetch full release date when possible (if available and format supports it). Which platform did you try? Also what format did you use? Thank you

**Comment by leon1fcn** [comment]
I used stems and spotify

**Comment by leon1fcn** [comment]
And another thing I noticed... I used 1T for my whole library and now all my BPM and beatgrids are wrong. Every songs BPM is changed and now they don't fit the beatgrid anymore... what was my mistake? (I selected to not change BPM values in the tagging process)

**Comment by Marekkon5** [comment]
I'll look into the release date issue, and messed up beatgrids; disable overwriting BPM tag. 1T shouldn't touch any private DJ apps tags, so I don't really know what's causing it.

**Comment by leon1fcn** [comment]
@Marekkon5 Thank you! Yeah I don't know either. In Traktor I locked the BPM etc now so it won't be changed again

**Comment by Marekkon5** [comment]
Should be fixed in latest commit, you can download the binary from the Actions tab to test it out. Feel free to comment or reopen if you have more issues.
