### ISSUE TITLE
Rate limiting on Spotify

### ISSUE THREAD

**Issue by drsgfdds** [Marekkon5/onetagger#346]
Was trying to Autotag genresfrom Spotify and it just paused midway through.  Checked the logs:

2024-03-01 10:49:08 [WARN] onetagger_platforms::spotify: Spotify rate limit hit, sleeping for: 72982s...

What settings should be used to avoid hitting the Spotify rate limit? This is almost 24 hours.

**Comment by Marekkon5** [comment]
You can use less threads and tag less songs at a time. Otherwise there isn't much you can do.

**Comment by Marekkon5** [comment]
I added a ""fix"" which slows down Spotify by a bit, and also detects too high rate limits. You can get the binary from Actions tab. It is not perfect, however this is Spotify-side issue, so not much we can do, therefore I'll close this for now.
Feel free to comment or open new issues if you have any problems. Thanks
