### ISSUE TITLE
“OneTagger” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by djtony79** [Marekkon5/onetagger#35]
Can OneTagger become a reconized deleoper by apple? would probably help there customer base if they ever start charging.

/no a deleoper but there are no contact details on their website....

**Comment by Marekkon5** [comment]
What do you mean by this, could you be more precise? Thank you

**Comment by djtony79** [comment]
my bad sorry.
when you try to open the file on a Mac you get the warning message "“OneTagger” cannot be opened because the developer cannot be verified."
I assume this is because OneTagger is no a verified developer at Apple.
If they were then the warning would not pop up. I think this will put a lot of people off installing the software.
Does that make sense?

**Comment by Marekkon5** [comment]
Yes, however doing that requires us to pay money to Apple and probably going thru some verification processes. We don't plan on doing this anytime soon, because it would make building and publishing more painful and we don't wanna pay any fees as this app is opensource. Thank you for the suggestion anyway

**Comment by djtony79** [comment]
Ok gotcha. That makes sence.
Maybe just get some other external verification that is cheap but still credible? Just so it is obvious to people. Maybe it is just me being dumb but this is first time I have seen this warning when installing a program.

On 17 Aug 2021, at 15:32, Marekkon5 ***@***.***> wrote:

﻿
Yes, however doing that requires us to pay money to Apple and probably going thru some verification processes. We don't plan on doing this anytime soon, because it would make building and publishing more painful and we don't wanna pay any fees as this app is opensource. Thank you for the suggestion anyway

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Marekkon5** [comment]
As for Apple there are no "cheap" ways to do this sadly. It costs 100$/year. However @bascurtiz whill create installation videos which will hopefully help users install it without being worried about this.

**Comment by onetagger** [comment]
@djtony79 Website updated with new how-to install videos for Win & macOS (incl. how to proceed when such warning pops up).
