### ISSUE TITLE
Cannot upload playlist

### ISSUE THREAD

**Issue by crankedguy** [Marekkon5/onetagger#350]
Hi,

I cannot upload any playlist in latest version on Windows. Drag & drop does not work, it just does nothing. It does not even log anything to the log. It is just defunct.
Tried with any playlist, m3u or m3u8

Even with only 1 file in it.
Restart does not help either.

**Comment by crankedguy** [comment]
I saw for m3u8 this is even mentioned here already, this seems like it has never been fixed then, because it is the same behavior, it stays just blank. This is a huge issue due to 1T being not the most stable and completely hangs up, at least on Windows, with bigger tasks, I need to be able to load a playlist otherwise I can never tag the files that still need to be tagged from a previous run with a hang.
https://github.com/Marekkon5/onetagger/issues/148

**Comment by Marekkon5** [comment]
Hello, could you please try the latest Actions build? It has some changes related to this. You can download it from the Actions tab on top of GitHub.
Also sometimes this happens if the playlist is invalid / contains bad data.

Let me know if it fixes it for you. Thanks

**Comment by crankedguy** [comment]
Hi,

the playlist is for shure not invalid. It cannot even load the playlists created by your own app. E.g. the success and failed playlists you create. They cannot be loaded with the load playlist field.

I will try the latest build thanks.

**Comment by crankedguy** [comment]
I used the latest the build that was sucessful : https://github.com/Marekkon5/onetagger/actions/runs/8030185588
At least the upload works, it shows that the file was uploaded in the window.
Now the question is : How tested, or untested, are these versions? I am using this for production use case and I do not want to mess up 100K files. 
Thanks!

**Comment by Marekkon5** [comment]
Hello, sorry for delayed reply, we do not recommend running on 100K files. You should do smaller batches, and **make backups beforehand**. Many people reported that the tags 1T wrote were suboptimal or sometimes wrong, so you should test on smaller batches and see results for yourself. I'll also look into the playlists further.

**Comment by crankedguy** [comment]
I have written my own tagger for my "normal" music library, which works with Discogs, that is highly optimized as there is absolutely no tagger, neither commercial nor open source that would satisfy my needs. They are all either sloppy written and/or not thought out well.

Unfortunately for my track library Discogs is subpar and about 90% of my tracks are available on Beatport. Now if Beatport would give people proper API access I would have also written my own tagger because, sorry to say, your matching is also pretty subpar. It seems to me that the titles and artists are not properly normalized, e.g. Pig & Dan is not matched with Pig&Dan with a high probability. And you have to use a high probability >90% with 1T because with a lower one the results are simply completely off - no offense - through the bank. But this has nothing to do with probability anyways, this is a case for normalizing. Same e.g. for Thomas P. Heckmann and Thomas P.Heckmann. Honestly this is a bit wondrous because you seem to take a lot of care for UI and bits, but missing out such really basic things.
As said, no offense!

I have written my own tagger that fixes the 1T errors with a post run. It runs with mutagen which is felt a 100 times faster than using metaflac. But it has to be done because the flac tags you write are literally unusable in standard software, because there is no software out there that uses "LABEL" from a flac tag, or "REMIXER". As you cannot tell 1T what to use for a field this would be completely unusable otherwise.

Cheers

**Comment by Marekkon5** [comment]
Over the years we've tried to improve the 1T matching & cleaning rates as much as possible, however I fully do agree that it isn't perfect or most likely won't ever be perfect. I also understand that everyone has their preferences when it comes to this and prioritizes different aspects. However feel free to suggest, open PRs or just read the matching code of 1T in case you want to improve it.

As for the selected tags; they were for most part selected by bascurtiz based on testing a lot of different apps and checking which tags they support and which they don't. You can see his work (and the work 1T's choices are based on) in the help section somewhere. We might add custom tags in future, however it would require a bunch of rewrites (and as you can see by my reply time I don't have much of it lately).

Feel free to leave suggestions here or open new issues if you have any. Thanks

**Comment by crankedguy** [comment]
Yea for me it is no problem as said, as I wrote most of the things that don't fit in a post-1T tagger. Unfortunately I am lacking time too, and I do not write rust so it is unlikely that I would contribute PR- or code-wise, sorry for that.

Re. preferences: Yes it is clear that you cannot include everyones personal preferences but normalizing artist and title strings for matching is the first thing I write in a tagger. But ok, mileage may vary here, too. It is simply there are 100s of tracks that are not matched because of a space or a _ instead of a -. Anyways, it is not my intention to make it look bad. It helped for a good bunch of files, with post-cosmetics, for me.

Re. tags: I can hardly imagine that. For mp3 tags that might be true what you say, for flac/Vorbis?? But ok, also this was fixed pretty easily afterwards in bulk.

A question : I did not have a look at the code but you are also not using any API for beatport, you are scraping, is this right?

As to suggestion : First thing I ever do is replacing all [-_()/&,.] by "", "\sand\s" by "", all \s+ by "", then all lowered if course, as an absolute minimum for comparisons regarding music tracks/tracknames. A very high percentage of cases are already covered by this simple measures, given you have a good basis of tags, but simply come from a different platform. This fixes mentioned cases below in an instan for instance. And it cannot lead to wrong results because it carries no information, it is just normalizing. Of course you have to know how the platforms you access give back information and adapt accordingly.

Cheers

**Comment by Marekkon5** [comment]
We do most of the cleanups you suggested already; https://github.com/Marekkon5/onetagger/blob/master/crates/onetagger-tagger/src/lib.rs line 850+

Beatport: we're using the API and CSR data (so that imo counts as API too although it's scrapping technically.)

**Comment by crankedguy** [comment]
Ok yea but somehow these things I mentioned are still missed. Anyway I think there is no pressing to discuss this further as I just live with it. I can only tell you that this is/was missed and it was pretty baffling, I did not look at the code as I do no Rust as said.

Ok thanks for the info! Yea my intention was not to nitpick what counts as API access or not but rather the question how does one get access to the real beatport API as this seems closed since a long time for "normal" persons, or better they do not respond to any requests... Because I would love to write my own tagger then solely for Beatport, as I have a real large track library in 6 figure area

**Comment by Marekkon5** [comment]
You can read the 1T source, or do your own research by reversing the web & mobile apps.

I'll close this issue for now, since it seems to go out of scope. Feel free to comment or open new ones if you have any issues with 1t. Thanks
