### ISSUE TITLE
FLAC file Not Working

### ISSUE THREAD

**Issue by IplaygamesIhate** [Marekkon5/onetagger#361]
When I'm using Flac files it isn't getting matched on any website. I have selected and logged into all sites. 
The same files when i just renamed it to .mp3, both got recognized though only 1 file was edited with all details.

They are 24 bit Flac files. Please let me know if im doing something wrong. Using 1.7.0 version

![Flac not support](https://github.com/Marekkon5/onetagger/assets/92145260/f472a2cf-ffb5-4e2d-b646-13ae5141bd64)
![flac](https://github.com/Marekkon5/onetagger/assets/92145260/f3636c1d-a72b-4370-89cd-f49f3ec86e05)
![Mp3](https://github.com/Marekkon5/onetagger/assets/92145260/a37a69d8-216f-4a70-88e0-22ede6d359ad)

**Comment by Marekkon5** [comment]
You have FLAC with an ID3 header. It is not normal or supported. You should use some tool to remove the ID3 header. 
Or maybe you can try latest Actions build of 1T, however 1T does not support these files.

**Comment by IplaygamesIhate** [comment]
Thank you. I got the files again and tried it. It worked.

I think since i changed the file type to mp3 by renaming it, i got that error
