### ISSUE TITLE
Audio Features - Limit?

### ISSUE THREAD

**Issue by elektrikmusik** [Marekkon5/onetagger#37]
First of all. I like the app very much. It is now part of my workflow for managing my DJ Library.
Good job.

For some reason Audio Features stop having "successfull' tags after 500 files.
I had to split my collection in batches of 400 files to achieve the audio features tag.

**Comment by bascurtiz** [comment]
Not sure what you mean.
I've tested it with (and without) ISRC on 3900+ tracks. All show up fine.

I'm showing a demo here: https://youtu.be/Gp_lUGzSuF8
I'm aware I'm not showing the AUDIO_FEATURES tag, but only raw values written.
But after adding that column in Mp3tag, they all seem to be written too.

Can you share your log file please?
1. Open One Tagger
2. Click Settings icon
3. Click General
4. Click Open Data Folder
5. Attach `onetagger.log` to your reply here (or upload to pastebin.com for ex.)

**Comment by elektrikmusik** [comment]
[onetagger.log](https://github.com/Marekkon5/onetagger/files/7026452/onetagger.log)

**Comment by Marekkon5** [comment]
Thanks for the log, it seems like problem with the underlying rspotify library. I've made a fix in the latest commit - lemme know if it works for you.

You can get the binary from the `Actions` tab, it should be ready within ~30 minutes. Thank you.
