### ISSUE TITLE
Tags getting reverted while search is active

### ISSUE THREAD

**Issue by bensinlukt** [Marekkon5/onetagger#377]
In Quick Tag mode, while filtering tracks using search, edited tags don't seem to stick. When closing the app, some changes save. Editing tags works as expected if not using the search function

Version:
1.7.0

Repro:
1. Go to Quick Tag mode
2. Type in anything in the search box to filter tracks
3. Edit tracks for any track (I was editing the two last ones in the list)
4. Click another track to save

Result:
* Tags for the edited track revert fully or partially.

**Comment by Marekkon5** [comment]
Should be fixed in latest commit, you can get the binary from Actions tab to test it out. Feel free to comment / reopen if problem persist. Thanks
