### ISSUE TITLE
Album art appears in apps like Rekordbox but wont appear in windows file explorer and I'm not sure why

### ISSUE THREAD

**Issue by g1adez** [Marekkon5/onetagger#380]
Not super important but I have no clue why and my nit pickiness is bugged by it

**Comment by bascurtiz** [comment]
Iirc, it's a Windows issue regaring ID3v2.4 vs 2.3, whereas 2.3 will show album art, and 2.4 won't, due Win being Win lol:
Here's some .reg to too, to fix things:
https://www.sevenforums.com/music-pictures-video/260159-mp3-album-art-not-showing.html

**Comment by Marekkon5** [comment]
Inactive, not 1T issue, you can disable ID3v2.3 in settings in 1T if needed.
