### ISSUE TITLE
Onetagger-cli command with m3u file instead of path

### ISSUE THREAD

**Issue by Hexactly** [Marekkon5/onetagger#382]
Trying to work out if this great tool can run using a supplied path to m3u file instead of a folder path.
Would be very useful for some automation tasks especially since an m3u is created for failed songs.

Thanks!

**Comment by Marekkon5** [comment]
Added support for this in latest commit, you can just pass m3u file path in the `--path` argument. You can get the binary from Actions tab to test it out. Feel free to comment or reopen if you have more issues. Thanks
