### ISSUE TITLE
''Missing artist tag'' 

### ISSUE THREAD

**Issue by mentaesphere** [Marekkon5/onetagger#383]
Hello!

When trying to load tracks on the program, it says ''Failed to load'' and when I click on the reason why, it says ''Missing artist tag''.

How can I fix that? I tried finding something about this to no avail. :( 

Thanks!

**Comment by Marekkon5** [comment]
OneTagger requires Title & Artist tags to be present in order for Auto Tag, Audio Features and Quick Tag to work. If you don't have those, you might consider using the Shazam, or parse filename options.

If this didn't help, feel free to comment or reopen, thanks.
