### ISSUE TITLE
Deezer Tags Locale

### ISSUE THREAD

**Issue by jljubich** [Marekkon5/onetagger#388]
I am a user of OneTagger and have a specific query regarding obtaining music genres from Deezer. Currently, the genres retrieved are in Spanish due to my Windows operating system's language and region settings. However, I prefer the music genres to be in English.

I would appreciate your help in understanding if there are any additional settings within OneTagger that I can adjust or if there is a method to force the genres to be retrieved in English regardless of the Windows language and region settings.

**Comment by Marekkon5** [comment]
Added in latest commit as a platform specific setting. You can test it by downloading latest Actions build. Thank you.
