### ISSUE TITLE
Can't open app

### ISSUE THREAD

**Issue by Plarson18** [Marekkon5/onetagger#392]
I am trying to download, open, and ultimately use the application, but after I download and go to open it, it says the developer can't be identified and I am completely unable to open the app. I am prompted with two options when I try to open it. First is to move the file straight to the trash, and the second is to cancel which just closes the window. I am completely unable to open and use Onetagger :(

**Comment by bascurtiz** [comment]
Maybe this helps: 
https://youtu.be/8IDG0igqJQs

**Comment by Marekkon5** [comment]
Video has solution to this problem, inactive issue, closing.
