### ISSUE TITLE
Half Star Ratings for Energy

### ISSUE THREAD

**Issue by Bank1824** [Marekkon5/onetagger#393]
I am currently usingthe Music/iTunes app to set energy ratings because I can do half stars in it and then copy those ratings to the grouping tag. This sort of works but there are a few additional steps I need to do depending on the file type to make the ratings show up in Serato.

1. For files other than mp3s and aiff files, I need to copy the tag info in the grouping tag to the content grouping tag in MP3tag because iTunes doesn't write to that tag and that's the tag that Serato uses.
2. If I make any changes to the energy rating in Serato I have to try to manage them in two places to keep them in sync.

It would be amazing if you were able to implement half star ratings in OneTagger for those that need more granular energy ratings!
![Screenshot 2024-07-14 at 11 59 37 PM](https://github.com/user-attachments/assets/0ea97d53-b3a7-423f-bd5c-8cad6a9a0cfa)
![Screenshot 2024-07-15 at 12 00 05 AM](https://github.com/user-attachments/assets/d825c023-7224-455b-a42e-86dd280b2262)
<img width="1440" alt="Screenshot 2024-07-15 at 12 04 49 AM" src="https://github.com/user-attachments/assets/44bc2154-6b99-4218-bd44-c9bd6f22ca9d">

**Comment by jljubich** [comment]
I don't think rating is related to energy, unfortunately. We're talking about different tags that shouldn't be interchanged, without a doubt.

**Comment by Marekkon5** [comment]
OneTagger's star ratings are Popularimeter or RATING WMP tags. They're whole integers, because frankly most apps reading them read them as integers only. It would also interfere with the energy as characters option. Therefore sorry but we won't be adding this, as it is very specific / single app use case / unstandardized.
