### ISSUE TITLE
Not finding the right tags for albums on auto tag / also dont tag as EP, single, Album etc

### ISSUE THREAD

**Issue by Bolty2024** [Marekkon5/onetagger#394]
Hi,

I tried to use this software however when i added a batch in, it has messed up the tags, by writing the wrong ones on it?

i have it on the strictist level, my method is spotify as thats where i get my songs from. Also is there a way that it can tag if its an album, EP, compilation, as some singles are on albums and it has messed those up for me aswell

**Comment by jljubich** [comment]
Spotify is probably not a reliable source for auto tagging. How did you try to tag your songs? Did your songs have ISRC tags applied, or were you trying to derive them from the file name or the artist and title tags considering their duration? Even using ISRC won't yield an acceptable result.

**Comment by Bolty2024** [comment]
Hi,

thank you for your response i tried to do it from name and the data recorded from spotify, which is where i get the music from, some results were fine but some got confused, not sure what the ISRC tag is, so im guessing thats a no. The next part i want to achieve is adding only the genre to all my music, but i dont want to mess up over 800k songs, any advice i would appreciate

**Comment by jljubich** [comment]
The ISRC (International Standard Recording Code) is a unique identifier for sound recordings and music videos. It is an essential tool for rights management and tracking the use of musical works. The ISRC provides a way to distinguish each recording of a song, even if multiple versions or releases exist. The code is typically assigned at the time of recording and remains the same throughout the recording's lifetime, facilitating its identification across various platforms and services. An ISRC consists of 12 characters, formatted as follows:

 - Country code (2 characters): Indicates the country where the ISRC is assigned.
 - Registrant code (3 characters): Identifies the registrant (usually the record label or artist).
 - Year of reference (2 characters): The year the ISRC was assigned.
 - Designation code (5 characters): A unique code for the specific recording.

For example, an ISRC might look like this: US-ABC-20-12345.

It is important to note that a song can have multiple ISRCs if it appears on different albums or in different versions. Each distinct recording or version of the song will be assigned a unique ISRC, allowing for precise tracking and rights management. This system helps in royalty collection, tracking airplay, and ensuring that creators and rights holders are properly compensated for the use of their work.

**Comment by Bolty2024** [comment]
> The ISRC (International Standard Recording Code) is a unique identifier for sound recordings and music videos. It is an essential tool for rights management and tracking the use of musical works. The ISRC provides a way to distinguish each recording of a song, even if multiple versions or releases exist. The code is typically assigned at the time of recording and remains the same throughout the recording's lifetime, facilitating its identification across various platforms and services. An ISRC consists of 12 characters, formatted as follows:
> 
> * Country code (2 characters): Indicates the country where the ISRC is assigned.
> * Registrant code (3 characters): Identifies the registrant (usually the record label or artist).
> * Year of reference (2 characters): The year the ISRC was assigned.
> * Designation code (5 characters): A unique code for the specific recording.
> 
> For example, an ISRC might look like this: US-ABC-20-12345.
> 
> It is important to note that a song can have multiple ISRCs if it appears on different albums or in different versions. Each distinct recording or version of the song will be assigned a unique ISRC, allowing for precise tracking and rights management. This system helps in royalty collection, tracking airplay, and ensuring that creators and rights holders are properly compensated for the use of their work.

is there a way to get a copy of these codes from someone and to import into the files itself

**Comment by jljubich** [comment]
The ISRC of a song can vary depending on the album and its origin. This makes obtaining the exact ISRC a challenge, especially when trying to do so automatically. Here are some strategies you might consider to improve accuracy in obtaining ISRCs:

Strategy Based on Complete Metadata

To increase accuracy, you could use additional metadata, such as the album name, song duration, and track order.

Improved Manual Strategy

Verify in Databases:

Discogs and MusicBrainz: These databases allow album searches and provide more precise information. You can search for the entire album and check the ISRCs of all tracks to ensure they match.
Use Specialized Software:

Music Tagging Software: Programs like MediaMonkey, Picard (from MusicBrainz), or dBpoweramp can help organize and tag your music collection, and they can automatically search for ISRCs if available in the databases they use.

Additionally, OneTagger has announced in these forums intentions to develop an option for obtaining tags for all songs in an album, but this feature is not currently available.

However, there are not many services that can determine the type of album (e.g., Studio, Single, EP, Live, etc.) based solely on the ISRC. As far as I have seen, Spotify can only indicate whether a song belongs to a compilation album or not. Perhaps DISCOGS be a better cource but still a challenge.

**Comment by Marekkon5** [comment]
1T works on best-effort mode, there is no __exact__ way to determine whether the match is 100% correct (except for using ISRC, but that requires the tracks to have ISRC, and only few platforms support it). Also 1T operates on track-basis rather than album basis, so sadly this isn't really an issue we can solve right now. We recommend using Manual Tag (inside QT section), or tagging just small batches, or minimal metadata possible.
