### ISSUE TITLE
Label tag for FLAC

### ISSUE THREAD

**Issue by ALRV84** [Marekkon5/onetagger#397]
When using the AUTO TAG function for FLAC files, the LABEL tag is filled in as ORGANIZATION. And when the Playlist is loaded further into Traktor pro, the LABEL tag is not displayed. Tell me, how do I make the LABEL tag appear in Traktor pro 3 when using the AUTO TAG function?

![tag](https://github.com/user-attachments/assets/3b131f1a-38f3-4bbc-b9ba-d0a93bb7ff27)

You have to manually duplicate the Label tag into the Organization tag so that it appears in the Traktor pro 3 metadata as a Label. And the essence of autocomplete is lost.

**Comment by Marekkon5** [comment]
Hello, please try the latest Actions build, you can download it on the top of the page. It writes to LABEL tag now.

**Comment by ALRV84** [comment]
Please send me the link or show it in a screenshot!  I didn’t quite
understand where to look)

ср, 24 июл. 2024 г., 12:34 Marekkon5 ***@***.***>:

**Comment by ALRV84** [comment]
I'm currently using oneTagger version 1.7.0.  for Windows

ср, 24 июл. 2024 г., 12:40 Алексей Родин ***@***.***>:

**Comment by Marekkon5** [comment]
![image](https://github.com/user-attachments/assets/e58d1660-1ef9-43e1-97f4-d075dbaf8cca)
![image](https://github.com/user-attachments/assets/a63847eb-e468-4408-a5ff-e89be921f173)
![image](https://github.com/user-attachments/assets/951323e5-1a7e-41e7-aae1-2b6c69152561)

**Comment by ALRV84** [comment]
Super!  Thank you

ср, 24 июл. 2024 г., 12:54 Marekkon5 ***@***.***>:
