### ISSUE TITLE
Errors but the songs found in Beatport

### ISSUE THREAD

**Issue by cryptotabluvox** [Marekkon5/onetagger#40]
First run with 100% strictness and resulted 3 errors. Second run with 0% strictness, 2 failed and 1 wrong tag. default.zip is the one from first run. done.zip is the second run.

Track URLs:
https://www.beatport.com/track/keepin-it-jazz/15462829
https://www.beatport.com/track/equinox/15585299
https://www.beatport.com/track/hygge/15585285

ZIP URL:
https://drive.google.com/drive/folders/1g9ht7XMxbPhPjeOEp4Zt0UyuOMCCR0I-?usp=sharing

[onetagger.log](https://github.com/Marekkon5/onetagger/files/7080267/onetagger.log)

**Comment by Marekkon5** [comment]
I was able to find the 2 songs on default settings (70% strictness) on the latest "beta" version. You can download it in the Actions tab on GitHub.
As for `Samuele Scelfo - Hygge (Extended)` - the track metadata and name suggest it's an Extended version, however the one you linked is Original Mix. (I wasn't able to find the extended manually either, just the original mix one). Therefore 1T can't find it.

**Comment by cryptotabluvox** [comment]
I see. Btw, where can I download the beta version?

**Comment by Marekkon5** [comment]
https://www.youtube.com/watch?v=qLz_X4c9XSM

**Comment by cryptotabluvox** [comment]
alright thanks for the assist. have a nice day :)
