### ISSUE TITLE
Mix Name for  AUTO RENAME

### ISSUE THREAD

**Issue by pritvorshik** [Marekkon5/onetagger#401]
Hello. Thank you very much for your hard work. Please tell me how to add the "Mix Name" field from "EDIT TAGS" for  AUTO RENAME. It displays the remixer or the original, extended mix.

**Comment by Marekkon5** [comment]
The "Mix Name" field in Edit Tags is registered as `TIT3` for ID3. So you can use `%TIT3%` or `%version%` (since that maps to TIT3, and VERSION in other formats).
