### ISSUE TITLE
MOOD COLOR TO COLOR TRACK SOFTWARE

### ISSUE THREAD

**Issue by Nickyg001** [Marekkon5/onetagger#404]
Many DJ software, such as Traktor, Rekordbox can highlight the track in the playlist with a color (red, green, yellow, purple, etc.)
Wouldn't it be possible to make the colors of the "MOOD" of ONETagger reflect the colors and TAGs in the various software so as to also have a visual color in the playlists that reflect the MOODs??

At least in this way the COLOR and MOOD function would also be used in DJ software

Example:
With a choice menu you identify the software and the respective preset colors in the options where the name of the MOOD should be identified. The name of the MOOD should always be written in the TAG (to be chosen)

TRAKTOR:
-----------------
Red: HAPPY
Orange: SEXY
Yellow: ANGRY
Green: ...
Blue:
Rose:
Violet:

**Comment by bascurtiz** [comment]
Many? Only Traktor and Rekordbox have such.
And it's not something that's universally linked between the two either.
Also it doesnt save it in metadata, but within their internal database, so alas, we won't support it.
