### ISSUE TITLE
AI to clean auto tag of genres?

### ISSUE THREAD

**Issue by AntoDotco** [Marekkon5/onetagger#412]
Hey guys, I'm soo impressed by your app, congratulations and thank you! So I hate to tag manually, and I auto tag with Genre and Audio Features to classify my tracks in Rekordbox.

Genre is giving a lot of different genres, I'd love to use ChatGPT to clean up the genre and assign a predefined genre based on the content of the field that was auto tag.

For Audio features, I'd love if this data could be used to auto tag mood, energy, vibe, situation, instruments... same thing with some good prompts ChatGPT could totally do that pretty well.

I guess this is more a feature request than a question, but i was wondering if it's something you got in the timeline - auto tagging assisted by AI?

Thanks!

**Comment by Marekkon5** [comment]
Hello, ChatGPT is a paid product (so the user would have to supply own key), and such tagging is **highly** opinionated (on what genres to keep, what genres to remove, how to get most prominent style from features etc). 
OneTagger is a "dumb" program, which fetches *exact* metadata the websites provide. Adding ChatGPT support in this way is in my opinion very out of scope, and as mentioned before, opinionated. Therefore sorry, but we won't be adding it. 
However you can always create custom platform or fork the project if you need such functionality. 
Feel free to comment, or open new issues if you have more suggestions or bug reports. 
Thanks

**Comment by AntoDotco** [comment]
Sounds good, thanks for your feedback! I'm just wondering how I can get a clean classification by genre without doing it manually, but I guess outside of ChatGPT with a good prompting, manual tagging is the only option. Thanks

**Comment by Marekkon5** [comment]
There are some services which provide AI-based tagging (mood, genre etc). We might add it, considering several people asked for it
