### ISSUE TITLE
Bulk delete a tag?

### ISSUE THREAD

**Issue by AntoDotco** [Marekkon5/onetagger#414]
Hello,
I put into Comment tag the data from Audiofeatures. I want to delete all the tags in bulk from the comment field, so it's empty again. Is it possible? Thank you

**Comment by bascurtiz** [comment]
For such bulk operation, I suggest to use Mp3tag (free on Windows / paid on macOS).
1. Load in the folder into Mp3tag
2. Select all
3. Right-click > Extended tags
4. Double-click the < keep > of the Comment field
5. Delete < keep > so it's empty and hit OK > OK

![image](https://github.com/user-attachments/assets/1d3a05a0-0efa-426a-8615-738e7ef6e65d)

**Comment by AntoDotco** [comment]
It works perfectly, thank you! And for Mac there is a 7 days free trial :)
