### ISSUE TITLE
Pulling specific beatport track metadata

### ISSUE THREAD

**Issue by cryptotabluvox** [Marekkon5/onetagger#45]
Is there any way to pull specific track metadata because I keep getting the wrong release? Maybe some feature like we put in link in the song's file beforehand so that the tagger can pull the data from the link.

Saved metadata:
https://www.beatport.com/track/wanna-play/12409354

Correct release:
https://www.beatport.com/track/wanna-play/14201221

Also, the track length mismatch.

Song:
https://mega.nz/file/woZlxI7I#ifCf7QQtdJx0yS9XFKfe6_gMT7lHlMvSaerAOyNoiTU

Thanks in advance.

[onetagger.log](https://github.com/Marekkon5/onetagger/files/7192701/onetagger.log)

**Comment by Marekkon5** [comment]
It's implemented for Discogs right now using the `DISCOGS_RELEASE_ID` tag, so I could probably do the same for Beatport. However I will add it earliest next week.

**Comment by cryptotabluvox** [comment]
wow, nice. thanks, can't wait hehe. have a nice day :)

**Comment by Marekkon5** [comment]
Added in latest commit - the tag is `BEATPORT_TRACK_ID`, let me know if it works for you. You can get the binary in Actions tab. Thanks.

**Comment by cryptotabluvox** [comment]
Thanks dev. it's working now :)
