### ISSUE TITLE
Beatport Subgenre

### ISSUE THREAD

**Issue by cryptotabluvox** [Marekkon5/onetagger#47]
Is there any way to pull subgenre from beatport eg. Big Room, Future House from Mainstage. Usually, the tracks get tagged with the main genre. Maybe if the tagger could pull the data to new field Subgenre or even write it to comments. Thanks :)

**Comment by benjaminlewandowski** [comment]
+1 for new subgenre field; wouldn't use comments as those are used by mixed in key

**Comment by Marekkon5** [comment]
Added in latest commit, comment or reopen if you have any issues with it. You can get the binary in the actions tab. Thank you.

**Comment by cryptotabluvox** [comment]
wow, thanks dev :)
