### ISSUE TITLE
feature request: tagged date (if tagging was successful)

### ISSUE THREAD

**Issue by benjaminlewandowski** [Marekkon5/onetagger#49]
Would it be possible to add a 1t_taggeddate tag with the date when the tagging was done (if the tagging was successful)? Or split it to an additional tag like 1t_matched with true/false value.

p.s. thank you for your extreme fast responses and the help you are giving to the whole digital dj community.

**Comment by Marekkon5** [comment]
I've added the tagged date in latest commit, as for matched/not matched tag it's complicated right now, because unmatched tracks don't get modified/touched at all. Let me know if it works for you, you can get the binary in Actions tab. Thanks.
