### ISSUE TITLE
Traxsource tagging not working

### ISSUE THREAD

**Issue by KeelDev** [Marekkon5/onetagger#5]
Hi,

Tested on library of 3000 flac tracks and did not find 1 successful traxsource match. All artists and titles are complete.
Did extensive testing on a single track which i know is on traxsource: (0% strictness)
Johnny Corporate, Choco - Sunday Shoutin' (B Boys Shouting Dub)
This was tagged successfully on both beatport and juno options. 
I am specifically interested in traxsource for certain tags but this appears none functional at the moment.

Great application, keep up the good work.
Please let me know if you need anymore information, cheers

(macOSX Catalina)

**Comment by bascurtiz** [comment]
Strange. Can you drop the logfile here?

path on windows: YourUserName\AppData\Roaming\OneTagger

path on macOS: /Users/YourUserAccount/Library/Application Support/OneTagger

**Comment by KeelDev** [comment]
no log, only folder /Users/username/Library/WebKit/com.marekkon5.onetagger exists and all folders appear empty, what am i missing here? The app was simply unzipped and added to applications.

**Comment by Marekkon5** [comment]
That folder is WebKit cache, not actual data folder. Check /Users/YourUserAccount/Library/Application Support/OneTagger

**Comment by bascurtiz** [comment]
@KeelDev 
Just tested it on latest non-released version of 1T, running Catalina, it's here for me: /Users/macbook/Library/Preferences/com.OneTagger.OneTagger/onetagger.log

Can you check if it's there for you too?

**Comment by KeelDev** [comment]
Hi, just tried it, was in the location /Users/username/Library/Preferences/com.OneTagger.OneTagger/onetagger.log, getting this in the error log when just tried it:
May 24 12:46:36.108 INFO Starting tagger with: 1 files!
May 24 12:46:36.109 INFO Starting Traxsource
May 24 12:46:36.109 INFO Starting tagging: 1 files, 16 threads!
May 24 12:46:37.912 INFO [Traxsource] State: Error, Accuracy: None, Path: /Users/liam/Downloads/0000/Johnny Corporate - Sunday Shoutin' (B. Boy's Shoutin' Dub).flac

**Comment by KeelDev** [comment]
Raw metadata in file:
File = /Users/username/Downloads/0000/Johnny Corporate - Sunday Shoutin' (B. Boy's Shoutin' Dub).flac

Title: Sunday Shoutin' (B Boys Shouting Dub)
Artist: Johnny Corporate, Choco
Year: 2008
Encoded By: reference libFLAC 1.2.1 20070917
Release Time: 2008
Artwork:
	Description = 
	MIME type = image/jpeg
	Picture type = (3) Cover (front)

**Comment by Marekkon5** [comment]
My mistake in Traxsource implementation, which caused all tracks to fail with album / album art tag disabled. Should be fixed on master, I got 100% match on this track. Reopen if doesn't work, thank you.
