### ISSUE TITLE
feature request: filter results

### ISSUE THREAD

**Issue by benjaminlewandowski** [Marekkon5/onetagger#50]
I am unsure how complex this feature would be, but I just ran an auto tag run on a folder with around 600 tracks. Now there are 86 failed tracks and 2 skipped ones. To see which have failed and which have been skipped, I have to scroll through the list and check the icons for the state "manually". It would greatly improve user experience if it would be possible to just press the failed/skipped button on top to filter the list.

**Comment by Marekkon5** [comment]
Added in latest commit, you can get the binary in actions tab. Thanks
