### ISSUE TITLE
Feature Request: Manual selection Mode

### ISSUE THREAD

**Issue by benjaminlewandowski** [Marekkon5/onetagger#52]
Sometimes the same track is on multiple releases, and it would be nice to get the option to manual select the right one. (kinda like beatport pro was "back then") 

![beatport pro interface](https://user-images.githubusercontent.com/64488529/134922975-efc8523b-1761-4e96-80e9-9d427ad9ceaf.png)

Example: I bought "bipolar disorder" from kaiserdisco as part of the best of kd raw 2019 release (https://www.beatport.com/release/best-of-2019/2786480) - but I would like to tag it like it's the version from the "Paranoid EP" (https://www.beatport.com/release/paranoid-ep/2635325)

the only way to do this right now would be to manually change the beatport_track_id to the "correct" one and rescan the file

**Comment by Marekkon5** [comment]
Yeah, but this is project's goal is fully automatic tagger for now, so I won't implement it now. Maybe will consider in future.

**Comment by nmycps** [comment]
That would be a great option. The 1T is a great tagger, but it can often need assistance from the user in selecting which release is correct, which saves a lot of time. Or, perhaps there's a way for 1T to have a threshold of identifying one album as the correct one and using that to tag the other files that may have been skipped or identified with some other release. I've had 1T identify an album correctly save one or several files, that were tagged with another release similar, or it misidentified the tracks completely. For example, I've had a CD that is electronic, house but the track was identified as a punk rock song with a completely different release ID, artwork and everything.

**Comment by Marekkon5** [comment]
After 694 days added this in latest commit. You can get binary from Actions tab to try it. 

Please open new issues if you have any questions / problems regarding to this. 

Thanks

**Comment by benjaminlewandowski** [comment]
I just saw the Merged pull request. I am really thankful that you did put the (extensive) work into this feature even if it's most likely quite niche
