### ISSUE TITLE
Feature Request: Search

### ISSUE THREAD

**Issue by Scorp188** [Marekkon5/onetagger#59]
Would it be possible to add a search to filter songs in Quick Tag? For example I commonly set cue points and use One Tagger simultaneously. A search would streamline this greatly. Same goes for when I listen to a song without my PC nearby with One Tagger. It would be nice to quickly find the song to tag when back at my PC without scrolling or pointing to a directory with that single song. 
Thanks for your great work.

**Comment by Marekkon5** [comment]
Which section do you mean? Quick Tag or Edit tags?

**Comment by Scorp188** [comment]
> Which section do you mean? Quick Tag or Edit tags?

Quick

**Comment by Marekkon5** [comment]
Added in latest commit, you can get the binary in the Actions tab (should be ready in ~30minutes). Thanks
