### ISSUE TITLE
Quick Tag does not load any file.

### ISSUE THREAD

**Issue by rosgr100** [Marekkon5/onetagger#6]
Hi, latest masters are not loading any file for quick tagging although i am setting the path to a folder through the settings. 
Edit tags function is working correctly.

**Comment by Marekkon5** [comment]
Is there anything in logs? In recent masters I've added extension filter to QuickTag, however that shouldn't really change anything, since Edit Tags uses the same filter.

**Comment by rosgr100** [comment]
No, i don't see anything relevant in the logs.

Something weird is that it actually seems to load something as there is a navigation bar but the tracks are not visible.

![Screenshot 2021-05-29 143743](https://user-images.githubusercontent.com/74199552/120068935-be831b00-c072-11eb-9fcd-12fff1e2f82c.png)

![Screenshot 2021-05-29 143821](https://user-images.githubusercontent.com/74199552/120068942-c80c8300-c072-11eb-9c45-0202d94806b3.png)

**Comment by Marekkon5** [comment]
1. Are you using the latest master from tonight? I fixed simillar bug to this
2. Can you check the JS console? (Open `http://localhost:36913` in your browser, click Quick Tag and F12 to see it).

**Comment by rosgr100** [comment]
Yes, i am using the latest build.

Here is the JS console logs.

[JScon.txt](https://github.com/Marekkon5/onetagger/files/6564630/JScon.txt)

**Comment by Marekkon5** [comment]
Thank you, I don't see any obvious problem / solution yet.

1. Which formats do you use? MP3/FLAC/M4A? Do you have set the tags for mood/custom values for all the formats?
2. Can you try making a backup of settings.json and deleting them to see if that same folder works on clean settings?

Sharing your current settings.json would also help reproducing the bug for me, if you do, delete manually your path and discogs token from it. Thank you.

**Comment by rosgr100** [comment]
Removing the old json solved the issue.

Do you still need the old one?

**Comment by Marekkon5** [comment]
Not really, 1.1 will require settings reset anyway due to breaking changes.
