### ISSUE TITLE
Feature Request: Spotify Tagging

### ISSUE THREAD

**Issue by whoisthis0** [Marekkon5/onetagger#60]
I would love to be able to tag my local files using Spotify's metadata, if you could add that feature I would appreciate it so much

**Comment by Marekkon5** [comment]
I've added it in latest commit, you can get the binary from the `Actions` tab, lemme know if it works for you.

**Comment by whoisthis0** [comment]
I keep getting "INVALID_CLIENT: Invalid redirect URI" when setting up the program to use Spotify, and I think I put the correct Callback URL, Client ID and Client Secret

**Comment by Marekkon5** [comment]
Have you set and saved the Redirect URI on Spotify's website in the Edit App section? It should be `http://127.0.0.1:36914/spotify` there.

![image](https://user-images.githubusercontent.com/15169286/140312515-3db1a731-54cd-4aba-9af6-aff8b38eaa3f.png)

**Comment by whoisthis0** [comment]
Yes, I did.
![image](https://user-images.githubusercontent.com/93047183/140312772-168bbcfa-cd9c-4e8b-b019-9805525e63e3.png)

**Comment by Marekkon5** [comment]
Could you please provide full OneTagger log?

In OneTagger go to settings (top right) > General > Open Data Folder. And there `onetagger.log`.

**Comment by whoisthis0** [comment]
[onetagger.log](https://github.com/Marekkon5/onetagger/files/7474749/onetagger.log)
Is this it? The button wasn't working so I had to manually look for it, hope that's the correct file

**Comment by Marekkon5** [comment]
Yes, however it is empty. Where did you get the `INVALID_CLIENT: Invalid redirect URI` error? Can you send a screenshot of it? Maybe close and reopen onetagger so the log updates. Thanks

**Comment by whoisthis0** [comment]
I got the error after clicking login, it automatically opens a browser tab with the "INVALID_CLIENT: Invalid redirect URI" message, and the log says the same after reopening onetagger. Here are screenshots
![image](https://user-images.githubusercontent.com/93047183/140314868-6244b2d4-4310-409e-8c85-039bfac66570.png)
![image](https://user-images.githubusercontent.com/93047183/140315128-80273a61-43a8-4f5e-8c27-d49d95b339bb.png)

**Comment by Marekkon5** [comment]
Can you please try changing the Redirect URI in Spotify to `http://localhost:36914/spotify`

**Comment by whoisthis0** [comment]
That worked, thank you!

**Comment by Marekkon5** [comment]
It's a bug, I've fixed it in latest commit - so now `http://127.0.0.1:36914/spotify` should work properly. (You probably don't have to change anything because the login is now cached).

**Comment by whoisthis0** [comment]
Again, thank you so much, I was looking for a Spotify tagger for weeks and I just couldn't find one but now that OneTagger has it I don't need to use other ones
