### ISSUE TITLE
Beatsource reporting weird BPMs

### ISSUE THREAD

**Issue by jonathanherdt** [Marekkon5/onetagger#62]
The way BeatSource inside OneTagger reports BPMs is puzzling.

First off, BeatSource gives me 5-digit BPMs that iTunes can't read. One example would be `12593` for the song "Because the Night" from Patti Smith. I first thought this 5-digit BPM would be a comma-separated number with a missing comma, ie 125.93. This doesn't line up, though, because the reported BPM is still off. When checking with what BeatSource gives us (see [here](https://www.beatsource.com/search?q=because%20the%20night%20patti%20smith), the result with the ID 1732229 which is the top one for me), we can see that BeatSource actually reports a BPM of 113.

More examples:
Patti Smith Group - Because the Night (OneTagger: 12593, BeatSource: 113, ID: 1732229, [Search URL](https://www.beatsource.com/search?q=because%20the%20night%20patti%20smith))
Mogwai - DT64 (OneTagger: 12595, BeatSource: 130, ID: 2531110, [Search URL](https://www.beatsource.com/search?q=dt64))
De Mthuda - Emlanjeni (OneTagger: 12593, BeatSource: 113, ID: 6541027, [Search URL](https://www.beatsource.com/search?q=emlanjeni))
David Bowie - Heroes (OneTagger: 12593, BeatSource: 112, ID: 1377737, [Search URL](https://www.beatsource.com/search?q=heroes%202017%20remaster%20david%20bowie))
Jimi Hendrix - Hey Joe (OneTagger: 12594, BeatSource: 124, ID: 1982943, [Search URL](https://www.beatsource.com/search?q=jimi%20hendrix%20hey%20joe))
Les Humphries Singers - Mama Loo (OneTagger: 12596, BeatSource: 148, ID: 2134032, [Search URL](https://www.beatsource.com/search?q=les%20humphries%20singers%20mama%20loo))

I'd be happy to help debugging but not sure where to start. I found `src/tagger/beatsource.rs` but it doesn't contain the scraping / API logic.

**Comment by bascurtiz** [comment]
https://gyazo.com/fbe2501ea03945aa8ebdf959981a7602

Looks fine here?

**Comment by bascurtiz** [comment]
![image](https://user-images.githubusercontent.com/34075088/142776579-a37bd8e9-a0c6-4d67-9b4c-304a856a2cd1.png)
Looks fine in iTunes too.

**Comment by jonathanherdt** [comment]
Hey, sorry for the late reply. All of the files are `.m4a`

**Comment by Marekkon5** [comment]
Thanks, it seems 1t writes the BPM as text rather than 16bit number, which iTunes wants. Ill fix it on the weekend.

**Comment by Marekkon5** [comment]
I've just pushed a fix for this, you can get the binary from Actions tab (it should be ready in ~30 minutes). Let me know if it works for you. Thanks

**Comment by jonathanherdt** [comment]
Works flawlessly, thanks a lot! 🙏
