### ISSUE TITLE
Unable to use custom FLAC seperator - existing tags not recognized

### ISSUE THREAD

**Issue by gabrielsoule** [Marekkon5/onetagger#63]
The app gets confused when I try to use a custom FLAC separator (in particular, I typed in the string `, `, which is the same as the default id3 separator). All other configuration options are default & unchanged, and I'm running the release version 1.3.0 from the website.

To reproduce: I try to add some tags to a FLAC file, like so: Everything looks fine. 
![bug1](https://user-images.githubusercontent.com/5464864/144280791-f18a852a-4ee6-4393-bfa7-71c33e1acd7a.png)

Then, I save the edits to the track, move to another track in the list, and return to the tagged track. The tags are still present in the track list entry, but the panel to the right doesn't seem to recognize them (notice that no tags are highlighted on the right panel). 
![bug2](https://user-images.githubusercontent.com/5464864/144280916-114dde15-9585-49f8-9473-92121d584ff7.png)

When I try to remove existing tags by clicking on them in the panel to the right, the program instead adds new copies of the existing tags, since it doesn't seem to know that the tags are already present (even though they seem to be parsed correctly by whatever functionality renders the track entry in the center list).
![bug3](https://user-images.githubusercontent.com/5464864/144281246-d436336e-0e78-485d-b378-bdad349b9062.png)

This problem persists even when I restart the program. The list in the center renders the tags correctly, but the panel to the right think that they don't exist, and therefore adds duplicate tags instead of removing existing ones when a tag is clicked.

The tags, incorrect as they are, are being saved in the correct format. Observe: 
![image](https://user-images.githubusercontent.com/5464864/144282707-1d38c9df-8ef4-4219-8861-65ecc6c7e201.png)

For context: by default, it seems that OneTagger saves FLAC tags in a sort of array format, where there is one tag per entry in the FLAC format's comment array (I'm not an expert on these formats, but I think that this is how it works). Unfortunately, Traktor (for instance) only looks at the first entry in the FLAC comment array, which means I instead need to have all tags concatenated into a single comma-seperated entry (just like the default id3 handling). Hence my desire to use `, ` as the FLAC separator. 

Thanks!

**Comment by Marekkon5** [comment]
Hello, I've just pushed a fix for this, you can get the binary from the Actions tab. Let me know, if it works for you. Thanks

**Comment by gabrielsoule** [comment]
Sure thing mate. The most recent build failed, but I'll check it out when you patch it (I'm on Windows). Thanks for all your work on this project!

**Comment by Marekkon5** [comment]
I'll take a look this afternoon, it seems that NodeJS has been updated and is broken on the Github Actions VM.

**Comment by Marekkon5** [comment]
Okay the Windows build is successful now, let me know if it solves your bug. Thanks

**Comment by gabrielsoule** [comment]
Seems to solve the issue. Thanks! There may still be a couple elusive little bugs in the system: in one instance, I noticed that the software had appended the separator at the beginning of the string before any tags, i.e. `,tag1,tag2,tag3,... `. Can't figure out exactly how to reproduce it though, and it doesn't seem common, so don't worry. If I can find a reliable way to reproduce the problem I'll open a new report... but otherwise, I think it's good to go. Thanks for the fix!

**Comment by Marekkon5** [comment]
It is probably because you had 2 tags (one empty and one with the values). Aka some leftovers from writing without the tag separator. But that is just a guess. Thanks for testing.
