### ISSUE TITLE
Possibility of validate the autotag

### ISSUE THREAD

**Issue by maxananas** [Marekkon5/onetagger#65]
Hi, there,
First of all thank you for your work, the application works very well!
Just maybe a possibility of improvement: the ability to validate or refuse a tag proposed automatically by the program. It sometimes happens that the tag is not the right one identified (artist, album or even name of the song). Being able to validate before the tag is overwritten on the file would be great!
Thanks again for this!

**Comment by Marekkon5** [comment]
There has been similar issues for this, but my point still remains - currently it's an auto tagger. So I will not be adding manual tagging/selection now. Maybe in future, when we figure out how should it be integrated. Sorry for the inconvenience.

**Comment by maxananas** [comment]
No problem ! thanks for the answer :)
