### ISSUE TITLE
Windows installer flagged by SmartScreen and performs reboot without warning

### ISSUE THREAD

**Issue by StoneCut** [Marekkon5/onetagger#67]
The Windows installer gets flagged by Windows 10's SmartScreen for whatever reason (haven't had that issue for ages with any other open source product). That prompted me to check the installer with Virustotal -> it was clean.

Somewhat relieved I went ahead and circumvented the SmartScreen warning only to then experience a reboot at the end of installation without any sort of warning or ability to prevent it. Thanks for that, my open work in other applications got lost... I don't even know why it had to reboot. There's almost no need for that on Windows, ever.

I really wanted to try OneTagger but this is not the way to build trust in a product.

Oh yeah, there's also no uninstaller for the product. Just great.

**Comment by Marekkon5** [comment]
1. BasCurtiz submitted it for review for MS Defender, so we don't know why you got the warning. Did you use latest release or the Actions build? 

2. The reboot at the end of installation - again sorry for that, but it's a WebView2 issue which we doesn't have fix and we can't reliably reproduce it either. OneTagger depends on it, so we can't just remove it. It uses the official Microsoft evergreen/bootstrap installer. On up-to-date clean Windows installs or Windows 11 it doesn't happen. We'll try to report it to WebView2 as an issue.

3. Uninstaller is present and there is code in NSIS for creating it. Did you check the install folder? It should be there.

OneTagger is fully opensource, so feel free to check any code if you have suspicions or don't trust it. Sorry for the inconveniences.

**Comment by StoneCut** [comment]
Thanks for the quick reply and sorry for coming across a bit miffed. I was doing some track sorting in Excel and I lost hours of work because of the unexpected reboot.

1. I used the installer linked from the homepage (v1.3.0)
2. My Windows 10 is fully patched/up-to-date.
3. Yes, I found the uninstaller now, thanks. Why doesn't it get added to the standard "Add/Remove programs" functionality of Windows? That's a rather trivial registry entry AFAIK.

I wasn't suspicious per se, the tagging by SmartScreen (which I only ever see about once a year) prompted me to investigate the binary distribution. I don't code (and certainly not in Rust) so checking the source code is of no use to me.

Again, thanks for the quick feedback but you can close this issue now. I'm done with OneTagger, sorry.
