### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by brendan-pike** [Marekkon5/onetagger#69]
On the latest I can't compile/run, I get this error:

   Compiling cssparser v0.27.2
     Running `/home/bedlore/repos/onetagger/target/debug/build/cssparser-9f49bd6ed8404bf4/build-script-build`
error[E0658]: use of unstable library feature 'seek_convenience'
  --> /home/bedlore/.cargo/git/checkouts/rust-id3-6f94e9a55d3d3e5d/f3aa7d8/src/chunk.rs:67:36
   |
67 |             let id3_tag_pos = file.stream_position()?;
   |                                    ^^^^^^^^^^^^^^^
   |
   = note: see issue #59359 <https://github.com/rust-lang/rust/issues/59359> for more information

error[E0658]: use of unstable library feature 'seek_convenience'
  --> /home/bedlore/.cargo/git/checkouts/rust-id3-6f94e9a55d3d3e5d/f3aa7d8/src/chunk.rs:90:28
   |
90 |             let pos = file.stream_position()?;
   |                            ^^^^^^^^^^^^^^^
   |
   = note: see issue #59359 <https://github.com/rust-lang/rust/issues/59359> for more information

error[E0658]: use of unstable library feature 'seek_convenience'
   --> /home/bedlore/.cargo/git/checkouts/rust-id3-6f94e9a55d3d3e5d/f3aa7d8/src/chunk.rs:121:14
    |
121 |             .stream_position()?
    |              ^^^^^^^^^^^^^^^
    |
    = note: see issue #59359 <https://github.com/rust-lang/rust/issues/59359> for more information

error[E0658]: use of unstable library feature 'seek_convenience'
   --> /home/bedlore/.cargo/git/checkouts/rust-id3-6f94e9a55d3d3e5d/f3aa7d8/src/chunk.rs:183:22
    |
183 |     let pos = reader.stream_position()?;
    |                      ^^^^^^^^^^^^^^^
    |
    = note: see issue #59359 <https://github.com/rust-lang/rust/issues/59359> for more information

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `id3`

Caused by:
  process didn't exit successfully: `rustc --crate-name id3 --edition=2018 /home/bedlore/.cargo/git/checkouts/rust-id3-6f94e9a55d3d3e5d/f3aa7d8/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=4b85a69abb02594d -C extra-filename=-4b85a69abb02594d --out-dir /home/bedlore/repos/onetagger/target/debug/deps -L dependency=/home/bedlore/repos/onetagger/target/debug/deps --extern bitflags=/home/bedlore/repos/onetagger/target/debug/deps/libbitflags-962552bb38271636.rmeta --extern byteorder=/home/bedlore/repos/onetagger/target/debug/deps/libbyteorder-60cc69fd001777f3.rmeta --extern flate2=/home/bedlore/repos/onetagger/target/debug/deps/libflate2-98e7759d391ee352.rmeta --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...

**Comment by Marekkon5** [comment]
What's your rust version? `rustup toolchain list` Maybe the dependency uses a function that was stabilized in newer version. You can update by running `rustup update`


(also btw you can just use the CI binaries rather than compiling from source).

**Comment by brendan-pike** [comment]
I updated rust - stable-x86_64-unknown-linux-gnu (default) to the latest, this time if gets through but fails at the very end. Not to worry, I hadn't seen the CI builds before, so I'm running that one now and will see how it goes.
