### ISSUE TITLE
Request: Add option to treat Discogs "Style" as custom tag when auto-tagging

### ISSUE THREAD

**Issue by deeprhythms** [Marekkon5/onetagger#7]
Context: Auto tagging with Discogs.
For electronic music, Discogs' main genre is Electronic which isn't of much use. On Discogs, the release's Style has more relevant sub-genre information.

Currently when auto-tagging,  Discogs' "Style" is read and One Tagger creates a custom id3v2.4.0. tag called "STYLE" and places the data there (for eg. House, Breakbeat). However, this "Style" tag is not read by Rekordbox (or other major platforms AFAIK).

Request: When auto-tagging, allow users to treat Discogs Style as a custom tag and write the data in comments (COMM)

**Comment by bascurtiz** [comment]
Hmm, you can merge it to Genre tag, or don't fetch Genre, but write Style instead to Genre. since after-all Style is basically Genre, but more detailed, let's say sub-genre, depending how you look at it.

Wouldn't that suffice?

![image](https://user-images.githubusercontent.com/34075088/120531518-01305480-c3df-11eb-94c3-eac5404501f9.png)

**Comment by deeprhythms** [comment]
Not really, but my use case might be a bit special. I'd like to keep the genres quite clear ie. "Deep House" & "Breakbeat" rather than "Deep House, Breakbeat" if I were to merge Discogs Styles to genre tag as there can be multiple styles. It might be more to do with Discogs as the Style (or sub genre) is per release and not per tracks.

But to my use case, maybe this will clarify it a little.
- I tag my tracks based on the content of the track ie. genre, situation, sub-genre/style (very loose here), mood (multiple! Like one track could have Melancholic, hypnotic, raw) & components.
- This way I can use RB's Intelligent playlists like "Give me all the tracks where genre is Electro and comments include Dystopian, Peak, Distorted kick" or "Give me all the tracks added in the last 3 months labeled with sub bass, dreamy and build-up"
- I buy 99% of my digital music from Bandcamp so no genre or style tags, that's why auto-tagging would be handy
-

**Comment by bascurtiz** [comment]
Make sense, we'll look into it!

**Comment by Marekkon5** [comment]
I've added option to write Discogs styles to custom tag in the latest commit. You can get binary in actions tab. Let me know if it works, thank you.

**Comment by deeprhythms** [comment]
Excellent! Did a quick test and it seems to be working as it should, thanks a bunch!
