### ISSUE TITLE
Deleting Mood tag

### ISSUE THREAD

**Issue by lxape** [Marekkon5/onetagger#70]
Hi guys,

Thanks a lot for creating this amazing app. 

I have one question: How can I remove a Mood from a song? 

I deleted the "Mood"-Tag via the "Edit Tags". However, the tag remains whenever I open the song in the "Quick Tags".

Many thanks in advance and best regards,

L

**Comment by Marekkon5** [comment]
You can just click the same mood on the left second time to remove it.


However it's weird that it didn't disappear after removing in Edit Tags. Looks like a bug, ill take a look tomorrow.

**Comment by bascurtiz** [comment]
@lxape 
I can't seem to replicate your issue.
Did you maybe forgot to hit Save in Edit Tags?

https://user-images.githubusercontent.com/34075088/148537676-12669f42-6e3e-410e-8b46-d0ebce953169.mp4

**Comment by nico-ottati** [comment]
Same it's still happening to me, even after this last update.

**Comment by bascurtiz** [comment]
@nico-ottati It's fixed in the latest commit you can find under the Actions tab here on Github.
Download the binary from there. 
See also how-to (must be logged into Github): https://youtu.be/qLz_X4c9XSM

**Comment by Marekkon5** [comment]
Seems to be working correctly, inactivity
