### ISSUE TITLE
Custom tag separator doesn't work

### ISSUE THREAD

**Issue by rshea0** [Marekkon5/onetagger#71]
I'm using `/` as a custom separator. My songs show all my custom tags as a single tag.

![image](https://user-images.githubusercontent.com/1417838/148335183-367c6e16-678d-4f1d-aa5b-1017938259f7.png)

**Comment by onetagger** [comment]
Did you set the separator to `/` in Settings?

![image](https://user-images.githubusercontent.com/83558131/148373657-3c1fffb6-137d-4531-bedd-5a18ed93efae.png)

**Comment by rshea0** [comment]
Yes. It's really weird because once I edit and save the tag, the vibes are split out into multiple chips like they should be, but once I reload the page, they're back to being a single chip.

I'll record a video of what's happening later today.

**Comment by rshea0** [comment]
Ok here's a video of the issue. Very strange. I looked through the related code myself but couldn't figure out why this might be happening.

Thanks!

https://user-images.githubusercontent.com/1417838/148474337-f58028c8-a1b0-4689-8318-7bff2e02f01d.mp4

**Comment by bascurtiz** [comment]
Thanks for the video!
Strange indeed... I've tried to replicate, but I can't.
Even after switching to Audio Features, or adding tags from the right panel.
Maybe related to file format? I've used mp3.

Could you upload 2-3 tracks in a zip, so I can inspect further?

**Comment by rshea0** [comment]
Strange, I'm using mp3 as well.

Here's the first 2 tracks and my settings.json file.

[One Tagger Bug.zip](https://github.com/Marekkon5/onetagger/files/7831203/One.Tagger.Bug.zip)

**Comment by Marekkon5** [comment]
I copied your separator settings and couldn't reproduce it. What version are you using? 1.3.0 from website or the latest Github Actions build? If the first one, try downloading the latest Github Acitons build. Thanks

**Comment by rshea0** [comment]
I was using 1.3.0 from the latest GitHub release. I just installed the latest build and it's working now! It's also now showing the rating year and key as well.

One issue I have now is that it's only showing the first genre. Will there be support for multiple genres or subgenres in the future?

**Comment by SunwalkerDJ** [comment]
> I was using 1.3.0 from the latest GitHub release. I just installed the latest build and it's working now! It's also now showing the rating year and key as well.
> 
> One issue I have now is that it's only showing the first genre. Will there be support for multiple genres or subgenres in the future?

A little offtop:

I don't understand anything about programming and backend
Could you send me a compiled file of the latest build, if you have one?

Thx! My email: mail@sunwalker.dj

**Comment by Marekkon5** [comment]
> > I was using 1.3.0 from the latest GitHub release. I just installed the latest build and it's working now! It's also now showing the rating year and key as well.
> > One issue I have now is that it's only showing the first genre. Will there be support for multiple genres or subgenres in the future?
> 
> A little offtop:
> 
> I don't understand anything about programming and backend Could you send me a compiled file of the latest build, if you have one?
> 
> Thx! My email: [mail@sunwalker.dj](mailto:mail@sunwalker.dj)

You can just click the Actions tab on top in Github to get the latest precompiled builds.

**Comment by Marekkon5** [comment]
> I was using 1.3.0 from the latest GitHub release. I just installed the latest build and it's working now! It's also now showing the rating year and key as well.
> 
> One issue I have now is that it's only showing the first genre. Will there be support for multiple genres or subgenres in the future?

For long time we said, that we decided that genres should be a single-value and that you can use custom tag for it, however a bunch of people requested this so, I've changed it. You can now have multiple genres in the latest commit. You can get the binary in actions.

**Comment by rshea0** [comment]
Awesome! Thank you so much for looking into this so quickly

**Comment by SunwalkerDJ** [comment]
> > I was using 1.3.0 from the latest GitHub release. I just installed the latest build and it's working now! It's also now showing the rating year and key as well.
> > One issue I have now is that it's only showing the first genre. Will there be support for multiple genres or subgenres in the future?
> 
> For long time we said, that we decided that genres should be a single-value and that you can use custom tag for it, however a bunch of people requested this so, I've changed it. You can now have multiple genres in the latest commit. You can get the binary in actions.

Thanks! This is a very useful innovation

But it would be cool to add the possibility of choosing a custom separator for genres
I think it would be useful for many people:

For example, my genres are always in this format:
Disco / Funk / Latin

**Comment by Marekkon5** [comment]
The custom separator in QuickTag applies to genre too.
