### ISSUE TITLE
Sequential tag recording [Bug?]

### ISSUE THREAD

**Issue by SunwalkerDJ** [Marekkon5/onetagger#72]
Hi! Thanks for the great utility

Is it possible to optionally make the tags recorded in the order in which they are set in the right menu?

That is, if there is a column with tags on the right:

#Smooth
#Dark
#Deep

I would like the tags to be written not in the order in which I put them, but based on the hierarchy of the right menu

If such a function is possible, then from a UX point of view it would be great to make a button for mass correction of all entries in the Quick Tag tab

P.S. Also, it would be cool to modify the cards themselves by adding the year and key
![Снимок-экрана-2022-01-06-в-16 09 33](https://user-images.githubusercontent.com/96825311/148389142-e2ce17e0-34e0-4521-a5ec-9d27378e4e6b.jpg)

Thanks!

**Comment by bascurtiz** [comment]
Great creative way of using Quick Tag's functionality (like replacing Mood with whatever you like)!
The icons in the characteristics - cool! Do they show up in your DJ app too?

@Marekkon5 confirmed he might be able to pull your request off, so stay tuned...

**Comment by Marekkon5** [comment]
I've added the ordering + a sort button (it's on the bottom of right side) + the year and key to the list in the latest commit. You can get the Actions tab on Github. Let me know if it works for you. Thanks

**Comment by 5unwalker** [comment]
> Отличный творческий способ использовать функциональность быстрого тега (например, заменить настроение на все, что вам нравится)! Иконки в характеристиках - круто! Они тоже появляются в вашем диджейском приложении?
> 
> @Marekkon5 подтвердил, что, возможно, сможет выполнить ваш запрос, поэтому следите за обновлениями...

Yes, of course
Emojis are fully functional in Serato (not displayed in Rekordbox & Traktor)

<img width="1212" alt="Снимок экрана 2022-01-07 в 19 57 12" src="https://user-images.githubusercontent.com/96825311/148579152-f9a3757c-fee1-4d48-bb13-bf80109a105d.png">

However, you will have to work on formatting by adding some spaces

**Comment by 5unwalker** [comment]
> Отличный творческий способ использовать функциональность быстрого тега (например, заменить настроение на все, что вам нравится)! Иконки в характеристиках - круто! Они тоже появляются в вашем диджейском приложении?
> 
> @Marekkon5 подтвердил, что, возможно, сможет выполнить ваш запрос, поэтому следите за обновлениями...

Yes, of course
Emojis are fully functional in Serato (not displayed in Rekordbox & Traktor)

<img width="1212" alt="Снимок экрана 2022-01-07 в 19 57 12" src="https://user-images.githubusercontent.com/96825311/148579302-16ec0ca9-1286-4845-9d3f-c2639069aa8f.png">

However, you will have to work on formatting by adding some spaces
