### ISSUE TITLE
Unsaved warning whenever switching tracks

### ISSUE THREAD

**Issue by rshea0** [Marekkon5/onetagger#74]
In quick tag, even if I haven't made any changes, I always get warned that I have unsaved changes whenever I select a new track.

**Comment by bascurtiz** [comment]
Yes, we are aware, thank you for reminding us!

**Comment by rshea0** [comment]
Glad y'all are already on top of it. Keep up the great work! <3

**Comment by Marekkon5** [comment]
@rshea0  I've fixed it in this commit, you can get the binary from actions tab to test it out. Leave a comment or open another issue if you have any more issues. Thanks.
