### ISSUE TITLE
Feature Request:  Chrome OS support or Linux on Chrome OS support.

### ISSUE THREAD

**Issue by sandu8** [Marekkon5/onetagger#78]
Would be great to be able to install this with linux on ChromeOS support via command line.

**Comment by Marekkon5** [comment]
I don't know how ChromeOS works, but if you have access to a linux container, you should be able to just download the binary and run it in server mode (`./onetagger --server`) and visit http://127.0.0.1:36913 in chrome.

**Comment by sandu8** [comment]
Thank you very much for such a quick response.

I was unable to run it in server mode as my Chromebook is Arm64 based and
it appears your linux binaries are X86-64.

I am using the Lenovo Duet 5 Chromebook running a Qualcomm Snapdragon 7c
Gen2 processor(8 Cores, 8x Kryo ***@***.***) and 8GB LPDDR4 at 2133MHz.

Do you think you will ever have a version for arm devices?

Kind Regards,
Alex Turlea

**Comment by Marekkon5** [comment]
I don't know if Github Actions support arm64 and I dont think I have any devices to compile on. Ill however try and find a way. If you don't wanna wait you can compile from source by following the instructions from README.

**Comment by Marekkon5** [comment]
[onetagger-arm64.zip](https://github.com/Marekkon5/onetagger/files/7928901/onetagger-arm64.zip)

I've managed to compile it on CircleCI arm64 machine. Let me know if it works for you.

```
wget https://github.com/Marekkon5/onetagger/files/7928901/onetagger-arm64.zip
unzip onetagger-arm64.zip
chmod +x onetagger-arm64
./onetagger-arm64
```

**Comment by sandu8** [comment]
Thank you very much for that.   I tried with your instructions, but
received the following error message:

./onetagger-arm64: error while loading shared libraries:
libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or
directory

I am a very novice linux user and not sure what to do.

Cheers,
Alex Turlea

**Comment by Marekkon5** [comment]
You are missing the libGTK (and probably libsndfile) dependencies. I don't know what distro is running inside that linux container, but assuming it's debian/ubuntu, you can run:

```
sudo apt install libsndfile1-dev libwebkit2gtk-4.0-dev
```

**Comment by sandu8** [comment]
Thank you very much for this mate.

This actually worked.  I haven't tried it out yet, but the install is
complete and I was able to access one tagger through the url.

Thanks again mate.
