### ISSUE TITLE
OneTagger does not work at all

### ISSUE THREAD

**Issue by levalencia** [Marekkon5/onetagger#79]
I selected autotag, selected the platforms, the path, and then click on start, Nothing happens

Not sure how to debug this error or how to send you the logs.

If I try quick tag, it says Click Here to select folder, when I click, nothing happens either

**Comment by Marekkon5** [comment]
Hello, what OS are you using?

If Windows, the log is present at %appdata%/OneTagger

**Comment by levalencia** [comment]
MAC Mojave 10.14.6

**Comment by Marekkon5** [comment]
You can try going to http://127.0.0.1:36913 in Chrome or Safari while 1T is running to see if you can reproduce the bug or get any error messages in there.

**Comment by bascurtiz** [comment]
I just tested it on older macOS, High Sierra: all good. So we assume it should work fine on newer versions, like Mojave too.
See video demo: https://youtu.be/4Vk9qrbkVMY

The log file `onetagger.log` you can find here:
Open One Tagger > Settings > General > Open Data Folder

**Comment by levalencia** [comment]
It works in the browser with above URL, the app doesnt work, doesnt do anything like opening folders or autotagging


Weird

**Comment by Marekkon5** [comment]
I don't have a Mac and have 0 experience with them, however we got the same issue when testing on older MacOS versions. So it probably is related to Safari / WebKit version, so if there's a way to update it, you can try it.

However the ""browser"" version has no differences to the app one, so if you just wanna use that, you can start OneTagger in server mode by starting it with `--server` parameter.

**Comment by bascurtiz** [comment]
I've just installed a fresh version of Mojave. One Tagger seems to work ok there too.
See video demo: https://youtu.be/fFA_JUEvrxs

I did notice however, there is some ~2gb Security Update + Safari 14.1.2 available, which I'm installing right now.
I'll check One Tagger's behavior afterwards. If there's a different outcome, I'll let you know.

**Comment by chrish-d** [comment]
Just adding to this — I'm on Monterey 12.1 (21C52) and it works absolutely fine.

**Comment by Marekkon5** [comment]
Seems solved, inactivity
