### ISSUE TITLE
Not matching album on discog

### ISSUE THREAD

**Issue by brendan-pike** [Marekkon5/onetagger#8]
Running linux 1.1.0 version and finding it just skips albums even with a 5% strictness.  It would be good to add some CLI flags for linux.  ie.
--debug 
--verbose
and path import would be great too, eg. ./onetagger /music/my_album to auto-populate with that path

**Comment by Marekkon5** [comment]
1. Discogs - could you send some example albums / tracks that don't get matched?

2. CLI debug / verbose - there isn't much additional debug info at this moment , most gets written to logs in normal mode.

3. Yeah, might add, tho the app is GUI only so it will only autofill the fields.

**Comment by Marekkon5** [comment]
Added the path as CLI arg in latest master.
