### ISSUE TITLE
Curious about how you modify the music tag or music metadata?

### ISSUE THREAD

**Issue by AlanCutFlim** [Marekkon5/onetagger#80]
Hello! I am new in coding and most of the time focus on the frontend. Can you tell me how you modify the music tag? Is there any way for me to modify the music tag in node.js?

Actually i found a library called `music-metadata` on github, it allows node.js to read the meta data of a song, but after reading the readme i am not sure whether it can modify the metadata.

I will appreciate any help or advice, thank you!

**Comment by Marekkon5** [comment]
In node.js you can read and write metadata using:

ID3 (mp3): https://www.npmjs.com/package/browser-id3-writer

FLAC (vorbis): https://www.npmjs.com/package/metaflac-js2


However this is unrelated to OneTagger, so I'll close this issue. For general programming questions you're better off asking somewhere like stackoverflow.com or on Reddit. If you have any issues releated to OneTagger feel free to open another issue.

**Comment by AlanCutFlim** [comment]
Thanks for the reply! I might need do some more research.
