### ISSUE TITLE
Can't add larger album art to Tag

### ISSUE THREAD

**Issue by SunKrocket** [Marekkon5/onetagger#81]
When I write album art to tag I get the 175x175 jpeg from Traxsource instead of the larger 600x600 I'd prefer. Also is there a setting that would write a track number AND **total tracks** to the tag?

Windows 10
OneTagger 1.3.0

**Comment by SunKrocket** [comment]
I see that this issue is obviously beyond anyone's ability to figure out at this time. Thankfully I found a work around that works to near perfection.

**Comment by bascurtiz** [comment]
Nice! Care to share?

**Comment by Marekkon5** [comment]
Fixed in latest commit, you can get the binary from the Actions tab. If you have any more issues comment or reopen. Thanks
