### ISSUE TITLE
Add multiple genres

### ISSUE THREAD

**Issue by chrish-d** [Marekkon5/onetagger#82]
It'd be handy to have the option to add multiple genres. At the moment when I click between them, it swaps them out. I'm thinking in situations where a song sits between various genres but you might want to include them in different smart playlists; ie. `House`, `Deep House`, etc.

**Comment by Marekkon5** [comment]
This actually has been added already, but it's not in the released version yet. You can however try and use it in the development builds - you can download them from the Actions tab on Github. Comment / reopen if you have any issues with it. Thanks
