### ISSUE TITLE
Allow the genre list to scroll horizontally

### ISSUE THREAD

**Issue by chrish-d** [Marekkon5/onetagger#83]
I like the genre where it is, but it does add a bit of a limitation on how many genres you can add.

With only being able to add one genre (#82) you can find yourself needing to add quite a lot of them to be specific (Techno, Minimal Techno, Industrial Techno, etc).

If we could scroll horizontally, this would solve the problem.

**Comment by Marekkon5** [comment]
We've already added the option to select multiple genres, and also added subgenres to this too. However it's not in the released version yet, but you can try and use it in the development builds - you can download them from the Actions tab on Github. Comment / reopen if you have any issues with it, or whether the scrollbar is still needed for you. Thanks

**Comment by chrish-d** [comment]
Multiple genres is a great addition, but I do think having a scrollbar (Windows users could have dragging) would be really useful

I've used this on recent projects. I'm not sure if it's useful for the language this is written in, though:
https://keen-slider.io/

**Comment by chrish-d** [comment]
I just checked the actions tab to download the latest version but I don't see a link anywhere. I had a dig through the processes but could only see reference to `dist/OneTagger-mac.zip` but I'm not sure where this is hosted

**Comment by Marekkon5** [comment]
You have to be logged in into Github, click the latest build 
![image](https://user-images.githubusercontent.com/15169286/152548545-28325038-f82b-47d9-9a0e-63bd79b959f2.png)

And there on bottom click on the file for your platform

![image](https://user-images.githubusercontent.com/15169286/152548617-ae400b03-2bbe-4d9e-9306-f21ccddad2e6.png)

**Comment by chrish-d** [comment]
I just took a look, but I think artifacts must only be visible if you're part of the repo since I can't see them (even when logged in). I'm not sure how your releases work but maybe you could create a beta branch?

**Comment by bascurtiz** [comment]
@chrish-d 
In order to find those artifacts, do it like this: https://youtu.be/qLz_X4c9XSM

**Comment by chrish-d** [comment]
@bascurtiz @Marekkon5 found 'em... turns out I had to scroll past Annotations 😅  my bad!

Anyway, not wanting to derail the topic, I think adding a horizontal scroll to the genre list would be really useful. I have a really diverse catalog of music so having lots of genre options is a must 😄

**Comment by Marekkon5** [comment]
Added in the latest commit, you can get the binary from the Actions tab. If you have any more issues or suggestions feel free to comment or reopen. Thanks
