### ISSUE TITLE
Copy/paste macOS 10.13 issues

### ISSUE THREAD

**Issue by JOJ0** [Marekkon5/onetagger#84]
Hi,
very nice tool. Copying marked text anywhere written in onetagger does not work, nor does pasting something from a website or somewhere else _into_ onetagger work on my installation: 

Onetagger 1.3.0
macOS 10.13 High Sierra

This is especially unhelpful when trying to configure eg. app key and secret to get the Spotify audio features tagger going :-)
Thanks for any hints or fixes :-)

**Comment by bascurtiz** [comment]
For now, just right-click in such input field, and hit Paste.

**Comment by Marekkon5** [comment]
High Sierra isn't supported anymore
