### ISSUE TITLE
In Quicktag screen, where is the save button?

### ISSUE THREAD

**Issue by JOJ0** [Marekkon5/onetagger#85]
Sorry for asking I might just not find it: In quicktag screen, where is the actual "save button" to write mood, genre, etc. to files. I can save when I switch to another track because it asks me that there is unsaved changes. But is there a direct save button or shortcut to do it beforehand.

thanks a lot! great tool btw!

onetagger 1.3.0
macOS 10.13 High Sierra

**Comment by chrish-d** [comment]
I think you can hit `ctrl+s` to save (afaik it's the same on Windows, Mac and Linux (ie. on Mac it's not CMD))

Or there's an "Autosave changes when switching to a different track" option in the general settings which is what I personally use.

**Comment by Marekkon5** [comment]
CTRL+S should work, in the latest commit i've also added support for the mac meta key. You can get the test binary from Actions tab. Comment / reopen if you have any more issues. Thanks
