### ISSUE TITLE
Make genre field editable in Quick Tag list

### ISSUE THREAD

**Issue by chrish-d** [Marekkon5/onetagger#86]
Most of the tracks I have already have a genre, but sometimes they're not really applicable and I want to delete them.

To remove the genres at the moment I have to find them in tag editor, but it'd be really handy if the genre was directly editable in the quick tagger like so:

<img width="1072" alt="Screenshot 2022-02-13 at 18 50 27" src="https://user-images.githubusercontent.com/8567692/153770118-ca79a807-082a-41f5-807c-54642c314ffa.png">

**Comment by bascurtiz** [comment]
Good idea!
just like when clicking CUSTOM NOTE, which brings up a pop-up where you can edit the tags.

**Comment by chrish-d** [comment]
Exactly! The less clicking around users have to do the better. I should really learn Rust so I can properly contribute...

**Comment by Marekkon5** [comment]
I've added a way to remove the existing genres by clicking on them in the track list. Let me know if it works for you / is sufficient enough. You can get the binary in the actions tab. Thanks

BTW: QuickTag is written entirely in Javascript.
