### ISSUE TITLE
add option to skip track already tagged with audio feature

### ISSUE THREAD

**Issue by flovanc** [Marekkon5/onetagger#88]
often on large libraries I have an "ERRO Audio features search track by ISRC error: Spotify API reported error code 400, module: onetagger::ui::audiofeatures"

is it possible to add an option in the audiofeature section to skip a track already tagged with audiofeature ?

**Comment by Marekkon5** [comment]
1. Can you send the name of the specific track, so we can test? 
2. In the latest commit I've added 2 options - to write meta tag and to skip tracks (with the meta tag). It works the same way as autotagger does. You can get the binary in the Actions tab, lemme know if it works for you. 

Thanks

**Comment by Marekkon5** [comment]
Added, inactivity, closing
