### ISSUE TITLE
[Enhancement] Auto tag - Include subfolders checbox

### ISSUE THREAD

**Issue by sakej** [Marekkon5/onetagger#89]
Hi.

It would be great if there was "Include sub folders" checkbox in Auto Tag like it is in settings of Quick Tag

Cheers!

**Comment by Marekkon5** [comment]
Subfolders are automatically included in Autotag.

**Comment by sakej** [comment]
Yes, my point is to user to have an option.
I have lots of music in folders where I have other folders and I do not want to include them all at once.

**Comment by Marekkon5** [comment]
I've added the option in the latest commit. You can get the binary from the Actions tab to test it out. Feel free to comment / reopen if you have any more issues. Thanks
