### ISSUE TITLE
Option to recurse subdirectories when finding files to tag

### ISSUE THREAD

**Issue by Muppetteer** [Marekkon5/onetagger#9]
I want to tag my library but, since file locations are managed by iTunes, every track is stored in a directory structure like so:

iTunes Media/Artist/Album/Track

Therefore if I want to auto tag or quick tag I have to change directories for almost every single track, which is unmanageable. Could you perhaps add an option to recurse down the directory tree to find all files under a starting directory?

**Comment by Marekkon5** [comment]
1. AutoTag is recursive. Just select the parent folder and it will include all subdirectories.

2. As for QuickTag - will consider adding recursive option to settings. However now you can export your playlist as .m3u and use it in QT.

**Comment by Marekkon5** [comment]
Added into Quick Tag on latest master, you can get the binary in Actions tab. Please reopen this issue if you have any problems with it. Thank you.

**Comment by Muppetteer** [comment]
Works great, thanks.
