### ISSUE TITLE
[Enhancement] Auto tag - Stop tagging

### ISSUE THREAD

**Issue by sakej** [Marekkon5/onetagger#90]
Hi.

It would be great if there was STOP button when Auto Tagging is running,
Now all I can do is kill app to stop if I've selected wrong folder and it has like let's say 1000mp and all platforms are selected
or wait about half of hour.

Cheers!

**Comment by Marekkon5** [comment]
Currently due to the way how Autotagger works and multiple threads, stopping it is kinda very difficult. However killing the app is safe.

**Comment by sakej** [comment]
OK, thanks for letting us know.
