### ISSUE TITLE
[Bug] OpenWindowDialog issue

### ISSUE THREAD

**Issue by sakej** [Marekkon5/onetagger#91]
Hi.

Open Window Dialog to pick folder is always partially hidden

![image](https://user-images.githubusercontent.com/15695263/156937648-2bf0fea1-7826-4e57-b7ba-9b5445f3f370.png)

Win 10 1920x1080 (100% scaling)
OneTagger 1.3.0 portable version

Cheers!

**Comment by Marekkon5** [comment]
It's a Windows thing, there is nothing I can do about it. Windows controls the position it spawns in and the size, 1T doesn't. You can however just drag the window.
