### ISSUE TITLE
[Improvment] Skipping in AT and AF

### ISSUE THREAD

**Issue by sakej** [Marekkon5/onetagger#93]
Hi.

1. Add files to AT and check One Tagger Tag option
2. Run AT
3. Go to AF
4. Set the same files to be used
5. In AF set Skip already tagged tracks
6. Run AF - track will be skipped 

Track that have been tagged in AT with option to write OneTagger tag cannot be used in AF,
seems that both apps looks for the same tag for skipping where they should be different, 
so user could use both functions on the same files.

Win 10 (portable)
Build #203

**Comment by Marekkon5** [comment]
However how do you imagine this? Should it write another different tag, so you'll have a bunch of useless tags in your files? Or check whether the prominent tag is present?

**Comment by sakej** [comment]
I would say that one tag would be enough just add value like AT and AF or 1 and 2 or whatever you find to be better, and than app will check with option was allready used and to not descriminate one option over another

**Comment by Marekkon5** [comment]
I've added this in the latest commit the way you suggested it. You can get the binary from Actions tab to test it. Let me know if it works for you and fell free to comment/reopen if you have any more issues.

**Comment by flovanc** [comment]
hello is it not possible to have two different 1T tags in order to be able to use the skip option in AT and in AF in a permanent way?
