### ISSUE TITLE
Discogs Initial Release Year?

### ISSUE THREAD

**Issue by sword55** [Marekkon5/onetagger#95]
The software often finds the YEAR tag of the origin of the file, like from CD compilations.
It would be great if it finds the initial year of the release on the single or E. Like the track is on 12" vinyl for example.

**Comment by Marekkon5** [comment]
OneTagger writes the initial year of the best match on Discogs, which means it's not always able to fetch the original release year.

**Comment by arnaudgst** [comment]
> OneTagger writes the initial year of the best match on Discogs, which means it's not always able to fetch the original release year.

Is it possible to update year tag from discogs best match, only if it is older than the actual year tag in file ? or if there is no year in file metadatas ?
