### ISSUE TITLE
aif and aiff

### ISSUE THREAD

**Issue by sword55** [Marekkon5/onetagger#96]
It skipped files with aif file extension, so i have to rename to aiff soon.

**Comment by Marekkon5** [comment]
Both aif and aiff are supported. Can you send the log?

**Comment by sword55** [comment]
how can i send a private message and send the log?

**Comment by sword55** [comment]
Maybe it is another issue. because i got aif files, but in rekordbox playlists it's marked as a aiff file.
i think i replaced my wav files in the past with aif files, and i used another software to auto change things.

**Comment by Marekkon5** [comment]
WAV isn't supported. You can send log here.

**Comment by sword55** [comment]
Mar 19 14:49:01.711 INFO [Discogs] State: Error, Accuracy: None, Path: D:\TRACK COLLECTION\COLLECTION\TRACKS\Xs-Ive House - Sunday 6 AM.aif, module: onetagger::tagger
Mar 19 14:49:03.028 INFO Discogs fallback search!, module: onetagger::tagger::discogs

**Comment by Marekkon5** [comment]
That means the song wasn't found on Discogs, not that aif is unsupported. Can you find the song on Discogs? Thanks

**Comment by sword55** [comment]
yes. https://www.discogs.com/master/23957-Xs-Ive-House-Monoroid

**Comment by Marekkon5** [comment]
I used the song with the following tags and it matched in 1T succesfuly on default settings. What is the exact title and artist in your song? Also sending log would help because it contains settings for us to double check. 

![image](https://user-images.githubusercontent.com/15169286/159137199-8d1303d1-395b-4b4d-ba84-3dd7da6da938.png)

**Comment by sword55** [comment]
ok, at the title in the tag, there is more words. i think i have to clean up the existing tags of artist and title, first?

**Comment by sword55** [comment]
Thanks, i see it is a tag problem of my files, and not the filetype.

**Comment by Marekkon5** [comment]
Most is cleaned by 1T itself (original mix, radio edition etc). If looks like you have some extras that aren't cleaned - you have to clean it manually or decrease the strictness. You can also share the exact title and artist if you wish to improve OneTagger. Thanks
