### ISSUE TITLE
m3u playlists and m3u8

### ISSUE THREAD

**Issue by sword55** [Marekkon5/onetagger#97]
It would be great, if one tagger supports m3u8 playlists.

**Comment by Marekkon5** [comment]
OneTagger already supports m3u8 playlists. You can drag and drop them to the box under the path in Autotagger or settings for QuickTag.

**Comment by sword55** [comment]
I used the m3u8 List from rekordbox, and i cannot add it

**Comment by Marekkon5** [comment]
What's the error / log?

**Comment by sword55** [comment]
It does not write something about it in the log file. When i drag and drop it, nothing happens, with the rekordbox m3u8 file. I convert this one to m3u with Traktor, then it works.

**Comment by Marekkon5** [comment]
I've just checked - m3u8 works fine for me. Can you send an example playlist/file? Also does the file stay there in the UI or it still remain on `Drag & drop M3U playlist file` after dropping it? Thanks

**Comment by sword55** [comment]
#EXTM3U
#EXTINF:231, - Bolero (Acid House Mix)
D:\EXPORT\Bolero (Acid House Mix).aif

**Comment by Marekkon5** [comment]
We couldn't reproduce it with the same filename and m3u8 file, however it seems like the target file (`Bolero (Acid House Mix).aif`) is missing the artist tag. Could you maybe share the log? Thanks

**Comment by sword55** [comment]
Mar 18 03:36:07.606 WARN Error loading file: Missing track metadata (title/artist or id), module: onetagger::tagger
Mar 18 03:36:07.606 INFO [Discogs] State: Skipped, Accuracy: None, Path: D:\EXPORT\Bolero (Acid House Mix).aif, module: onetagger::tagger
Mar 18 03:36:07.608 WARN Error loading file: Missing track metadata (title/artist or id), module: onetagger::tagger
Mar 18 03:36:07.609 INFO [Discogs] State: Skipped, Accuracy: None, Path: D:\TRACK COLLECTION\COLLECTION\TRACKS\03 Devotion Mix.aif, module: onetagger::tagger

**Comment by Marekkon5** [comment]
Well as you can see - OneTagger needs artist and title tag inside the files to search for them on the platforms. You are missing one of them (it looks like the artist one). Without them 1T can't find the track. You have to add them manually.
