### ISSUE TITLE
[Request] Quick Tag sorting and view options

### ISSUE THREAD

**Issue by TheOnlyTick** [Marekkon5/onetagger#99]
I love the idea of Quick Tag, but in its current form it's pretty limited. It'd be nice if the view had artist, name, genre, etc fields you could sort by, as well as an option to hide some of those fields, for example I don't necessarily need to see the album art when I'm scrolling through it. Being able to sort and find all those tracks that get generically labeled as "Electronic" or "Dance", for example, to use Quick Tag with would be amazing.

**Comment by Marekkon5** [comment]
Added in latest commit. You can get the binary from the Actions tab. Feel free to reopen/comment if you have any more issues. Thanks
